### ISSUE TITLE
migrater: 8f99b8bf-03ff59bf fails to create TicketStatus objects

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket#1316]
```
[INSERT INTO ost_ticket_status SET id = 1, name = 'Open', state = 'open', mode = 3, sort = 1, properties = '{\"description\":\"Open tickets.\"}', created = NOW()] Unknown column 'properties' in 'field list'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(182): osTicket->logDBError('DB Error #1054', '[INSERT INTO os...')
 #1 (root)/include/class.orm.php(221): db_query('INSERT INTO ost...')
 #2 (root)/include/class.list.php(1131): VerySimpleModel->save(true)
 #3 (root)/include/upgrader/streams/core/8f99b8bf-03ff59bf.task.php(31): TicketStatus::__create(Array)
 #4 (root)/include/class.upgrader.php(372): SequenceLoader->run('60')
 #5 (root)/include/class.upgrader.php(122): StreamUpgrader->doTask()
 #6 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()
 #7 [internal function]: UpgraderAjaxAPI->upgrade()
 #8 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
 #9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader', NULL)
 #10 (root)/scp/ajax.php(186): Dispatcher->resolve('/upgrader')
 #11 {main}
```

Looks like the task needs to be moved to the last upgrade patch.

**Comment by greezybacon** [comment]
@kordianbruck it would be nice to have some help. @protich do you know if GitHub allows addition of a teammate with rights to manage issues only?

**Comment by ntozier** [comment]
I could probably assist as well.

**Comment by kordianbruck** [comment]
@greezybacon according to this [help site](https://help.github.com/articles/issues-only-access-permissions/) theres unfortunately no such thing. Any ideas?

**Comment by greezybacon** [comment]
@kordianbruck @ntozier perhaps we can try adding you as a read-only collaborator and see if you have permission to manage the issues

**Comment by kordianbruck** [comment]
@greezybacon sure, if you have a organization account, this should at least allow tagging. Still closing issues is then up to you guys.
