### ISSUE TITLE
develeop-next - Fatal Error after saving Advanced Search 

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#1763]
[24-Feb-2015 18:27:24 UTC] PHP Fatal error:  Uncaught exception 'OrmException' with message 'Model `UserCdata` does not have a relation called `phone`' in /var/www/develop-next/include/class.orm.php:1399
Stack trace:
#0 /var/www/develop-next/include/class.orm.php(1417): SqlCompiler->{closure}('phone', Array, NULL)
#1 /var/www/develop-next/include/class.orm.php(1524): SqlCompiler->getField('user__cdata__ph...', 'TicketModel')
#2 /var/www/develop-next/include/class.orm.php(1552): SqlCompiler->compileQ(Object(Q), 'TicketModel')
#3 /var/www/develop-next/include/class.orm.php(1813): SqlCompiler->compileConstraints(Array, 'TicketModel')
#4 /var/www/develop-next/include/class.orm.php(1836): MySqlCompiler->getWhereHavingClause(Object(QuerySet))
#5 /var/www/develop-next/include/class.orm.php(838): MySqlCompiler->compileCount(Object(QuerySet))
#6 /var/www/develop-next/scp/tickets.php(470): QuerySet->count()
#7 /var/www/develop-next/scp/index.php(17): require('/var/www/develo...')
#8 {main}

  thrown in /var/www/develop-next/include/class.orm.php on line 1399

**Comment by gmt-it** [comment]
To get the error:
Open advanced search -> select another field like phone etc. -> input a search term -> input name of search and save it
![error01](https://cloud.githubusercontent.com/assets/10116166/6417692/8fb0b2cc-beaf-11e4-8739-234eea02bb28.jpg)

After saving clich search:
![error02](https://cloud.githubusercontent.com/assets/10116166/6417705/ad465d5a-beaf-11e4-8206-c1f11609c4c8.jpg)

You got this error:
![error03](https://cloud.githubusercontent.com/assets/10116166/6417732/d72ced46-beaf-11e4-8ec0-59b0818395b0.jpg)


Only way to login again is to delete session cookie.
