### ISSUE TITLE
DB errors during upgrade to 1.10 RC-1

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#2284]
This might be of some help. Anything serious? Should I roll back?
Some seems repeated, but I've added them anyway

```
 DB Error #1091

[EXECUTE stmt] Can't DROP 'updated'; check that column/key exists

 ---- Backtrace ----
 #0 (root)/include/class.setup.php(70): osTicket->logDBError('DB Error #1091',  '[EXECUTE stmt] ...',  false)
 #1 (root)/include/class.setup.php(43): SetupWizard->load_sql('/**\n * @signatu...',  'ost_',  false,  true)
 #2 (root)/include/class.upgrader.php(460): SetupWizard->load_sql_file('/var/www/html/s...',  'ost_',  false,  true)
 #3 (root)/include/class.upgrader.php(386): StreamUpgrader->cleanup()
 #4 (root)/include/class.upgrader.php(124): StreamUpgrader->doTask()
 #5 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()
 #6 [internal function]: UpgraderAjaxAPI->upgrade()
 #7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array,  Array)
 #8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader',  NULL)
 #9 (root)/scp/ajax.php(253): Dispatcher->resolve('/upgrader')
 #10 {main}

-----------------------

 DB Error #1064

[" ))] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '" ))' at line 1

 ---- Backtrace ----
 #0 (root)/include/class.setup.php(70): osTicket->logDBError('DB Error #1064',  '["\n))] You have...',  false)
 #1 (root)/include/class.setup.php(43): SetupWizard->load_sql('/**\n * @signatu...',  'ost_',  false,  true)
 #2 (root)/include/class.upgrader.php(460): SetupWizard->load_sql_file('/var/www/html/s...',  'ost_',  false,  true)
 #3 (root)/include/class.upgrader.php(386): StreamUpgrader->cleanup()
 #4 (root)/include/class.upgrader.php(124): StreamUpgrader->doTask()
 #5 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()
 #6 [internal function]: UpgraderAjaxAPI->upgrade()
 #7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array,  Array)
 #8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader',  NULL)
 #9 (root)/scp/ajax.php(253): Dispatcher->resolve('/upgrader')
 #10 {main}

-------------------------------

[SET @s = (SELECT IF( (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'ost_faq' AND table_schema = DATABASE() AND column_name = 'views' ) > 0, "SELECT 1", "ALTER TABLE `ost_faq` DROP `views`, DROP `score`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"ALTER TABLE `ost_faq` DROP `views`, DROP `score`' at line 9

---- Backtrace ----
#0 (root)/include/class.setup.php(70): osTicket->logDBError('DB Error #1064', '[SET @s = (SELE...', false)
#1 (root)/include/class.setup.php(43): SetupWizard->load_sql('/**\n * @signatu...', 'ost_', false, true)
#2 (root)/include/class.upgrader.php(460): SetupWizard->load_sql_file('/var/www/html/s...', 'ost_', false, true)
#3 (root)/include/class.upgrader.php(386): StreamUpgrader->cleanup()
#4 (root)/include/class.upgrader.php(124): StreamUpgrader->doTask()
#5 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()
#6 [internal function]: UpgraderAjaxAPI->upgrade()
#7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader', NULL)
#9 (root)/scp/ajax.php(253): Dispatcher->resolve('/upgrader')
#10 {main}

----------------------------------

 DB Error #1091

[EXECUTE stmt] Can't DROP 'updated'; check that column/key exists

 ---- Backtrace ----
 #0 (root)/include/class.setup.php(70): osTicket->logDBError('DB Error #1091',  '[EXECUTE stmt] ...',  false)
 #1 (root)/include/class.setup.php(43): SetupWizard->load_sql('/**\n * @signatu...',  'ost_',  false,  true)
 #2 (root)/include/class.upgrader.php(460): SetupWizard->load_sql_file('/var/www/html/s...',  'ost_',  false,  true)
 #3 (root)/include/class.upgrader.php(386): StreamUpgrader->cleanup()
 #4 (root)/include/class.upgrader.php(124): StreamUpgrader->doTask()
 #5 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()
 #6 [internal function]: UpgraderAjaxAPI->upgrade()
 #7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array,  Array)
 #8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader',  NULL)
 #9 (root)/scp/ajax.php(253): Dispatcher->resolve('/upgrader')
 #10 {main}

-----------------------

DB Error #1091

[ALTER TABLE `ost_thread` DROP COLUMN `tid`] Can't DROP 'tid'; check that column/key exists

 ---- Backtrace ----
 #0 (root)/include/class.setup.php(70): osTicket->logDBError('DB Error #1091',  '[ALTER TABLE `o...',  false)
 #1 (root)/include/class.setup.php(43): SetupWizard->load_sql('ALTER TABLE `%T...',  'ost_',  false,  true)
 #2 (root)/include/class.upgrader.php(460): SetupWizard->load_sql_file('/var/www/html/s...',  'ost_',  false,  true)
 #3 (root)/include/class.upgrader.php(386): StreamUpgrader->cleanup()
 #4 (root)/include/class.upgrader.php(124): StreamUpgrader->doTask()
 #5 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()
 #6 [internal function]: UpgraderAjaxAPI->upgrade()
 #7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array,  Array)
 #8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader',  NULL)
 #9 (root)/scp/ajax.php(253): Dispatcher->resolve('/upgrader')
 #10 {main}

--------------------------


[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'helpdesk.ost_translation' doesn't exist

---- Backtrace ----
#0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146', '[SELECT A1.* FR...')
#1 (root)/include/class.orm.php(2659): db_prepare('SELECT A1.* FRO...')
#2 (root)/include/class.orm.php(2653): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(2729): MySqlExecutor->_prepare()
#4 (root)/include/class.orm.php(1499): MySqlExecutor->getArray()
#5 (root)/include/class.orm.php(1322): ModelInstanceManager->fillTo(0)
#6 (root)/include/class.translation.php(899): ResultSet->valid()
#7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
#8 (root)/include/class.list.php(328): CustomDataTranslation::translate('72ccae91ff25b91...')
#9 (root)/include/class.list.php(194): DynamicList->getLocal('name_plural')
#10 (root)/include/class.list.php(456): DynamicList->getPluralName()
#11 [internal function]: DynamicList::getSelections()
#12 (root)/include/class.forms.php(563): call_user_func(Array)
#13 (root)/include/class.forms.php(571): FormField::allTypes()
#14 (root)/include/class.forms.php(995): FormField::getFieldType('text')
#15 [internal function]: FormField->getImpl(Object(DynamicFormField))
#16 (root)/include/class.dynamic_forms.php(638): call_user_func_array(Array, Array)
#17 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->__call('getImpl', Array)
#18 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->getImpl(Object(DynamicFormField))
#19 (root)/include/class.dynamic_forms.php(990): DynamicFormEntryAnswer->getField()
#20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
#21 (root)/include/staff/footer.inc.php(5): Company->__toString()
#22 (root)/scp/upgrade.php(88): require('/var/www/html/s...')
#23 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
#24 (root)/scp/admin.inc.php(16): require('/var/www/html/s...')
#25 (root)/scp/upgrade.php(16): require_once('/var/www/html/s...')
#26 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
#27 (root)/scp/autocron.php(18): require('/var/www/html/s...')
#28 {main}

--------------------------

DB Error #1146

[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'helpdesk.ost_translation' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146',  '[SELECT A1.* FR...')
 #1 (root)/include/class.orm.php(2659): db_prepare('SELECT A1.* FRO...')
 #2 (root)/include/class.orm.php(2653): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2729): MySqlExecutor->_prepare()
 #4 (root)/include/class.orm.php(1499): MySqlExecutor->getArray()
 #5 (root)/include/class.orm.php(1322): ModelInstanceManager->fillTo(0)
 #6 (root)/include/class.translation.php(899): ResultSet->valid()
 #7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
 #8 (root)/include/class.list.php(328): CustomDataTranslation::translate('72ccae91ff25b91...')
 #9 (root)/include/class.list.php(194): DynamicList->getLocal('name_plural')
 #10 (root)/include/class.list.php(456): DynamicList->getPluralName()
 #11 [internal function]: DynamicList::getSelections()
 #12 (root)/include/class.forms.php(563): call_user_func(Array)
 #13 (root)/include/class.forms.php(571): FormField::allTypes()
 #14 (root)/include/class.forms.php(995): FormField::getFieldType('text')
 #15 [internal function]: FormField->getImpl(Object(DynamicFormField))
 #16 (root)/include/class.dynamic_forms.php(638): call_user_func_array(Array,  Array)
 #17 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->__call('getImpl',  Array)
 #18 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->getImpl(Object(DynamicFormField))
 #19 (root)/include/class.dynamic_forms.php(990): DynamicFormEntryAnswer->getField()
 #20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
 #21 (root)/include/staff/footer.inc.php(5): Company->__toString()
 #22 (root)/scp/upgrade.php(88): require('/var/www/html/s...')
 #23 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
 #24 (root)/scp/admin.inc.php(16): require('/var/www/html/s...')
 #25 (root)/scp/upgrade.php(16): require_once('/var/www/html/s...')
 #26 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
 #27 (root)/scp/autocron.php(18): require('/var/www/html/s...')
 #28 {main}

-------------------


[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'helpdesk.ost_translation' doesn't exist

---- Backtrace ----
#0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146', '[SELECT A1.* FR...')
#1 (root)/include/class.orm.php(2659): db_prepare('SELECT A1.* FRO...')
#2 (root)/include/class.orm.php(2653): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(2729): MySqlExecutor->_prepare()
#4 (root)/include/class.orm.php(1499): MySqlExecutor->getArray()
#5 (root)/include/class.orm.php(1322): ModelInstanceManager->fillTo(0)
#6 (root)/include/class.translation.php(899): ResultSet->valid()
#7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
#8 (root)/include/class.list.php(328): CustomDataTranslation::translate('72ccae91ff25b91...')
#9 (root)/include/class.list.php(194): DynamicList->getLocal('name_plural')
#10 (root)/include/class.list.php(456): DynamicList->getPluralName()
#11 [internal function]: DynamicList::getSelections()
#12 (root)/include/class.forms.php(563): call_user_func(Array)
#13 (root)/include/class.forms.php(571): FormField::allTypes()
#14 (root)/include/class.forms.php(995): FormField::getFieldType('text')
#15 [internal function]: FormField->getImpl(Object(DynamicFormField))
#16 (root)/include/class.dynamic_forms.php(638): call_user_func_array(Array, Array)
#17 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->__call('getImpl', Array)
#18 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->getImpl(Object(DynamicFormField))
#19 (root)/include/class.dynamic_forms.php(990): DynamicFormEntryAnswer->getField()
#20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
#21 (root)/include/staff/footer.inc.php(5): Company->__toString()
#22 (root)/scp/upgrade.php(88): require('/var/www/html/s...')
#23 {main}

---------------------

DB Error #1146

[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'helpdesk.ost_translation' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146',  '[SELECT A1.* FR...')
 #1 (root)/include/class.orm.php(2659): db_prepare('SELECT A1.* FRO...')
 #2 (root)/include/class.orm.php(2653): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2729): MySqlExecutor->_prepare()
 #4 (root)/include/class.orm.php(1499): MySqlExecutor->getArray()
 #5 (root)/include/class.orm.php(1322): ModelInstanceManager->fillTo(0)
 #6 (root)/include/class.translation.php(899): ResultSet->valid()
 #7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
 #8 (root)/include/class.list.php(328): CustomDataTranslation::translate('72ccae91ff25b91...')
 #9 (root)/include/class.list.php(194): DynamicList->getLocal('name_plural')
 #10 (root)/include/class.list.php(456): DynamicList->getPluralName()
 #11 [internal function]: DynamicList::getSelections()
 #12 (root)/include/class.forms.php(563): call_user_func(Array)
 #13 (root)/include/class.forms.php(571): FormField::allTypes()
 #14 (root)/include/class.forms.php(995): FormField::getFieldType('text')
 #15 [internal function]: FormField->getImpl(Object(DynamicFormField))
 #16 (root)/include/class.dynamic_forms.php(638): call_user_func_array(Array,  Array)
 #17 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->__call('getImpl',  Array)
 #18 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->getImpl(Object(DynamicFormField))
 #19 (root)/include/class.dynamic_forms.php(990): DynamicFormEntryAnswer->getField()
 #20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
 #21 (root)/include/staff/footer.inc.php(5): Company->__toString()
 #22 (root)/scp/upgrade.php(88): require('/var/www/html/s...')
 #23 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
 #24 (root)/scp/admin.inc.php(16): require('/var/www/html/s...')
 #25 (root)/scp/upgrade.php(16): require_once('/var/www/html/s...')
 #26 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
 #27 (root)/scp/autocron.php(18): require('/var/www/html/s...')
 #28 {main}

--------------------

DB Error #1146

[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'helpdesk.ost_translation' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146',  '[SELECT A1.* FR...')
 #1 (root)/include/class.orm.php(2659): db_prepare('SELECT A1.* FRO...')
 #2 (root)/include/class.orm.php(2653): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2729): MySqlExecutor->_prepare()
 #4 (root)/include/class.orm.php(1499): MySqlExecutor->getArray()
 #5 (root)/include/class.orm.php(1322): ModelInstanceManager->fillTo(0)
 #6 (root)/include/class.translation.php(899): ResultSet->valid()
 #7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
 #8 (root)/include/class.list.php(328): CustomDataTranslation::translate('72ccae91ff25b91...')
 #9 (root)/include/class.list.php(194): DynamicList->getLocal('name_plural')
 #10 (root)/include/class.list.php(456): DynamicList->getPluralName()
 #11 [internal function]: DynamicList::getSelections()
 #12 (root)/include/class.forms.php(563): call_user_func(Array)
 #13 (root)/include/class.forms.php(571): FormField::allTypes()
 #14 (root)/include/class.forms.php(995): FormField::getFieldType('text')
 #15 [internal function]: FormField->getImpl(Object(DynamicFormField))
 #16 (root)/include/class.dynamic_forms.php(638): call_user_func_array(Array,  Array)
 #17 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->__call('getImpl',  Array)
 #18 (root)/include/class.dynamic_forms.php(1374): DynamicFormField->getImpl(Object(DynamicFormField))
 #19 (root)/include/class.dynamic_forms.php(990): DynamicFormEntryAnswer->getField()
 #20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
 #21 (root)/include/staff/footer.inc.php(5): Company->__toString()
 #22 (root)/scp/upgrade.php(88): require('/var/www/html/s...')
 #23 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
 #24 (root)/scp/admin.inc.php(16): require('/var/www/html/s...')
 #25 (root)/scp/upgrade.php(16): require_once('/var/www/html/s...')
 #26 (root)/scp/staff.inc.php(116): require('/var/www/html/s...')
 #27 (root)/scp/tickets.php(17): require('/var/www/html/s...')
 #28 (root)/scp/index.php(17): require('/var/www/html/s...')
 #29 {main}

```

**Comment by greezybacon** [comment]
```[SET @s = (SELECT IF( (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'ost_faq' AND table_schema = DATABASE() AND column_name = 'views' ) > 0, "SELECT 1", "ALTER TABLE `ost_faq` DROP `views`, DROP `score`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"ALTER TABLE `ost_faq` DROP `views`, DROP `score`' at line 9```

```[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'helpdesk.ost_translation' doesn't exist```

I'm confident these two have been fixed

**Comment by fictionedge** [comment]
Do you think it will be safe to upgrade to RC2 ?
