### ISSUE TITLE
develop-next: SQL Error Unknown column '__relevance__' in 'order clause'

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket#2655]
I since the update this morning (somewhere between ecf693120f4a4f4ba712de9daaf7faa6f63f7920 and 8295dfde014ed404c56f90179a966fc9b82cd54e) I get the following SQL error:

```
[SELECT A3.`address` AS `user__default_email__address`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tickets` FROM `ost_ticket` A1 JOIN `ost_user` A2 ON (A1.`user_id` = A2.`id`) LEFT JOIN `ost_user_email` A3 ON (A2.`default_email_id` = A3.`id`) WHERE (A1.`staff_id` = ? OR A1.`team_id` IN (SELECT A1.`team_id` FROM `ost_team_member` A1 WHERE A1.`staff_id` = ?) OR A1.`dept_id` IN (?, ?, ?, ?, ?)) GROUP BY A3.`address` ORDER BY __relevance__ DESC LIMIT 25]

Unknown column '__relevance__' in 'order clause'<br />
<br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1054', '[SELECT A3.`add...')<br />
#1 (root)/include/class.orm.php(2766): db_prepare('SELECT A3.`addr...')<br />
#2 (root)/include/class.orm.php(2760): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2836): MySqlExecutor->_prepare()<br />
#4 (root)/include/class.orm.php(1597): MySqlExecutor->getArray()<br />
#5 (root)/include/class.orm.php(1381): HashArrayIterator->fillTo(0)<br />
#6 (root)/include/ajax.tickets.php(76): ResultSet->valid()<br />
#7 [internal function]: TicketsAjaxAPI->lookup()<br />
#8 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('lookup', Array)<br />
#10 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('lookup', Array)<br />
#11 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/lookup', NULL)<br />
#12 (root)/scp/ajax.php(260): Dispatcher->resolve('/tickets/lookup')<br />
#13 {main}
```

**Comment by slimatic** [comment]
It looks like this relates to a similar issue I am getting on #2656 . This is cause a break the UsersAjaxAPI->search() function.

**Comment by protich** [comment]
@t-oster - Fix posted on #2656

**Comment by t-oster** [comment]
Hi @protich sorry but 1aaa3139d1dfd7236c576b1278261bc820690a1d does not seem to fix the problem. I agree with @slimatic that this is an ORM related SQL problem. Where is this __relevance__ column supposed to be.
These are the code-references I found, but the ORM class is not that easy to read....
![relevance](https://cloud.githubusercontent.com/assets/1052720/10535093/e811f2d8-73df-11e5-9e4a-bf6a3f6efc0f.png)

**Comment by greezybacon** [comment]
It seems to be fixed to me, and reading the code, I don't see where this problem would crop up

**Comment by slimatic** [comment]
@greezybacon please see my comments on #2656 . It seems to be working if you have implemented the use of organizations. I never used the organization feature pre-upgrade. If my testing is correct then folks who have added users to organizations won't see this issue.

**Comment by t-oster** [comment]
Well. I do have organizations. I cannot reproduce this issue anymore right now, but this is because the search often fails in general. This is related to #2667. After this is fixed, I can recheck.

**Comment by slimatic** [comment]
@t-oster You may be able reproduce the error this way.

Test it with two different users - one in an organization and one without an organization.
e.g. user1 - in an organization & user2 - not in an organization

Now go to a ticket and try adding these two users to the ticket as collaborators.
If the issue is properly reproduced you will find that user1 will come up and you will be able to add them to the ticket however with user2, you will not be able to.

This was my test.

**Comment by brookemarshassoc** [comment]
FYI - I received the above error today (osTicket version 1.10).  I don't know how the user generated it.  (should I comment out references to "__relevance__" in `include/ajax.tickets.php`?  I'm not sure what I would be breaking with such an edit.)

**Comment by t-oster** [comment]
Hi. I am using current version 1.10 and still getting this:
```
[SELECT A3.`staff_id` AS `lock__staff_id`, A1.`staff_id` AS `staff_id`, A1.`isoverdue` AS `isoverdue`, A1.`team_id` AS `team_id`, A1.`ticket_id` AS `ticket_id`, A1.`number` AS `number`, A4.`subject` AS `cdata__subject`, A6.`address` AS `user__default_email__address`, A1.`source` AS `source`, A7.`priority_color` AS `cdata__:priority__priority_color`, A7.`priority_desc` AS `cdata__:priority__priority_desc`, A1.`status_id` AS `status_id`, A8.`name` AS `status__name`, A8.`state` AS `status__state`, A1.`dept_id` AS `dept_id`, B0.`name` AS `dept__name`, A5.`name` AS `user__name`, A1.`lastupdate` AS `lastupdate`, A1.`isanswered` AS `isanswered`, B1.`firstname` AS `staff__firstname`, B1.`lastname` AS `staff__lastname`, B2.`name` AS `team__name`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS collab_count, (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS attachment_count, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS thread_count FROM `ost_ticket` A1 JOIN (SELECT Q7.`ticket_id` FROM `ost_ticket` Q7 JOIN `ost_ticket_status` Q8 ON (Q7.`status_id` = Q8.`id`) WHERE ((Q8.`state` = 'open' AND (Q7.`staff_id` = 11 OR Q7.`team_id` IN (7))) OR Q7.`dept_id` IN ('1', '4', '5', '9')) ORDER BY __relevance__ DESC LIMIT 40) A2 LEFT JOIN `ost_lock` A3 ON (A1.`lock_id` = A3.`lock_id` AND A3.`expire` > NOW()) LEFT JOIN `ost_ticket__cdata` A4 ON (A1.`ticket_id` = A4.`ticket_id`) JOIN `ost_user` A5 ON (A1.`user_id` = A5.`id`) LEFT JOIN `ost_user_email` A6 ON (A5.`default_email_id` = A6.`id`) LEFT JOIN `ost_ticket_priority` A7 ON (A4.`priority` = A7.`priority_id`) JOIN `ost_ticket_status` A8 ON (A1.`status_id` = A8.`id`) JOIN `ost_department` B0 ON (A1.`dept_id` = B0.`id`) LEFT JOIN `ost_staff` B1 ON (A1.`staff_id` = B1.`staff_id`) LEFT JOIN `ost_team` B2 ON (A1.`team_id` = B2.`team_id`) WHERE A1.`ticket_id` = A2.`ticket_id` GROUP BY A3.`staff_id`, A1.`staff_id`, A1.`isoverdue`, A1.`team_id`, A1.`ticket_id`, A1.`number`, A4.`subject`, A6.`address`, A1.`source`, A7.`priority_color`, A7.`priority_desc`, A1.`status_id`, A8.`name`, A8.`state`, A1.`dept_id`, B0.`name`, A5.`name`, A1.`lastupdate`, A1.`isanswered`, B1.`firstname`, B1.`lastname`, B2.`name` ORDER BY __relevance__ DESC]

Unknown column '__relevance__' in 'order clause'<br />
<br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1054', '[SELECT A3.`sta...')<br />
#1 (root)/include/class.orm.php(3133): db_query('SELECT A3.`staf...', true, true)<br />
#2 (root)/include/class.orm.php(3180): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(1865): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(1815): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(1794): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(1803): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1463): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1480): CachedResultSet->fillTo(2147483647)<br />
#9 (root)/include/class.orm.php(1489): CachedResultSet->asArray()<br />
#10 (root)/include/staff/tickets.inc.php(419): CachedResultSet->getIterator()<br />
#11 (root)/scp/tickets.php(511): require_once('/kunden/296328_...')<br />
#12 {main}
