### ISSUE TITLE
osTicket 10.10rc2 InconsistentModelException when adding email

### ISSUE THREAD

**Issue by mark-dlc** [osTicket/osTicket#3203]
When going to emails and update an email address by 
adding email fetching a `500 server error` is thrown after (+-) 90 seconds.

`Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: MySQL server has gone away SELECT A1.* FROM `ost_email` A1 WHERE A1.`email_id` = ?'`

This is either with Pop and Imap. The error is only thrown when 'Status' is actually set to enabled.

Full stack trace:
> #0 osTicket/include/class.orm.php(2735): MySqlExecutor->execute()
> #1 osTicket/include/class.orm.php(2811): MySqlExecutor->_prepare()
> #2 osTicket/include/class.orm.php(1540): MySqlExecutor->getArray()
> #3 osTicket/include/class.orm.php(1344): ModelInstanceManager->fillTo(9223372036854775807)
> #4 osTicket/include/class.orm.php(1073): ResultSet->asArray()
> #5 osTicket/include/class.orm.php(1096): QuerySet->all()
> #6 osTicket/include/cla in osTicket/include/class.orm.php on line 2742
> [14-Jun-2016 18:51:32 UTC] PHP Fatal error:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: MySQL server has gone away SELECT A1.* FROM `ost_email` A1 WHERE A1.`email_id` = ?' in osTicket/include/class.orm.php:2742

This is already with mysql and socket timeout set to 300ms in php.ini (hopefully eliminating the fact that this error is caused by a timeout of the MySQL server)

<img width="707" alt="schermafbeelding 2016-06-14 om 21 16 45" src="https://cloud.githubusercontent.com/assets/9111546/16056386/9a3e9b2e-3275-11e6-86b9-f5e7f88eaa9d.png">

**Comment by skinsch** [comment]
wait... so, what's the fix?  did you get this resolved?
