### ISSUE TITLE
osTicket v1.10-rc3 -- Unable to search tickets

### ISSUE THREAD

**Issue by robintoy** [osTicket/osTicket#3208]
When you search tickets you get a blank screen and the following error gets placed in the system information: -

DB Error #1064

```
[SELECT COUNT(*) FROM (SELECT A1.`ticket_id`,  Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1 JOIN (SELECT COALESCE(Z3.`object_id`,  Z5.`ticket_id`,  Z8.`ticket_id`) as `ticket_id`,  SUM(MATCH (Z1.title,  Z1.content) AGAINST ('peter' IN NATURAL LANGUAGE MODE)) AS `relevance` FROM `ost__search` Z1 LEFT JOIN `ost_thread_entry` Z2 ON (Z1.`object_type` = 'H' AND Z1.`object_id` = Z2.`id`) LEFT JOIN `ost_thread` Z3 ON (Z2.`thread_id` = Z3.`id` AND Z3.`object_type` = 'T') LEFT JOIN `ost_ticket` Z5 ON (Z1.`object_type` = 'T' AND Z1.`object_id` = Z5.`ticket_id`) LEFT JOIN `ost_user` Z6 ON (Z6.`id` = Z1.`object_id` and Z1.`object_type` = 'U') LEFT JOIN `ost_organization` Z7 ON (Z7.`id` = Z1.`object_id` AND Z7.`id` = Z6.`org_id` AND Z1.`object_type` = 'O') LEFT JOIN ost_ticket Z8 ON (Z8.`user_id` = Z6.`id`) WHERE MATCH (Z1.title,  Z1.content) AGAINST ('peter' IN NATURAL LANGUAGE MODE) GROUP BY `ticket_id`) Z1 WHERE A1.`ticket_id` = Z1.`ticket_id`) __] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NATURAL LANGUAGE MODE)) AS `relevance` FROM `ost__search` Z1 LEFT JOIN `ost_thre' at line 1

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1064',  '[SELECT COUNT(*...')
 #1 (root)/include/class.orm.php(3121): db_query('SELECT COUNT(*)...',  true,  true)
 #2 (root)/include/class.orm.php(3177): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2631): MySqlExecutor->getRow()
 #4 (root)/include/class.orm.php(1192): MySqlCompiler->compileCount(Object(QuerySet))
 #5 [internal function]: QuerySet->count()
 #6 (root)/include/staff/tickets.inc.php(146): count(Object(QuerySet))
 #7 (root)/scp/tickets.php(492): require_once('/home/hp3-linc1...')
 #8 {main}
```

**Comment by robintoy** [comment]
Server Details are: -
OS: Linux Operating (Not sure which as a Clustered Hosting Platform from Fasthosts UK)
Web Server: Apache
PHP: 5.6.20
MySQL: 5.0.95

**Comment by mlipok** [comment]
To @robintoy please veryfi whether current version stil have this issue.
