### ISSUE TITLE
DB Error 1054 - v1.10-rc3

### ISSUE THREAD

**Issue by odhiambop** [osTicket/osTicket#3289]
Getting this error after backing up my datbase from one machine(v1.9) and trsanfering to updated machine (V1.10-rc-3)
 DB Error #1054

[SELECT A1.`id`,  A1.`content_id`,  A1.`isactive`,  A1.`type`,  A1.`name`,  A1.`body`,  A1.`lang`,  A1.`notes`,  A1.`created`,  A1.`updated` FROM `ost_content` A1 WHERE A1.`type` = 'banner-staff' ORDER BY A1.`name` ASC] Unknown column 'A1.content_id' in 'field list'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1054',  '[SELECT A1.`id`...')
 #1 (root)/include/class.orm.php(3121): db_query('SELECT A1.`id`, ...',  true,  true)
 #2 (root)/include/class.orm.php(3168): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(1753): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(1797): ModelInstanceManager->{closure}()
 #5 (root)/include/class.orm.php(1776): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(1785): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1452): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1462): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1148): CachedResultSet->asArray()
 #10 (root)/include/class.orm.php(1171): QuerySet->all()
 #11 (root)/include/class.page.php(235): QuerySet->one()
 #12 (root)/scp/login.php(26): Page::lookupByType('banner-staff')
 #13 {main}

**Comment by kest874** [comment]
Restart Apache and this should go away.

**Comment by meirg** [comment]
I know this is an old issue, but it should really be added to the upgrade instructions. I run into this after every upgrade and can never remember how to fix

**Comment by ntozier** [comment]
I've never had to restart my webserver after an upgrade.  So...
