### ISSUE TITLE
MySQL 5.7 + GTID CREATE..SELECT Error

### ISSUE THREAD

**Issue by slopokeit** [osTicket/osTicket#3384]
TicketForm::buildDynamicDataView() tries to execute a create table based on a select which violates the new policy when global transaction ids are enabled on the server.

my.cnf
# GTID REPLICATION #
gtid_mode                       = ON
enforce_gtid_consistency        = ON

[CREATE TABLE `ost_ticket__cdata` (PRIMARY KEY
                (ticket_id)) AS SELECT entry.`object_id` as `ticket_id`, MAX(IF(field.id='20',coalesce(ans.value_id, ans.value),NULL)) as `subject`,MAX(CASE WHEN field.id='22' THEN REPLACE(REPLACE(REPLACE(REPLACE(coalesce(ans.value_id, ans.value), '{', ''), '}', ''), '"', ''), ':', ',') ELSE NULL END) as `priority` FROM ost_form_entry entry
            JOIN ost_form_entry_values ans ON ans.entry_id = entry.id
            JOIN ost_form_field field ON field.id=ans.field_id
            WHERE entry.object_type='T' GROUP BY entry.object_id]

Statement violates GTID consistency: CREATE TABLE ... SELECT.

---- Backtrace ----
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1786', '[CREATE TABLE `...')
#1 (root)/include/class.dynamic_forms.php(330): db_query('CREATE TABLE `o...')
#2 (root)/include/class.dynamic_forms.php(315): TicketForm::buildDynamicDataView()
#3 (root)/include/staff/tickets.inc.php(269): TicketForm::ensureDynamicDataView()
#4 (root)/scp/tickets.php(506): require_once('/data/www/ticke...')
#5 (root)/scp/index.php(17): require('/data/www/ticke...')
#6 {main}

**Comment by slopokeit** [comment]
As a temporary workaround, we've changed this to use a View.

        $sql = 'CREATE VIEW `'.TABLE_PREFIX.'ticket__cdata`  
                AS ' . static::getCrossTabQuery('T', 'ticket_id');
        db_query($sql);

**Comment by rsaylor73** [comment]
Thanks, that fixed my issue.
`    static function buildDynamicDataView($cdata) {
        $sql = 'CREATE VIEW `'.TABLE_PREFIX.'ticket__cdata`  
        AS ' . static::getCrossTabQuery('T', 'ticket_id');
        db_query($sql);
        
        /*
        $sql = 'CREATE TABLE IF NOT EXISTS `'.$cdata['table'].'` (PRIMARY KEY
                ('.$cdata['object_id'].')) DEFAULT CHARSET=utf8 AS '
             .  static::getCrossTabQuery( $cdata['object_type'], $cdata['object_id']);
        db_query($sql);
        */
    }`

**Comment by BartVB** [comment]
Ran into something similar when attempting to upgrade from 1.8 to 1.11-rc1:

`[CREATE TABLE `_unknown_inlines` AS SELECT A2.`attach_id` FROM `file` A1 JOIN `ticket_attachment` A2 ON (A1.id = A2.file_id) JOIN `ticket_thread` A3 ON (A3.ticket_id = A2.ticket_id) WHERE A1.`type` LIKE 'image/%' AND A2.inline = 0 AND A3.body LIKE CONCAT('%"cid:', A1.key, '"%')] CREATE TABLE ... SELECT is forbidden when @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1.`

**Comment by BartVB** [comment]
I managed to get through the upgrade process by changing the `CREATE TABLE .. AS SELECT` into `CREATE TABLE ... LIKE ...` and `INSERT INTO ... SELECT`.

Duplicates:
#4349 and #3776

Thanks for the suggestion, @slopokeit . This is by far the most elegant solution. It's pretty hard to solve this in an other way because you would first need to figure out the data structure of the SELECT statement if you want to first create the table and then INSERT the results.

Currently using:

includes/class.dynamic_forms.php:
```php
    static function buildDynamicDataView($cdata) {
        $sql = 'CREATE VIEW `'.$cdata['table'].'` 
             AS ' .  static::getCrossTabQuery( $cdata['object_type'], $cdata['object_id']);
        db_query($sql);
    }
```

**Comment by rebeluca** [comment]
Is there any news on this issue? It's impossibile to host OsTicket on services like Google Cloud using their MySQL.
