### ISSUE TITLE
Error when creating new agent.

### ISSUE THREAD

**Issue by soae786** [osTicket/osTicket#3604]
Hi,
I am getting below errror when I create a new agent.

[INSERT INTO `ost_team_member` SET `team_id` = '1', `flags` = 1] Duplicate entry '1-0' for key 'PRIMARY'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
 #1 (root)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)
 #2 (root)/include/class.orm.php(597): MySqlExecutor->execute()
 #3 (root)/include/class.staff.php(711): VerySimpleModel->save()
 #4 (root)/include/class.staff.php(1041): Staff->updateTeams(Array, Array)
 #5 (root)/scp/staff.php(47): Staff->update(Array, Array)
 #6 {main}

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.7 (Ubuntu)
MySQL Version	5.5.53
PHP Version	5.5.9-1ubuntu4.20

**Comment by fdellwing** [comment]
PK is `team_id` - `staff_id`

Looks like your staff_id is 0 here.

Can confirm a bug here:

Adding a new agent with a team will write 0 instead of the `staff_id` in `ost_team_member`.

You can workaround that if you add your agents to their teams after you created them.

**Comment by fdellwing** [comment]
Looked into it.

When creating a user the Staff->update($_POST,$errors) gets called. But the post-data doesnt have the staff_id yet.

Creating a new user:
![ost2](https://cloud.githubusercontent.com/assets/22813377/21768242/e686547a-d678-11e6-8988-fa3f7c92e4e0.png)
Updating a user:
![ost3](https://cloud.githubusercontent.com/assets/22813377/21768243/e68645a2-d678-11e6-938f-36187e2d5962.png)

**Comment by GoodbyeWorld** [comment]
This is affecting us too.

**Comment by edima08** [comment]
I am Having this same problem but like @fdellwing Said the best way around this is to Create the Agents first and then Add them to Teams later which doesn't take as much time

**Comment by dwcthompson** [comment]
Can confirm we are getting this issue on a new install of osTicket v1.10.1

**Comment by ntozier** [comment]
@dwcthompson @GoodbyeWorld What version of MySQL or MariaDB are you two using?

**Comment by dwcthompson** [comment]
My hosting provider is using MariaDB 10.1.31

**Comment by antiuser** [comment]
same issue on 1.12.2 osTicket
