### ISSUE TITLE
DB Error #1062 and Valid CSRF Token Required

### ISSUE THREAD

**Issue by mbnoimi** [osTicket/osTicket#3689]
Hi,

Whenever I try to login to control panel https://xxxx/tickets/scp/login.php I get this error message!
```
Valid CSRF Token Required
```
Then I receive this error message to my e-mail:
```
[INSERT INTO `ost_session` SET `session_id` = '717ll8at7jvse92gr2799tjtm3', `session_data` = 'csrf|a:2:{s:5:\"token\";s:40:\"51958825ec6104d77c0bd2a0895353aa213085e3\";s:4:\"time\";i:1487111519;}', `session_expire` = NOW() + INTERVAL 86400 SECOND, `user_ip` = '145.142.174.131', `user_agent` = 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0'] 

Duplicate entry '717ll8at7jvse92gr2799tjtm3' for key 'PRIMARY'<br /> <br />
 ---- Backtrace ----<br /> 
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br /> 
#1 (root)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br /> 
#2 (root)/include/class.orm.php(597): MySqlExecutor->execute()<br /> 
#3 (root)/include/class.ostsession.php(216): VerySimpleModel->save()<br /> 
#4 (root)/include/class.ostsession.php(158): DbSessionBackend->update('717ll8at7jvse92...', 'csrf|a:2:{s:5:"...')<br /> 
#5 [internal function]: SessionBackend->write('717ll8at7jvse92...', 'csrf|a:2:{s:5:"...')<br /> 
#6 [internal function]: session_write_close()<br /> #7 {main}
```

**Comment by mbnoimi** [comment]
A screenshot when my website was up :(

![e95e5eae_o](https://cloud.githubusercontent.com/assets/284547/22953048/271fb588-f318-11e6-96ba-2b9cde3a94e4.png)

**Comment by mbnoimi** [comment]
IMPORTANT: I suspect this issue occurs after upgrading from 1.9.12 to 1.10

**Comment by mbnoimi** [comment]
It seems this is a big bug in osTicket #3081

**Comment by ntozier** [comment]
This appears to be a duplicate of the issue report that you mentioned.  Please close this duplicate.
