### ISSUE TITLE
DB Error #1062 ; Attachments ; Duplicate entry 'xxx' for key 'file-type' 

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4250]
Hi there.

I'm receiving these kind of error from time to time.
Error says that when attachment is uploaded it is given ID that already exists in the database and thus cannot add the entry for new attachment.
This is v1.10.1

```
[INSERT INTO `ost2_attachment` SET `file_id` = 807, `type` = 'D', `object_id` = 6342]

Duplicate entry '6342-807-D' for key 'file-type'<br />
<br />
---- Wsteczne śledzenie ----<br />
#0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (główny katalog)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (główny katalog)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (główny katalog)/include/class.attachment.php(161): VerySimpleModel->save()<br />
#4 (główny katalog)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 (główny katalog)/include/ajax.draft.php(229): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 [internal function]: DraftAjaxAPI->uploadInlineImageClient('6342')<br />
#7 (główny katalog)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#8 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('6342/attach', Array)<br />
#9 (główny katalog)/include/class.dispatcher.php(120): Dispatcher->resolve('6342/attach', Array)<br />
#10 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/6342/att...', NULL)<br />
#11 (główny katalog)/ajax.php(50): Dispatcher->resolve('/draft/6342/att...')<br />
#12 {main}
```

---

System info screenshot: http://take.ms/9xRoe

**Comment by iHunt101** [comment]
It seems your attached files exceeds the limit of upload.
@JediKev  can you help us out?

**Comment by cYbercOsmOnauT** [comment]
This happens in our company if someone copy&pastes a picture into a mail.

**Comment by ntozier** [comment]
If its a file size exceeds limit, then you would want to up the limit in your php.ini [restart webserver] and then configure osTicket to have a large file size limit.  

That being said this report looks strangely like:
https://github.com/osTicket/osTicket/issues/3481

So what are you doing in the UI when the error occurs?

**Comment by JediKev** [comment]
@esamo @iHunt101 @cYbercOsmOnauT 

Here you guys go:
- https://github.com/osTicket/osTicket/pull/5149

Cheers.
