### ISSUE TITLE
DB Error #1064 ; Dashboard ; A1.`dept_id` IN ()

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4251]
Hi there.

I got 6 errors like this last night. Notice the part "A1.`dept_id` IN ()" which causes the SQL syntax error.
Somewhere a condition is missing to prevent such error.
I thought it's a cache restoration or something, as this is the first occurrence.
This happened when user opened the Dashboard. 

```
Formatted SQL

SELECT 
	A2.`id` AS `dept__id`, 
	AVG(
		DATEDIFF(A1.`closed`, A1.`created`)
	) AS `ServiceTime`, 
	AVG(
		DATEDIFF(A4.`created`, A5.`created`)
	) AS `ResponseTime` 
FROM 
	`ost2_ticket` A1 
	JOIN `ost2_department` A2 ON (A1.`dept_id` = A2.`id`) 
	LEFT JOIN `ost2_thread` A3 ON (
		A3.`object_type` = 'T' 
		AND A1.`ticket_id` = A3.`object_id`
	) 
	LEFT JOIN `ost2_thread_entry` A4 ON (
		A3.`id` = A4.`thread_id` 
		AND A4.`type` = 'R'
	) 
	LEFT JOIN `ost2_thread_entry` A5 ON (A4.`pid` = A5.`id`) 
WHERE 
	A1.`dept_id` IN () 
GROUP BY 
	A2.`id`
```
---
```
[SELECT A2.`id` AS `dept__id`, AVG(DATEDIFF(A1.`closed`, A1.`created`)) AS `ServiceTime`, AVG(DATEDIFF(A4.`created`, A5.`created`)) AS `ResponseTime` FROM `ost2_ticket` A1 JOIN `ost2_department` A2 ON (A1.`dept_id` = A2.`id`) LEFT JOIN `ost2_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost2_thread_entry` A4 ON (A3.`id` = A4.`thread_id` AND A4.`type` = 'R') LEFT JOIN `ost2_thread_entry` A5 ON (A4.`pid` = A5.`id`) WHERE A1.`dept_id` IN () GROUP BY A2.`id`]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY A2.`id`' at line 1<br />
<br />
---- Wsteczne śledzenie ----<br />
#0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1064', '[SELECT A2.`id`...')<br />
#1 (główny katalog)/include/class.orm.php(3133): db_query('SELECT A2.`id` ...', true, true)<br />
#2 (główny katalog)/include/class.orm.php(3180): MySqlExecutor->execute()<br />
#3 (główny katalog)/include/class.orm.php(1865): MySqlExecutor->getArray()<br />
#4 (główny katalog)/include/class.orm.php(1815): HashArrayIterator->{closure}()<br />
#5 (główny katalog)/include/class.orm.php(1794): CallbackSimpleIterator->next()<br />
#6 (główny katalog)/include/class.orm.php(1803): CallbackSimpleIterator->rewind()<br />
#7 (główny katalog)/include/class.orm.php(1463): CallbackSimpleIterator->valid()<br />
#8 (główny katalog)/include/class.orm.php(1480): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (główny katalog)/include/class.orm.php(1489): CachedResultSet->asArray()<br />
#10 (główny katalog)/include/class.report.php(234): CachedResultSet->getIterator()<br />
#11 (główny katalog)/include/staff/dashboard.inc.php(86): OverviewReport->getTabularData('dept')<br />
#12 (główny katalog)/scp/dashboard.php(50): require_once('/home/www/suppo...')<br />
#13 {main}
```

---

System info screenshot: http://take.ms/9xRoe

**Comment by esamo** [comment]
This may be issue of the hosting company, like the whole system is reverted to state from the past for some time.
