### ISSUE TITLE
tickets are being assigned ID 0

### ISSUE THREAD

**Issue by raramuridesign** [osTicket/osTicket#4310]
Hi
We have a strange issue after moving the site from one server to another.
We have the latest version.
Running on php 7.0.x

When the cron is running it fetches the mail.
Tickets are then created with ticket_id 0.
Although the previous ID was much higher.

The old server does not have ticket ticket_id 0, and I am not sure how this actually gets created.

has anyone encountered this before, as I have searched the forums but have not found anything which could help here.

Important, we migrated from one server to the other. There has been no other issues, apart from this.
Matthew

**Comment by raramuridesign** [comment]
We now get this when the cron runs
It's affecting the ticket table as well as the form_entry Table
---- 

[INSERT INTO `ost_form_entry` SET `form_id` = 2, `sort` = 0, `created` = NOW(), `extra` = '{\"disable\":[38]}', `object_type` = 'T', `updated` = NOW()]

Duplicate entry '0' for key 'PRIMARY'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (root)/include/class.dynamic_forms.php(1238): VerySimpleModel->save(true)<br />
#4 (root)/include/class.ticket.php(3387): DynamicFormEntry->save()<br />
#5 (root)/open.php(42): Ticket::create(Array, Array, 'Web')<br />
#6 {main}

**Comment by JediKev** [comment]
@raramuridesign 

osTicket does not FULLY support PHP 7+ just yet so I would suggest downgrading to PHP 5.6.x for now. We will address all PHP 7+ issues in the near future. Stay tuned!

Cheers.

**Comment by tgbles** [comment]
Hi. 
We have the exact same problem after moving to a red hat server using php 7.2
Have you found any solutions https://github.com/raramuridesign?

**Comment by tgbles** [comment]
> @raramuridesign
> 
> osTicket does not FULLY support PHP 7+ just yet so I would suggest downgrading to PHP 5.6.x for now. We will address all PHP 7+ issues in the near future. Stay tuned!
> 
> Cheers.

I downgraded to php 5.6 on my ubuntu pc but I got the same issue there as well.
I guess something went wrong when I imported or exported the data base. Everything looks fine, but when creating new tickets, they get assigned with 0 values on ticked_id and ip-adress, and can't be opened after created.

**Comment by JediKev** [comment]
@tgbles 

One way to test this would be to create a fresh new install and see if that functions properly. If so, you know the issue is with your database. If the issue is with your database then compare your old database's columns to the fresh install's database to see if all your tables and columns match up perfectly (including auto_increment settings, etc).

Cheers.
