### ISSUE TITLE
Problem showing queues after upgrade to v.1.11.rc1

### ISSUE THREAD

**Issue by tdnk** [osTicket/osTicket#4422]
After upgrade to v1.11-rc1 the queues is no longer shown.

Furthermore no ticket count numbers is shown in the menu - only a "-" is show to the right of all queues. The issues might be related.

If we go to queue setup and do a preview on the queue the tickets is shown correctly, but in the Agent Panel the queues does not show.

When an agent clicks on a queue the system log shows DB Error #1054

`[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) AND A2.`state` = 'open' AND NOT A1.`dept_id` IN (3, 4, 5, 6) AND A1.`created` IS NOT NULL AND NOT A1.`est_duedate` IS NOT NULL THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) AND A2.`state` = 'open' AND A1.`created` IS NOT NULL AND NOT A1.`est_duedate` IS NOT NULL AND A1.`dept_id` = 3 THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) AND A2.`state` = 'open' AND A1.`created` IS NOT NULL AND NOT A1.`est_duedate` IS NOT NULL AND A1.`dept_id` = 5 THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A1.`staff_id` = 2 THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`created` IS NOT NULL AND A1.`est_duedate` IS NOT NULL AND A1.`ticket_id` = Z1.`ticket_id` THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) AND A2.`state` = 'open' AND A1.`dept_id` = 6 AND A2.`name` = 'Open' THEN A1.`ticket_id` END) AS `q14`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) AND A2.`state` = 'open' AND A1.`dept_id` = 6 AND A2.`name` = 'Open' AND A2.`state` = 'open' AND A1.`dept_id` = 6 AND A2.`name` LIKE '%Awaiting%' THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) AND A2.`state` = 'open' AND A1.`dept_id` = 6 AND A2.`name` = 'Open' AND A1.`dept_id` = 6 AND A2.`state` = 'open' AND A2.`name` = 'Accepted' THEN A1.`ticket_id` END) AS `q16`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`dept_id` IN (3, 4, 5) THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (1) AND A2.`state` = 'open' AND NOT A1.`dept_id` IN (3, 4, 5, 6) THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q2` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (1) OR A6.`team_id` IN (1))) OR A1.`dept_id` IN (1, 2, 3, 4, 5, 6) OR A7.`id` IN (1, 2, 3, 4, 5, 6)] Unknown column 'Z1.ticket_id' in 'field list'

 ---- Backtrace ----
 #0 C:\Data\websites\ticket.timemap.dk\include\mysqli.php(199): osTicket->logDBError('DB Error #1054', '[SELECT COUNT(D...')
 #1 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(3404): db_query('SELECT COUNT(DI...', true, true)
 #2 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(3451): MySqlExecutor->execute()
 #3 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(2063): MySqlExecutor->getArray()
 #4 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(2013): HashArrayIterator->{closure}()
 #5 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(1992): CallbackSimpleIterator->next()
 #6 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(2001): CallbackSimpleIterator->rewind()
 #7 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(1673): CallbackSimpleIterator->valid()
 #8 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(1683): CachedResultSet->fillTo(2147483647)
 #9 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(1318): CachedResultSet->asArray()
 #10 C:\Data\websites\ticket.timemap.dk\include\class.orm.php(1341): QuerySet->all()
 #11 C:\Data\websites\ticket.timemap.dk\include\class.search.php(877): QuerySet->one()
 #12 C:\Data\websites\ticket.timemap.dk\include\ajax.search.php(398): SavedQueue::ticketsCount(Object(StaffSession), Array, 'q')
 #13 [internal function]: SearchAjaxAPI->collectQueueCounts()
 #14 C:\Data\websites\ticket.timemap.dk\include\class.dispatcher.php(145): call_user_func_array(Array, Array)
 #15 C:\Data\websites\ticket.timemap.dk\include\class.dispatcher.php(38): UrlMatcher->dispatch('counts', Array)
 #16 C:\Data\websites\ticket.timemap.dk\include\class.dispatcher.php(120): Dispatcher->resolve('counts', Array)
 #17 C:\Data\websites\ticket.timemap.dk\include\class.dispatcher.php(38): UrlMatcher->dispatch('/queue/counts', NULL)
 #18 C:\Data\websites\ticket.timemap.dk\scp\ajax.php(288): Dispatcher->resolve('/queue/counts')
 #19 {main}`

### Versions
OsTicket version: v1.11.0-rc1 (e321982)
MySql: 5.7.16
Php: 5.6.28
OS: Win2012 IIS

**Comment by tdnk** [comment]
Ok, found the reason to why the queue items isn't shown: 

When a queue is a sub-queue to another one the parent criterias is included in the queue even if the "Include parent search criteria" checkbox isn't checked.

If we move the queue to a toplevel queue the tickets is shown correctly.

Still empty count in menus and DB error

**Comment by JediKev** [comment]
@tdnk 

Do you have any saved searches? If so that is why, the Saved Searches aren't fixed yet and if you upgraded an had Saved Searches the counts will not work. Also if any of the queues have failed criteria (such as non-existent field, etc.) then it will also not show the counts.

Cheers.

**Comment by nathankitchen** [comment]
class.orm.php - I don't think annotations are being cleared correctly in compileCount: there looks like a typo where:

$q->related = $q->anotations = false;

Should be annotations (two n's). Might be screwing up count queries?

**Comment by mujizac** [comment]
I seem to also have this error and issue.
I attempted to change the code inside of class.search.php on line 392 to reflect A1. `ticket_id' rather than Z1.  
This actually fixed the reported issue, but it totally broke the search function!!
My platform and version is as follows:
osTicket Version | v1.11.0-rc1 (e321982)
Web Server Software | Apache/2.4.18 (Ubuntu)
MySQL Version | 5.7.25
PHP Version | 7.0.32-0ubuntu0.16.04.1

**Comment by JediKev** [comment]
@nathankitchen @mujizac 

Please retest using latest pull from `1.11.x` or `develop-next` branch. These branches contain the latest bugfixes for the 1.11.x series.

**P.S.**
The download on our site is an RC and is super old with many, many issues. This will be replaced once we release a new version (1.11 ST).

Cheers.

**Comment by mujizac** [comment]
Probably a little off topic, but:
where I am running the version off the website, rather than git version currently,
is it most advisable to do a git pull of the branch into a fresh folder, or is there a well crafted git command to pull and overwrite a non-git folder?
Please note that I'm doing this first on a development copy of our server.  I can totally take chances and make mistakes, I'm just curious about best course of action.

**Comment by JediKev** [comment]
@mujizac 

The best way would be to clone the repo to a directory on your server, `cd` into the clone directory, update the branches (`git fetch`/`git merge`), and run the following command to deploy the code:
```
$ php manage.php deploy /path/to/html/ -v
```

This command says "Deploy osTicket to `/path/to/html` and be -Verbose".

Cheers.
