### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4429]
anyone can help with this problem? i think in searching user is the error

[SELECT A1.`id`, A1.`name`, A5.`address` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) LEFT JOIN `ost_organization` A3 ON (A1.`org_id` = A3.`id`) LEFT JOIN `ost_user__cdata` A4 ON (A1.`id` = A4.`user_id`) LEFT JOIN `ost_user_email` A5 ON (A1.`default_email_id` = A5.`id`) WHERE (A2.`address` LIKE '%aag%' OR A1.`name` LIKE '%aag%' OR A3.`name` LIKE '%aag%' OR A4.`phone` LIKE '%aag%') LIMIT 25] Unknown column 'A4.phone' in 'where clause'

---- Backtrace ----
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1054', '[SELECT A1.`id`...')
#1 (root)/include/class.orm.php(3136): db_query('SELECT A1.`id`, ...', true, true)
#2 (root)/include/class.orm.php(3192): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(1845): MySqlExecutor->getRow()
#4 (root)/include/class.orm.php(1818): FlatArrayIterator->{closure}()
#5 (root)/include/class.orm.php(1797): CallbackSimpleIterator->next()
#6 (root)/include/class.orm.php(1806): CallbackSimpleIterator->rewind()
#7 (root)/include/class.orm.php(1463): CallbackSimpleIterator->valid()
#8 (root)/include/class.orm.php(1480): CachedResultSet->fillTo(9223372036854775807)
#9 (root)/include/class.orm.php(1489): CachedResultSet->asArray()
#10 (root)/include/ajax.users.php(94): CachedResultSet->getIterator()
#11 [internal function]: UsersAjaxAPI->search('local')
#12 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#13 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/local', Array)
#14 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('/local', Array)
#15 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users/local', NULL)
#16 (root)/scp/ajax.php(262): Dispatcher->resolve('/users/local')
#17 {main}

**Comment by ntozier** [comment]
Reported on the forums.  See:
http://osticket.com/forum/discussion/comment/124841/
