### ISSUE TITLE
1.11.0-RC1 DB Error 1064 When viewing Queues

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#4521]
osTicket Version | v1.11.0-rc1-243-g30ff399 (30ff399)
Web Server Software | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.38
MySQL Version | 10.2.17
PHP Version | 5.6.38

[SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A1.`dept_id` = 4 THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q14`, COUNT(DISTINCT CASE WHEN A1.`team_id` = 0 AND A1.`staff_id` = 0 AND NOT A1.`topic_id` = 14 THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A1.`dept_id` = 8 THEN A1.`ticket_id` END) AS `q16`, COUNT(DISTINCT CASE WHEN NOT A1.`dept_id` = 9 AND NOT A1.`topic_id` = 14 THEN A1.`ticket_id` END) AS `q18`, COUNT(DISTINCT CASE WHEN A1.`dept_id` = 9 THEN A1.`ticket_id` END) AS `q20`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND NOT (A1.`team_id` = 0 AND A1.`staff_id` = 0) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q4` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (4) OR A6.`team_id` IN (4))) OR A1.`dept_id` IN (1, 4, 6, 7, 8, 9, 10) OR A7.`id` IN (1, 4, 6, 7, 8, 9, 10)]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` ' at line 1<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3412): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3459): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2063): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2013): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(1992): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2001): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1673): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1683): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1318): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1341): QuerySet->all()<br />
#11 (root)/include/class.search.php(877): QuerySet->one()<br />
#12 (root)/include/ajax.search.php(398): SavedQueue::ticketsCount(Object(StaffSession), Array, 'q')<br />
#13 [internal function]: SearchAjaxAPI->collectQueueCounts()<br />
#14 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#15 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('counts', Array)<br />
#16 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('counts', Array)<br />
#17 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/queue/counts', NULL)<br />
#18 (root)/scp/ajax.php(288): Dispatcher->resolve('/queue/counts')<br />
#19 {main}

**Comment by JediKev** [comment]
@Taps7734 

We are working on some queue issues now and one of them is some custom fields will cause the queue's query to mess up which causes the count to crash. In the meantime, please retest using the latest from `develop-next`.

Cheers.

**Comment by ArthurBorsboom** [comment]
After upgrading osTicket from 1.10 to 1.11 (stable - release Feb 6, 2019), I encounter the same error.

This can be reproduced by:
- Login as an agent
- Mail with the SQL error arrives instantly.

I cannot reproduce it after the login (is the result cached?), except for logout and login again.
Below the trace from this system (I believe it is exactly the same).

Is there a workaround available?

```
[SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2, 3, 4, 9, 11, 12) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1, 2, 3, 4, 9, 11, 12) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-10 00:00:00' AND '2019-02-10 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2, 3, 4, 9, 11, 12) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1, 2, 3, 4, 9, 11, 12) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-09 00:00:00' AND '2019-02-09 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2, 3, 4, 9, 11, 12) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-04 00:00:00' AND '2019-02-10 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-01 00:00:00' AND '2019-02-28 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (1, 2, 3, 4, 9, 11, 12) OR A6.`team_id` IN (1, 2, 3, 4, 9, 11, 12))) OR A1.`dept_id` IN (1, 2) OR A7.`id` IN (1, 2)]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' ' at line 1<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (root)/include/class.search.php(922): QuerySet->one()<br />
#12 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)<br />
#13 (root)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))<br />
#14 (root)/scp/tickets.php(525): require_once('/home/support/p...')<br />
#15 (root)/scp/index.php(17): require('/home/support/p...')<br />
#16 {main}
```

**Comment by wouterVE** [comment]
I encounter the same error after upgrading from 1.10.5 -> 1.11.0

Initially, I received this error after the creation of a new ticket, now it comes up now and then.
Here is the backtrace:

```
[SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q16`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (5) AND A1.`dept_id` = 4 THEN A1.`ticket_id` END) AS `q17`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2) OR A1.`staff_id` IN (3)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1, 2) OR A1.`staff_id` IN (3)) AND A2.`state` = 'open' AND A1.`staff_id` IN (3) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-13 00:00:00' AND '2019-02-13 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2) OR A1.`staff_id` IN (3)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1, 2) OR A1.`staff_id` IN (3)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (3) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-12 00:00:00' AND '2019-02-12 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1, 2) OR A1.`staff_id` IN (3)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-11 00:00:00' AND '2019-02-17 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-01 00:00:00' AND '2019-02-28 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 3 OR A5.`staff_id` = 3 OR A1.`team_id` IN (1, 2) OR A6.`team_id` IN (1, 2))) OR A1.`dept_id` IN (4, 5) OR A7.`id` IN (4, 5)]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q16`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (5)' at line 1<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (root)/include/class.search.php(922): QuerySet->one()<br />
#12 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)<br />
#13 (root)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))<br />
#14 (root)/scp/tickets.php(525): require_once('/var/www/ostick...')<br />
#15 (root)/scp/index.php(17): require('/var/www/ostick...')<br />
#16 {main}
```

**Comment by sgaechter** [comment]
Me too:

A1.`staff_id` = 0 AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A1.`dept_id` IN (3, 1, 8) AND NOT A2.`state` IN ('closed', 'archived', 'deleted') THEN A1.`ticket_id` END) AS `q23`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN (NOW() - INTERVAL '0' DAY) AND NOW() THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A1.`isanswered` = '1' AND A8.`email` IS NOT NULL THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-12 00:00:00' AND '2019-02-12 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN (NOW() - INTERVAL '5' DAY) AND NOW() THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-01 00:00:00' AND '2019-02-28 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) LEFT JOIN `ost_staff` A8 ON (A1.`staff_id` = A8.`staff_id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (1) OR A6.`team_id` IN (1))) OR A1.`dept_id` IN (1, 3, 9, 4, 5, 7, 8) OR A7.`id` IN (1, 3, 9, 4, 5, 7, 8)]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id`' at line 1<br /> <br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (root)/include/class.search.php(922): QuerySet->one()<br />
#12 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)<br />
#13 (root)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))<br />
#14 (root)/scp/tickets.php(525): require_once('/home/gompot7/w...')<br />
#15 (root)/scp/index.php(17): require('/home/gompot7/w...')<br />
#16 {main}

*********************************************

Serverinformationen
--
osTicket-Version | v1.11 (d4e240b) —  Aktuell
Server-Software | Apache/2.4
MySQL-Version | 10.1.38
PHP-Version | 5.6.39

gdlib | Wird für die Bildmanipulation und PDF-Druck verwendet
imap | Wird für den E-Mail-Abruf verwendet
xml | XML API
xml-dom | Wird für die HTML E-Mail-Verarbeitung verwendet
json | Verbessert die Leistung beim Erzeugen und Verarbeiten von JSON
mbstring | Dringend empfohlen für nicht-westeuropäische Sprachinhalte
phar | Dringend empfohlen für Plug-ins und Sprachpakete
intl | Dringend empfohlen für nicht-westeuropäische Sprachinhalte
fileinfo | Wird verwendet, um Dateitypen für Uploads zu erkennen
APCu | Verbessert die Gesamtleistung
Zend Opcache | Verbessert die Gesamtleistung

cgi.fix_pathinfo | "1" wird empfohlen, wenn AJAX nicht funktioniert
date.timezone | Europe/Zurich

Schema | gompot7_osticket (gompot7.mysql.db.internal)
Schema-Signatur | 00c949a623b82848baaf3480b51307e3
Belegter Speicher gesamt | 37.69 MiB
Datenbankspeicher für Anhänge | 26.52 MiB
Timezone | CET (Interpreted as Europe/Berlin)

**Comment by JediKev** [comment]
Everyone,

To resolve this issue, delete all of your saved searches in the `ost_queue` table and recreate them.

Cheers.

**Comment by ArthurBorsboom** [comment]
Deleting the saved search solved the issue for me.
Thanks !

**Comment by wouterVE** [comment]
> Everyone,
> 
> To resolve this issue, delete all of your saved searches in the `ost_queue` table and recreate them.
> 
> Cheers.

I'm a bit confused. Where do I have to delete the saved searches? In mysql or osticket admin panel?

**Comment by ArthurBorsboom** [comment]
I deleted my saved search through the Web GUI / Agent panel.

Once you found the saved search, there will be a small 'wheel icon' to the right of the name of the saved search. Clicking this shows a drop down menu with the option [Delete] or [Remove].

Found it?

**Comment by wouterVE** [comment]
> I deleted my saved search through the Web GUI / Agent panel.
> 
> Once you found the saved search, there will be a small 'wheel icon' to the right of the name of the saved search. Clicking this shows a drop down menu with the option [Delete] or [Remove].
> 
> Found it?

Ok, it was a bit tricky, I was looking at the wrong place. I've deleted my personal queues. No errors thus far.
I've included a screenshot to make it eassier for others to find:
![2019-02-14_08h01_41](https://user-images.githubusercontent.com/29882487/52768848-dfa0d880-302e-11e9-9661-70dbbedddb0c.png)

Many thanks!

**Comment by Cm-8** [comment]
I have same problem after the upgrade from 1.10.4 to 1.11, **only one of the users was affected** by the problem "DB Error 1064" and it taked many time to understand it.

I resolve the problem as suggested: 

- **i've  deleted the searches of the user affected.**

Thanks to @JediKev, and to 
@wouterVE for screenshot




> **Server Informations:**
> osTicket version | v1.11 (d4e240b) —  Update
> Web Server Software | Apache
> MySQL | 5.6.35
> PHP | 5.6.40
