### ISSUE TITLE
DB Error #1064 after Migration from MySQl 5.5.60 to 8.0.13

### ISSUE THREAD

**Issue by guidokuehler** [osTicket/osTicket#4586]
Serverinformationen
--
osTicket-Version | v1.9.9-1-gbe2f138 (be2f138)
Server-Software | nginx/1.8.0
MySQL-Version | 8.0.13
PHP-Version | 5.6.4-4ubuntu6.4

-----------------------------------------

What we have made?

We have today migrate the osTicket Database from MySQL 5.5.60 to 8.0.13.

We have see no warnings or errors by the Migration but when we click on Agents and then on Teams the List is Emtpy and we receive the followed Error in the Systems Logs.

 DB Error #1064
[SELECT team.*, count(m.staff_id) as members, CONCAT_WS(" ", lead.firstname, lead.lastname) as team_lead FROM ost_osticket_team team LEFT JOIN ost_osticket_team_member m ON(m.team_id=team.team_id) LEFT JOIN ost_osticket_staff lead ON(lead.staff_id=team.lead_id) WHERE 1 GROUP BY team.team_id ORDER BY team.name ASC ] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lead ON(lead.staff_id=team.lead_id) WHERE 1 GROUP BY team.team_id ORDER BY team' at line 1

---- Ablaufverfolgung ----
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT team.*, ...')
#1 (root)/include/staff/teams.inc.php(35): db_query('SELECT team.*, c...')
#2 (root)/scp/teams.php(118): require('/var/www/it-pow...')
#3 {main}
----------------------------

This is the only one Error what we can see after the Migration.

Can us give any one a Tip to resolve this Problem?

Best Regards
Guido

**Comment by ntozier** [comment]
1.9.x is end of life and has been for some time.
Please upgrade to a newer version.

**Comment by guidokuehler** [comment]
Thank you for your Answer. 

Looks like a Autoanswer from an KI!? 

You mean that we can resolve our described Problem to 100% with an Update to osTicket v1.10.4. 

Is that right, have we understand right the deep backgroundinformation in your Answer? 

Best Regards 
Guido 








Von: "ntozier" <notifications@github.com> 
An: "osTicket/osTicket" <osTicket@noreply.github.com> 
CC: "guidokuehler" <guido.kuehler@it-power.biz>, "Author" <author@noreply.github.com> 
Gesendet: Dienstag, 30. Oktober 2018 20:50:20 
Betreff: Re: [osTicket/osTicket] DB Error #1064 after Migration from MySQl 5.5.60 to 8.0.13 (#4586) 



1.9.x is end of life and has been for some time. 
Please upgrade to a newer version.

**Comment by ntozier** [comment]
I have no idea what a "KI" is...

I'm saying that you cannot receive support for an ancient version that is no longer supported.  If you upgrade and retest and still have the same issue then we can troubleshoot it and attempt to fix the issue.

**Comment by nicoletta-maia** [comment]
Hello @guidokuehler ,
you probably don't need help anymore, anyway _lead_ is a [reserved word](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-L) in Mysql 8.0.13. You can rename it (or quote it with backtick) in _(root)/include/staff/teams.inc.php_
Cheers
