### ISSUE TITLE
Osticket Unable to create New Ticket. error http 500

### ISSUE THREAD

**Issue by kotharikrunal** [osTicket/osTicket#4626]
I am new to PHP and installed Osticket verison v1.10 (901e5ea). It was been working fine but suddenly was unable to create a new ticket and gives HTTP error 500 (Page time out)

Below is PHP Error log

[04-Dec-2018 07:04:48 UTC] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\wamp64\www\support\include\class.orm.php:1176
Stack trace:
#0 C:\wamp64\www\support\include\class.orm.php(545): QuerySet->one()
#1 C:\wamp64\www\support\include\class.thread.php(2537): VerySimpleModel::lookup(Array)
#2 C:\wamp64\www\support\include\class.orm.php(350): ObjectThread::lookup(Array)
#3 C:\wamp64\www\support\include\class.orm.php(386): VerySimpleModel->get('thread', NULL)
#4 C:\wamp64\www\support\include\class.ticket.php(823): VerySimpleModel->__get('thread')
#5 C:\wamp64\www\support\include\class.ticket.php(2593): Ticket->getThread()
#6 C:\wamp64\www\support\include\class.ticket.php(3400): Ticket->logEvent('created', NULL, Object(StaffSession))
#7 C:\wamp64\www\support\include\class.ticket.php(3566): Ticket::create(Array, Array, 'staff', false)
#8 C:\wamp64\www\support\scp\tickets.php(328): Ticket::open(Array, Array)
 in C:\wamp64\www\support\include\class.orm.php on line 1176

04-Dec-2018 08:04:06 UTC] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\wamp64\www\support\include\class.orm.php:1176
Stack trace:
#0 C:\wamp64\www\support\include\class.orm.php(545): QuerySet->one()
#1 C:\wamp64\www\support\include\class.thread.php(2537): VerySimpleModel::lookup(Array)
#2 C:\wamp64\www\support\include\class.orm.php(350): ObjectThread::lookup(Array)
#3 C:\wamp64\www\support\include\class.orm.php(386): VerySimpleModel->get('thread', NULL)
#4 C:\wamp64\www\support\include\class.ticket.php(823): VerySimpleModel->__get('thread')
#5 C:\wamp64\www\support\include\class.ticket.php(2593): Ticket->getThread()
#6 C:\wamp64\www\support\include\class.ticket.php(3400): Ticket->logEvent('created', NULL, Object(StaffSession))
#7 C:\wamp64\www\support\include\class.ticket.php(3566): Ticket::create(Array, Array, 'staff', false)
#8 C:\wamp64\www\support\scp\tickets.php(328): Ticket::open(Array, Array)
 in C:\wamp64\www\support\include\class.orm.php on line 1176

Regards,
Krunal

**Comment by ntozier** [comment]
@JediKev can probably tell you where, but I can tell you that the system is trying to pull a piece of information which only one should exist, and more than one (2) were found, and it doesn't know what to do.  It could be statuses, lists, filters, etc.

Please check the following tables for dupes: ost_ticket_status, ost_list, ost_filter, ost_filter_action, ost_filter_rule

**Comment by JediKev** [comment]
Looks like a dupe thread. Look at ost_thread table for duplicate IDs and such.

**Comment by PeopleInside** [comment]
I had the same issue today.

**Comment by simocheccoli** [comment]
Deleting duplicate rows is not a solution about an apparent bug, it's just an update that an expert user must make by hand.
**How do you plan to solve this problem?**

**Comment by JediKev** [comment]
@simocheccoli 

My thinking is when you deleted a ticket in the past it didn't delete the Thread record (for some reason) and now InnoDB is reusing an old ticket id which matched the `object_id` from the old Thread record and now it's pulling two Thread results when it's expecting one result.

**Detailed Explanation:**
It appears the system reused an old `object_id` (ticket id) and since this new ticket's `id` matched an old one it pulled all threads matching the `object_id` (which pulled two results when it's expecting only one result). This can happen with InnoDB tables (which the majority of our tables are). When you restart the database for any reason, InnoDB tables reset the `auto_increment` to the next available value which can cause the reuse of old, deleted values. Whereas MyISAM tables cache the old `auto_increment` value and starts right where it left off. With this being said, this has been changed in MySQL 8.0 so with 8.0+ InnoDB tables will cache the `auto_increment` value and pick up where it left off even after restarting.

So, I don't _think_ that there is much we can do code-wise, mostly database-wise. I will discuss this with the team and get back to you.

Cheers.

**Comment by simocheccoli** [comment]
OK.

Maybe there may be a couple of solutions anyway.

- A logical delete, even if it is not clean as a solution, would not bring up this problem.
- The cascade on delete should work (?).
- Change all keys via UUID instead auto_increment strategy?

**Comment by simocheccoli** [comment]
Hope this can helps:
If i open a new ticket via agent panel, all works.
If a ticket is opened via email, threads are not showing

**Comment by simocheccoli** [comment]
@JediKev found:
`ost_thread_entry_email` there are some duplicated entry for this query
```sql
SELECT count(*) #A1.`id`, A1.`pid`, A1.`thread_id`, A1.`staff_id`, A1.`user_id`,
FROM `ost_thread_entry` A1 
LEFT JOIN `ost_staff` A2 ON (A1.`staff_id` = A2.`staff_id`) 
LEFT JOIN `ost_user` A3 ON (A1.`user_id` = A3.`id`) 
LEFT JOIN `ost_thread_entry_email` A4 ON (A1.`id` = A4.`thread_entry_id`) 
WHERE A1.`id` = <ID> ORDER BY A1.`created` ASC, A1.`id` ASC
```

**Comment by JediKev** [comment]
@simocheccoli 

Did someone truncate the `ost_ticket` table thinking it would delete all related records as well?

Cheers.

**Comment by simocheccoli** [comment]
@JediKev No, they have just delete some tickets, via agent panel..
