### ISSUE TITLE
Removing Organization will result in error

### ISSUE THREAD

**Issue by clandmeter** [osTicket/osTicket#4628]
Im running an up to date 1.11.x branch (31c129a2667d3dc6e4bb74254b9686b66594c51d) on PHP 7.0.
When removing an organization the below error will be thrown.

Removing the users cookie will make osTicket work again.

```
[Fri Dec  7 07:43:37 2018] PHP Fatal error:  Uncaught DoesNotExist in /usr/share/webapps/osTicket/include/class.orm.php:1353
Stack trace:
#0 /usr/share/webapps/osTicket/include/class.orm.php(721): QuerySet->one()
#1 /usr/share/webapps/osTicket/include/class.orm.php(338): VerySimpleModel->refetch()
#2 [internal function]: VerySimpleModel->__wakeup()
#3 /usr/share/webapps/osTicket/include/class.ostsession.php(86): session_start()
#4 /usr/share/webapps/osTicket/include/class.ostsession.php(130): osTicketSession->__construct(86400)
#5 /usr/share/webapps/osTicket/include/class.osticket.php(60): osTicketSession::start(86400)
#6 /usr/share/webapps/osTicket/include/class.osticket.php(628): osTicket->__construct()
#7 /usr/share/webapps/osTicket/main.inc.php(33): osTicket::start()
#8 /usr/share/webapps/osTicket/client.inc.php(21): require_once('/usr/share/weba...')
#9 /usr/share/webapps/osTicket/index.php(16): require('/usr/share/weba...')
#10 {main}
  thrown in /usr/share/webapps/osTicket/include/class.orm.php on line 1353
[Fri Dec  7 07:43:37 2018] 0.0.0.0:34245 [500]: / - Uncaught DoesNotExist in /usr/share/webapps/osTicket/include/class.orm.php:1353
Stack trace:
#0 /usr/share/webapps/osTicket/include/class.orm.php(721): QuerySet->one()
#1 /usr/share/webapps/osTicket/include/class.orm.php(338): VerySimpleModel->refetch()
#2 [internal function]: VerySimpleModel->__wakeup()
#3 /usr/share/webapps/osTicket/include/class.ostsession.php(86): session_start()
#4 /usr/share/webapps/osTicket/include/class.ostsession.php(130): osTicketSession->__construct(86400)
#5 /usr/share/webapps/osTicket/include/class.osticket.php(60): osTicketSession::start(86400)
#6 /usr/share/webapps/osTicket/include/class.osticket.php(628): osTicket->__construct()
#7 /usr/share/webapps/osTicket/main.inc.php(33): osTicket::start()
#8 /usr/share/webapps/osTicket/client.inc.php(21): require_once('/usr/share/weba...')
#9 /usr/share/webapps/osTicket/index.php(16): require('/usr/share/weba...')
#10 {main}
  thrown in /usr/share/webapps/osTicket/include/class.orm.php on line 1353
```

**Comment by cotus78** [comment]
Hi , I confirm the issue.
I took me an hour trying to understand what could be the cause until I found @clandmeter suggestion about cookies

**Comment by JediKev** [comment]
@clandmeter @cotus78 

Here y'all go:
#4740

Cheers.

**Comment by cotus78** [comment]
Tested right now and it looks fixed .
Thanks @JediKev
