### ISSUE TITLE
Password Reset - v1.11.0-rc1 

### ISSUE THREAD

**Issue by husseinsheikh** [osTicket/osTicket#4636]
I am using v1.11.0-rc1 and when i reset the password, it shows the blank white page on the next page and doesn't get any emails.

The PHP log give this error as below 

```
PHP Fatal error:  Uncaught Error: Cannot use object of type EmailAddress as array in C:\inetpub\website\support\include\pear\Mail\mimePart.php:968
Stack trace:
#0 C:\inetpub\website\support\include\pear\Mail\mimePart.php(857): Mail_mimePart::explodeQuotedString('[\t,]', Object(EmailAddress))
#1 C:\inetpub\website\support\include\pear\Mail\mime.php(1351): Mail_mimePart::encodeHeader('to', Object(EmailAddress), 'utf-8', 'quoted-printabl...', '\n')
#2 C:\inetpub\website\support\include\pear\Mail\mime.php(1327): Mail_mime->encodeHeader('To', Object(EmailAddress), 'utf-8', 'quoted-printabl...')
#3 C:\inetpub\website\support\include\pear\Mail\mime.php(1114): Mail_mime->encodeHeaders(Array)
#4 C:\inetpub\website\support\include\class.mailer.php(543): Mail_mime->headers(Array, true)
#5 C:\inetpub\website\support\include\class.email.php(180): Mailer->send(Array, 'Vodanile Suppor...', '<h3><strong>Hi ...', Array, Array)
#6 C:\inetpub\website\support\include\class.user.php(1 in C:\inetpub\website\support\include\pear\Mail\mimePart.php on line 968
```

**Comment by JediKev** [comment]
@husseinsheikh 

You need to use the latest pull from `1.11.x` or `develop-next`, apply pull #4344, and then retest.

Cheers.

**Comment by husseinsheikh** [comment]
> @husseinsheikh
> 
> You need to use the latest pull from `1.11.x` or `develop-next`, apply pull #4344, and then retest.
> 
> Cheers.

How do i download these files from a direct link as it is confusing?

**Comment by JediKev** [comment]
@husseinsheikh

Choose the branch from the branch drop down then click the big green button that says Clone or Download.

Cheers.

**Comment by husseinsheikh** [comment]
> @husseinsheikh
> 
> Choose the branch from the branch drop down then click the big green button that says Clone or Download.
> 
> Cheers.

after downloading the pull i am getting below errors on the main page 
```

Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\inetpub\website\support\include\class.forms.php on line 5024

Warning: Declaration of ReferralForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\inetpub\website\support\include\class.forms.php on line 5317

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\inetpub\website\support\include\class.forms.php on line 5409

Warning: Declaration of RoleQuickAddForm::getClean() should be compatible with Form::getClean($validate = true) in C:\inetpub\website\support\include\class.role.php on line 350

Warning: Declaration of QueueColumnListBroker::update($columns, &$errors, $options = Array) should be compatible with InstrumentedList::update(array $what) in C:\inetpub\website\support\include\class.queue.php on line 2706

Warning: Declaration of SavedQueue::getHierarchicalQueues(Staff $staff) should be compatible with CustomQueue::getHierarchicalQueues(Staff $staff, $pid = 0, $primary = true) in C:\inetpub\website\support\include\class.search.php on line 650

Warning: Declaration of AdhocSearch::checkAccess($staff) should be compatible with CustomQueue::checkAccess(Staff $agent) in C:\inetpub\website\support\include\class.search.php on line 1007

Warning: Declaration of DepartmentQuickAddForm::getClean() should be compatible with Form::getClean($validate = true) in C:\inetpub\website\support\include\class.dept.php on line 977

Warning: Declaration of TeamSelectionField::getSortKeys() should be compatible with FormField::getSortKeys($path) in C:\inetpub\website\support\include\class.search.php on line 1412

Warning: Declaration of ResetAgentPermissionsForm::getClean() should be compatible with Form::getClean($validate = true) in C:\inetpub\website\support\include\class.staff.php on line 1402

Warning: Declaration of ChangeDepartmentForm::getClean() should be compatible with Form::getClean($validate = true) in C:\inetpub\website\support\include\class.staff.php on line 1453

Warning: Declaration of StaffQuickAddForm::getClean() should be compatible with Form::getClean($validate = true) in C:\inetpub\website\support\include\class.staff.php on line 1563
```

**Comment by JediKev** [comment]
@husseinsheikh 

Apply #4344 for PHP 7-7.1 support.

Cheers.

**Comment by ntozier** [comment]
Easiest way:
Restore the DB from back up.
Restore the site from back up.

**Comment by husseinsheikh** [comment]
@JediKev @ntozier I have restored it and noticed a new issue when the client is trying to view the history online by clicking the link in the first email - they get this Account confirmation required error and when enter the email with ticket number they get green message that email sent which never comes to inbox. after few tries You've reached maximum failed login attempts allowed.

**Comment by JediKev** [comment]
@husseinsheikh 

You restored from backup, so what your current version? Post a screenshot of **Admin Panel > Dashboard > Information**. Also, what codebase are you using? Downloaded from the osticket.com site or from github?

Cheers.

**Comment by JediKev** [comment]
@husseinsheikh 

So you're using the files from the osticket site which is out of date (we're pushing updates to the site soon). In the meantime, you should be using the files from `1.11.x` or `develop-next` branch. On top of that, if you want to use PHP 7 or 7.1 you'll _have_ to apply the changes from #4344. You'll still get a few warnings (for now until we finalize the PHP 7.1 support pull) but nothing should be "fatal".

If you cannot or do not want to apply the changes from #4344 then you'll have to downgrade to PHP 5.6 until we release `1.11-rc2`.

Cheers.

**Comment by husseinsheikh** [comment]
@JediKev I tried to use the `1.11.x` or `develop-next` branch which gave some PHP warnings on the support landing page but didn't know how to get the files of  #4344 - Are you able to send me a direct link from where to download the files? When will be the next release `1.11-rc2` with all these fixes?

**Comment by JediKev** [comment]
@husseinsheikh

@ntozier left you a really good message on the pull request you commented on explaining how to apply the changes. Take a look at that message.

As for the pull request making it into 1.11-rc2, yes I _believe_ they will be merged by then (not 100% sure) and we do not set release dates for anything osTicket.

Cheers.

**Comment by vollkommenIrrelevant** [comment]
@JediKev 
I'm think the most don't want to use the own-merged versions. Maybe you can release a new release-candidate next time? Only to be shure to get an official state.
