### ISSUE TITLE
Cannot view Closed ticket

### ISSUE THREAD

**Issue by Cronus89** [osTicket/osTicket#4662]
I can't find anything duplicate in tables.
I also cannot view the list of ticket statuses in admin panel. Table is below

ost_ticket_status
---
| id | name | state | mode | flags | sort | properties | created | updated | 
| ---: | --- | --- | ---: | ---: | ---: | --- | --- | --- | 
| 1 | Open | open | 3 | 0 | 1 | {"description":"Open tickets."} | 2014-12-05 09:28:42 | 0000-00-00 00:00:00 | 
| 2 | Resolved | closed | 1 | 0 | 2 | {"allowreopen":true,"reopenstatus":0,"allowreopen":true,"reopenstatus":0,"description":"Resolved tickets"} | 2014-12-05 09:28:42 | 0000-00-00 00:00:00 | 
| 3 | Closed | closed | 3 | 0 | 3 | {"allowreopen":true,"reopenstatus":0,"allowreopen":true,"reopenstatus":0,"description":"Closed tickets. Tickets will still be accessible on client and staff panels."} | 2014-12-05 09:28:42 | 0000-00-00 00:00:00 | 
| 4 | Archived | archived | 3 | 0 | 4 | {"description":"Tickets only adminstratively available but no longer accessible on ticket queues and client panel."} | 2014-12-05 09:28:42 | 0000-00-00 00:00:00 | 
| 5 | Deleted | deleted | 3 | 0 | 5 | {"description":"Tickets queued for deletion. Not accessible on ticket queues."} | 2014-12-05 09:28:42 | 0000-00-00 00:00:00 | 

> Fatal
 error: Uncaught ObjectNotUnique: One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects. in /home/web/htdocs/support.tobaccosuper.com/public/include/class.orm.php:1176 Stack trace: #0 /home/web/htdocs/support.tobaccosuper.com/public/include/class.orm.php(545): QuerySet->one() #1 /home/web/htdocs/support.tobaccosuper.com/public/include/class.list.php(297): VerySimpleModel::lookup(Array) #2 /home/web/htdocs/support.tobaccosuper.com/public/include/class.list.php(384): DynamicList->getConfigurationForm(true) #3 /home/web/htdocs/support.tobaccosuper.com/public/include/class.list.php(112): DynamicList->getForm() #4 /home/web/htdocs/support.tobaccosuper.com/public/include/class.list.php(1327): CustomListHandler->__call('getForm', Array) #5 /home/web/htdocs/support.tobaccosuper.com/public/include/class.list.php(1143): TicketStatus->getConfiguration() #6 /home/web/htdocs/support.tobaccosuper.com/public/include/class.ticket.php(300): TicketStatus->isReopenabl in /home/web/htdocs/support.tobaccosuper.com/public/include/class.orm.php on line 1176

**Comment by ntozier** [comment]
So knowing what you are doing when the error occurs would be helpful;

Please check your forms for dupes (at the database level. ost_forms iirc)

Also check Admin panel -> Manage -> Lists. Are there two "Ticket Statuses" there?

**Comment by Cronus89** [comment]
I go to Closed tickets, click any one to view the details of it (responses etc)  its blank, when i enable php errors I get the uncaught objectnotunique error above.

There are no duplicates in forms, There are not two ticket statuses, (i saw that bug report and checked that)

**Comment by Cronus89** [comment]
ost_form
---
| id | pid | type | flags | title | instructions | name | notes | created | updated | 
| ---: | ---: | --- | ---: | --- | --- | --- | --- | --- | --- | 
| 1 |  | U | 0 | Contact Information |  |  |  | 2013-12-10 16:03:16 | 2013-12-10 16:03:16 | 
| 2 |  | T | 0 | Ticket Details | Please Describe Your Issue |  | This form will be attached to every ticket, regardless of its source. You can add any fields to this form and they will be available to all tickets, and will be searchable with advanced search and filterable. | 2013-12-10 16:03:16 | 2014-01-06 14:38:09 | 
| 3 |  | C | 0 | Company Information | Details available in email templates |  |  | 2013-12-10 16:03:16 | 2013-12-10 16:03:16 | 
| 4 |  | O | 0 | Organization Information | Details on user organization |  |  | 2014-07-03 09:12:00 | 2014-07-03 09:12:00 | 
| 5 |  | L2 | 1 | StoreName Properties |  |  |  | 2014-08-13 14:57:17 | 2014-08-13 14:57:17 | 
| 6 |  | L2 | 1 | Ticket Status Properties | Properties that can be set on a ticket status. |  |  | 2014-12-05 09:28:42 | 2014-12-05 09:28:42 | 
| 7 |  | L1 | 1 | Store # List Properties |  |  |  | 2014-12-05 09:28:45 | 2014-12-05 09:28:45 | 
| 8 |  | A | 0 | Task Details | Please Describe The Issue |  | This form is used to create a task. | 2017-02-09 14:20:35 | 2017-02-09 14:20:35 |

**Comment by Cronus89** [comment]
I never got this resolved, anyone have an idea what it could be?

**Comment by JediKev** [comment]
@Cronus89 

The issue is that you have one List associated with two different Properties Forms. We've recently noticed this issue as well and are looking into the root cause.

For now, you will need to do a little investigating to see which Form you actually use for the List Properties.
1. Go to the `ost_form_field` table and find the records where `form_id IN(5,6)`.
2. Look at the Form Fields for each respective Form and determine which ones you are _not_ using for the List Properties.
3. Once you determine which Form Fields you are _not_ using you can go to the `ost_form` table, take a backup (just in case), and delete the record with the `id` matching the `form_id` from the Fields you are not using.

This should clear the error and let you view the tickets again. Like I said above, we are looking into the root cause of this issue.

Cheers.

**Comment by Cronus89** [comment]
That worked. Store Name Properties (id 5) was not in use!
