### ISSUE TITLE
Multilanguage fields can't be saved - stuck on ajax 'Loading' on Save

### ISSUE THREAD

**Issue by pitzyn** [osTicket/osTicket#4716]
This is same for OST 1.10.x-1.11, PHP5.6/7.0/7.2, checked on two different hosting accounts

On Admin panel a few form fields are multilanguage and could be translated for each installed language.
Some of those forms can't be saved (regardles if any change has been done to its content nor default values been left unchanged).
The modal/Ajax message window is without css styling and it hungs forever on rotating gif and saying 'LOADING' 

It doesn't matter if only one/original language pack is installed or if additional packs are added.

This issue applies i.e. to tickets statuses (scp/lists.php?type=ticket-status) when you try to change its name, description or whatever value and then to save the form.
Same bug also applies to a few other places on admin/agent panel.

![2019-02-10](https://user-images.githubusercontent.com/47509322/52541264-4904bb00-2d93-11e9-985e-72747fcc4c1c.png)

Strange but for some places i.e. /scp/lists.php?type=ticket-status#properties tab to change & save its multilanguage content works fine.

**Comment by ntozier** [comment]
I am unable to replicate this on my production sites.

What webserver are you running?
PHP errors?
console errors?

**Comment by pitzyn** [comment]
How strange. I use Debian9/Apache2/PHP7.1 or PHP5.6/MariaDB.
I installed v1.10 and 1.11 and have the same issue with this multilanguage form fields - BUT with this particular one only. 
Any other multilang forms with editing & saving works normally.


I have found random osTicket demo installation, i.e. here (it is not related/hosted to me nor my system):
https://www.opensourcecms.com/osticket/

Please check this bug on their demo page. It does the same on editing ticket statuses /scp/lists.php?type=ticket-status

Admin Page: https://s1.demo.opensourcecms.com/osticket/scp/login.php
Username: opensourcecms
Password: opensourcecms

**Comment by JediKev** [comment]
@pitzyn 

I still cannot reproduce this error with the latest codebase and translations installed/enabled. I'm able to change, update, and save any Ticket Status.

Cheers.

**Comment by InToSSH** [comment]
I have exactly the same problem with my osTicket installation. Installed it yesterday from master. 
OS: Ubuntu 18.04 Server, PHP 7.1 (mostly stock config), MySQL 5.7.25. 
And same error: `VM1135:1 POST http://fqdn/scp/ajax.php/list/1/item/6/update 500 (Internal Server Error)`

**Comment by JediKev** [comment]
@InToSSH 

That "error" isn't really helpful unfortunately. Is your AJAX working correctly? Can you hover tooltips and see the actual content?

Cheers.

**Comment by InToSSH** [comment]
@JediKev yes, everything else is working fine. I usually develop webapps with Ajax and never had a problem with that. Unfortunatelly in the DevConsole there is no other output, however I can try to dig into the server, turn on as much debug as possible on PHP and see if I can find more stuff

**Comment by JediKev** [comment]
@InToSSH

That would be ideal as like I said I cannot reproduce this with both of my installs which are configured very differently from each other.

Cheers.

**Comment by InToSSH** [comment]
@JediKev 
Alrighty, this is what I found:

```
[21-Feb-2019 23:25:47 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function TicketStatus::update(), 1 passed in /var/www/hosts/osticket/include/ajax.forms.php on line 181 and exactly 2 expected in /var/www/hosts/osticket/include/class.list.php:1435
Stack trace:
#0 /var/www/hosts/osticket/include/ajax.forms.php(181): TicketStatus->update(Array)
#1 /var/www/hosts/osticket/include/class.dispatcher.php(145): DynamicFormsAjaxAPI->saveListItem('1', '6')
#2 /var/www/hosts/osticket/include/class.dispatcher.php(38): UrlMatcher->dispatch('1/item/6/update', Array)
#3 /var/www/hosts/osticket/include/class.dispatcher.php(120): Dispatcher->resolve('1/item/6/update', Array)
#4 /var/www/hosts/osticket/include/class.dispatcher.php(38): UrlMatcher->dispatch('/list/1/item/6/...', NULL)
#5 /var/www/hosts/osticket/scp/ajax.php(289): Dispatcher->resolve('/list/1/item/6/...')
#6 {main}
  thrown in /var/www/hosts/osticket/include/class.list.php on line 1435

```

Thanks for looking at this :)

**Comment by pitzyn** [comment]
I have this problem on PHP7.1/7.2 too

**Comment by JediKev** [comment]
@pitzyn @InToSSH 

Here you go:
#4758

Cheers.

**Comment by InToSSH** [comment]
@JediKev Thanks for fixing this issue. It's alright now 👍
