### ISSUE TITLE
Error Column title translated from task__cdata 

### ISSUE THREAD

**Issue by fernandogf** [osTicket/osTicket#4783]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

As i create a task, the column name 'title' on 'ost_task__cdata' change to 'titulo' (word translated)
So this makes some errors:
 - OsTicket Alert with the unkown 'titulo' in the bd (PHP error)->
```
[SELECT A1.`id` AS `id`, A1.`number` AS `number`, A1.`created` AS `created`, A1.`staff_id` AS `staff_id`, A1.`team_id` AS `team_id`, A4.`firstname` AS `staff__firstname`, A4.`lastname` AS `staff__lastname`, A5.`name` AS `team__name`, A6.`name` AS `dept__name`, A7.`title` AS `cdata__title`, A1.`flags` AS `flags`, COUNT(DISTINCT B0.`thread_id`) AS `collab_count`, COUNT(DISTINCT CASE WHEN B2.`inline` THEN NULL ELSE B2.`object_id` END) AS `attachment_count`, COUNT(DISTINCT CASE WHEN B1.`flags` & 4 != 0 THEN NULL ELSE B1.`id` END) AS `thread_count` FROM `ost_task` A1 LEFT JOIN `ost_ticket` A2 ON (A1.`object_id` = A2.`ticket_id`) LEFT JOIN `ost_ticket_status` A3 ON (A2.`status_id` = A3.`id`) LEFT JOIN `ost_staff` A4 ON (A1.`staff_id` = A4.`staff_id`) LEFT JOIN `ost_team` A5 ON (A1.`team_id` = A5.`team_id`) JOIN `ost_department` A6 ON (A1.`dept_id` = A6.`id`) JOIN `ost_task__cdata` A7 ON (A1.`id` = A7.`task_id`) JOIN `ost_thread` A8 ON (A1.`id` = A8.`object_id` AND A8.`object_type` = 'A') LEFT JOIN `ost_thread_collaborator` B0 ON (A8.`id` = B0.`thread_id`) LEFT JOIN `ost_thread_entry` B1 ON (A8.`id` = B1.`thread_id`) LEFT JOIN `ost_attachment` B2 ON (B2.`type` = 'H' AND B1.`id` = B2.`object_id`) WHERE A1.`flags` & 1 != 0 AND ((A1.`flags` & 1 != 0 AND A1.`staff_id` = 1) OR (A2.`staff_id` = 1 AND A3.`state` = 'open') OR A1.`dept_id` IN (4) OR (A1.`team_id` IN (4) AND A1.`flags` & 1 != 0)) GROUP BY A1.id ORDER BY A1.`created` DESC LIMIT 1]

Unknown column 'A7.title' in 'field list'<br /> <br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054', '[SELECT A1.`id`...')<br />
#1 (raíz)/include/class.orm.php(3454): db_query('SELECT A1.`id` ...', true, true)<br />
#2 (raíz)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (raíz)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (raíz)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (raíz)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (raíz)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (raíz)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (raíz)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (raíz)/include/class.orm.php(1721): CachedResultSet->asArray()<br />
#10 (raíz)/include/staff/tasks.inc.php(363): CachedResultSet->getIterator()<br />
#11 (raíz)/scp/tasks.php(257): require_once('/var/www/vhosts...')<br />
#12 {main}

```
- Can't see the task on my view of Open Tasks (also send me another error Alert)
![](https://i.imgur.com/C61iqHg.png)
![](https://i.imgur.com/rvsv2Xm.png)

### Tests
I try to delete all the task (removed data task__cdata and task) and change the title name to 'title', but after create another task, the column is rewrited and the whole data appears again.

### Versions

![](https://i.imgur.com/x0tEtgv.png)

Hope can help me.

Thanks.

**Comment by fernandogf** [comment]
Found error ->
In Admin Panel -> Manage -> Forms -> Task Details 
The variable name of "title" have been changed to "titulo"
Maybe because of the translation, but dunno how.
However... changed into DB manually -> ost_form_field 
Delete whole ost_task__cdata and changed column 'titulo' to 'title'

Now after create a new task, it appears correctly and works fine.
