### ISSUE TITLE
DB Error 1064 after updating to 1.11

### ISSUE THREAD

**Issue by phatair** [osTicket/osTicket#4795]
We updated our osTicket from 1.10 to 1.11 and now we are getting these Errors:

`[SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (4) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-14 00:00:00' AND '2019-03-14 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (4) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-13 00:00:00' AND '2019-03-13 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-11 00:00:00' AND '2019-03-17 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (4) OR A6.`team_id` IN (4))) OR A1.`dept_id` IN (1) OR A7.`id` IN (1)]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' ' at line 1<br /> <br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (root)/include/class.search.php(922): QuerySet->one()<br />
#12 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)<br />
#13 (root)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))<br />
#14 (root)/scp/tickets.php(525): require_once('/var/www/html/s...')<br />
#15 {main}
`

It looks like this error is generated if we click on the "Tickets" menu but i can not replicate this error and i'm not sure about this. This error occurs 14 times since the update yesterday.
There is no problems i can see, it looks like that everything is working fine but i would like to solve this error.

Our osTicket informations are attached as screenshot.
![osTicket_infos](https://user-images.githubusercontent.com/28873754/54357864-48e02f80-465f-11e9-8b39-1f8bedefd192.png)

**Comment by phatair** [comment]
Maybe thats the problem?
We have two custom list items for the ticket status.
![image](https://user-images.githubusercontent.com/28873754/54369694-a6cc4180-4676-11e9-85e0-81ec613d6af4.png)


This two values are also displayed in the ost_queue table

![image](https://user-images.githubusercontent.com/28873754/54369678-9ddb7000-4676-11e9-8ef8-966258bbb711.png)

Should i delete these custom ticket status values and create new entrys?

**Comment by JediKev** [comment]
@phatair 

Nah, just change the first highlighted record (in your screenshot) called `Open`'s `config` column data to `{"criteria":[["status__state","includes",{"open":"Open"}]]}` and just delete the second record called `Wartend` altogether.

Cheers.

**Comment by phatair** [comment]
Hi JediKey,
i followed you instructions but after that change all closed tickets are shown in the "open tickets" view on the dashboard. If i looked into the ticket, that status was set on closed but the ticket was shown in the open ticket view.

And i got the DB Error again.

```
[SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND (A1.`team_id` IN (4) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND A1.`staff_id` IN (6) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-15 00:00:00' AND '2019-03-15 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND (A1.`team_id` IN (4) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (6) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-14 00:00:00' AND '2019-03-14 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-11 00:00:00' AND '2019-03-17 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 6 OR A5.`staff_id` = 6 OR A1.`team_id` IN (4) OR A6.`team_id` IN (4))) OR A1.`dept_id` IN (1) OR A7.`id` IN (1)]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A1.`isanswered` = '0'' at line 1<br /> <br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (root)/include/class.search.php(922): QuerySet->one()<br />
#12 (root)/include/ajax.search.php(397): SavedQueue::counts(Object(StaffSession), true, Array)<br />
#13 (root)/include/class.dispatcher.php(145): SearchAjaxAPI->collectQueueCounts()<br />
#14 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('counts', Array)<br />
#15 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('counts', Array)<br />
#16 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/queue/counts', NULL)<br />
#17 (root)/scp/ajax.php(289): Dispatcher->resolve('/queue/counts')<br />
#18 {main}
```

**Comment by JediKev** [comment]
@phatair 

...that shouldn't happen...

My queues are functioning properly, they are as follows:
```
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Queue          | Config                                                                                                                         |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Open           | {"criteria":[["status__state","includes",{"open":"Open"}]]}                                                                    |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Answered       | [["isanswered","set",null]]                                                                                                    |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| My Tickets     | {"criteria":[["assignee","includes",{"M":"Me","T":"One of my teams"}],["status__id","includes",{"1":"Open"}]],"conditions":[]} |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Closed         | [["status__state","includes",{"closed":"Closed"}]]                                                                             |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Assigned       | [["assignee","assigned",null]]                                                                                                 |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Overdue        | [["isoverdue","set",null]]                                                                                                     |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Team Tickets   | {"criteria":[["status__id","includes",{"1":"Open"}],["assignee","includes",{"T":"One of my teams"}]],"conditions":[]}          |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Assigned To Me | {"criteria":[["staff_id","includes",{"M":"Me"}]],"conditions":[]}                                                              |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
| Open           | {"criteria":[["status__state","includes",{"open":"Open"}]],"conditions":[]}                                                    |
+----------------+--------------------------------------------------------------------------------------------------------------------------------+
```

Do yours look similar?

Cheers.

**Comment by phatair** [comment]
Do you mean the DB Table "ost_queue", right?
They look like this:
![image](https://user-images.githubusercontent.com/28873754/54520232-8814c600-4968-11e9-8e1d-17f6dfb24877.png)

I dont have a column "Queue", i have only a column "title".
The column "config" looks a little bit different to yours.

```
'Open', '[["status__state","includes",{"open":"Open"}]]'
'Open', '{"criteria":[["isanswered","nset",null]],"conditions":[]}'
'Answered', '{"criteria":[["isanswered","set",null]],"conditions":[]}'
'Overdue', '{"criteria":[["isoverdue","set",null]],"conditions":[]}'
'My Tickets', '{"criteria":[["assignee","includes",{"M":"Me","T":"One of my teams"}],["status__state","includes",{"open":"Open"}]],"conditions":[]}'
'Assigned to Me', '{"criteria":[["assignee","includes",{"M":"Me"}]],"conditions":[]}'
'Assigned to Teams', '{"criteria":[["assignee","!includes",{"M":"Me"}]],"conditions":[]}'
'Closed', '{"criteria":[["status__state","includes",{"closed":"Closed"}]],"conditions":[]}'
'Today', '{"criteria":[["closed","period","td"]],"conditions":[]}'
'Yesterday', '{"criteria":[["closed","period","yd"]],"conditions":[]}'
'This Week', '{"criteria":[["closed","period","tw"]],"conditions":[]}'
'This Month', '{"criteria":[["closed","period","tm"]],"conditions":[]}'
'This Quarter', '{"criteria":[["closed","period","tq"]],"conditions":[]}'
'This Year', '{"criteria":[["closed","period","ty"]],"conditions":[]}'
'Wartend', '{"status_id+search":"1","status_id+includes":"{\\"8\\":\\"Wartend\\"}"}'
```

**Comment by JediKev** [comment]
@phatair 

Okay, so after some sleep and the image you posted, I see the issue. The issue is due to the `ost_queue` record with `id` of `15`. This queue's `config` data is incorrect as it's in the old "Saved Search" format. You will need to update this to the new format, like so:
```
{"criteria":[["status__id","includes",{"8":"Wartend"}]],"conditions":[]}
```

After updating the `config` data the error should go away and you should be a happy camper. 😄⛺️🔥

Cheers.

**Comment by phatair** [comment]
@JediKev 

looks good - i changed the id 15 to your format and now it looks like that the error is gone 👍 
Thank you very much!!

**Comment by lourdas** [comment]
I posted a screenshot of my ost_queue table in another issue: https://github.com/osTicket/osTicket/issues/4801#issuecomment-485345198

And the error persists.

**Comment by lourdas** [comment]
Unfortunately and because of other errors, I had to revert back to 1.10.1...

**Comment by staskur** [comment]
> Unfortunately and because of other errors, I had to revert back to 1.10.1...

mysql ver. 5.7 ?

**Comment by lourdas** [comment]
> > Unfortunately and because of other errors, I had to revert back to 1.10.1...
> 
> mysql ver. 5.7 ?

No, MariaDB 5.6.

**Comment by TheEnergy** [comment]
i got the DB Error #1064 also.
What should i edit in my table? I dont have ID 15

![image](https://user-images.githubusercontent.com/54671083/64148081-a0977080-ce22-11e9-9fad-942126dbb2e4.png)

**Comment by JediKev** [comment]
@TheEnergy 

Of course, your install might differ from the OP's install so that's why you don't have a record with an ID `15`. You will need to post the exact error in order for us to assist.

Cheers.

**Comment by glienhard** [comment]
I had the exact same issue when upgrading from v1.10 to 1.12

The solution that ultimately fixed the issue was to have each agent delete any old custom search they had and recreate it in the new version. This works out for the better because the search function in the older versions was not as good.
