### ISSUE TITLE
Ticket creation error: ObjectNotUnique

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#4943]
Hello,

I really don´t know what is the problem so I post the error that occurs when I try to create a new ticket via e-mail that gets piped to automail.php:

> PHP Fatal error:  Uncaught ObjectNotUnique: One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects. in /path/to/ticketsystem/include/class.orm.php:1355
\nStack trace:
\n#0 /path/to/ticketsystem/include/class.orm.php(606): QuerySet->one()
\n#1 /path/to/ticketsystem/include/class.thread.php(3031): VerySimpleModel::lookup(Array)
\n#2 /path/to/ticketsystem/include/class.orm.php(381): ObjectThread::lookup(Array)
\n#3 /path/to/ticketsystem/include/class.orm.php(417): VerySimpleModel->get('thread', NULL)
\n#4 /path/to/ticketsystem/include/class.ticket.php(800): VerySimpleModel->__get('thread')
\n#5 /path/to/ticketsystem/include/class.ticket.php(3027): Ticket->getThread()
\n#6 /path/to/ticketsystem/include/class.ticket.php(3878): Ticket->logEvent('created', NULL, Object(User))
\n#7 /path/to/ticketsystem/include/api.tickets.php(133): Ticket::create(Array, Array, 'Email', true, true)
\n#8 /path/to/ticketsystem/include/api.tickets. in /path/to/ticketsystem/include/class.orm.php on line 1355

Regards,

Af0x

**Comment by JediKev** [comment]
@Af0x

You have a duplicate thread in the `ost_thread` table.

Cheers.

**Comment by Af0x** [comment]
you´re right. But how is this possible?
![duplicate-thread](https://user-images.githubusercontent.com/7013929/60758013-1abd9b80-a012-11e9-8408-b32fce3c8716.png)

**Comment by JediKev** [comment]
@Af0x

Maybe the db glitched, maybe you created ticket by Fetching and web at the same time, who knows...it looks like you’re fine though as it started incrementing the object_id again.

Cheers.
