### ISSUE TITLE
DB Error 1062

### ISSUE THREAD

**Issue by sushanku** [osTicket/osTicket#5305]
**Expected behavior:** Duplicate entry issue should be solved, I guess.

**Actual behavior:** Since I have moved the osticket from one server to another server. This duplicate entry issue has been occurring and it's occurring every day.

### Versions
osTicket (v1.12)

DB Error #1062
[INSERT INTO `ost_session` SET `session_id` = 'tihuii6a5bia34kkrhs8b4mn43', `session_data` = 'csrf|a:2:{s:5:\"token\";s:40:\"9ec682dd6f18e0abde3f6c32bf8aced1ea41379f\";s:4:\"time\";i:1577245730;}_auth|a:1:{s:5:\"staff\";N;}', `session_expire` = (NOW() + INTERVAL 86400 SECOND), `user_ip` = '110.44.116.104', `user_agent` = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'] Duplicate entry 'tihuii6a5bia34kkrhs8b4mn43' for key 'PRIMARY'

---- Backtrace ----
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
#1 (root)/include/class.orm.php(3455): db_query('INSERT INTO `os...', true, true)
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()
#3 (root)/include/class.ostsession.php(227): VerySimpleModel->save()
#4 (root)/include/class.ostsession.php(158): DbSessionBackend->update('tihuii6a5bia34k...', 'csrf|a:2:{s:5:"...')
#5 [internal function]: SessionBackend->write('tihuii6a5bia34k...', 'csrf|a:2:{s:5:"...')
#6 [internal function]: session_write_close()
#7 {main}

Log Date: Wed, Dec 25 2019 9:33AM IP Address: 110.44.116.104

OS and OS Version: Ubuntu 18.04.
Apache: 2.4
php 5.6
mysql 5.7

**Comment by JediKev** [comment]
@sushanku 

Truncate and repair the `ost_session` table to see if that helps. If you don’t know how, reference MySQL documentation.

Cheers.

**Comment by JediKev** [comment]
Closing due to inactivity. Please reopen if still an issue.
