### ISSUE TITLE
Slow performance when tickets are counted

### ISSUE THREAD

**Issue by ke1v3y** [osTicket/osTicket#5393]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When using osTicket v1.14.1, end users are experiencing performance issues. This appears to be related to getting ticket counts. When reviewing the logs, we are seeing very frequent occurrences of DB Error #1054. This appears similar to issue #5365, but has a different error in the logs. This issue is most prevalent when closing tickets.

```[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`id` IN (1, 2) AND A3.`lastmessage` <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(200): osTicket-&gt;logDBError('DB Error #1054', '[SELECT COUNT(D...')<br /> #1 (root)/include/class.orm.php(3459): db_query('SELECT COUNT(DI...', true, true)<br /> #2 (root)/include/class.orm.php(3506): MySqlExecutor-&gt;execute()<br /> #3 (root)/include/class.orm.php(2093): MySqlExecutor-&gt;getArray()<br /> #4 (root)/include/class.orm.php(2043): HashArrayIterator-&gt;{closure}()<br /> #5 (root)/include/class.orm.php(2022): CallbackSimpleIterator-&gt;next()<br /> #6 (root)/include/class.orm.php(2031): CallbackSimpleIterator-&gt;rewind()<br /> #7 (root)/include/class.orm.php(1703): CallbackSimpleIterator-&gt;valid()<br /> #8 (root)/include/class.orm.php(1713): CachedResultSet-&gt;fillTo(9223372036854775807)<br /> #9 (root)/include/class.orm.php(1336): CachedResultSet-&gt;asArray()<br /> #10 (root)/include/class.orm.php(1359): QuerySet-&gt;all()<br /> #11 (root)/include/class.search.php(973): QuerySet-&gt;one()<br /> #12 (root)/include/class.search.php(905): SavedQueue::counts(Object(StaffSession), true)<br /> #13 (root)/include/staff/templates/queue-tickets.tmpl.php(111): SavedQueue-&gt;getCount(Object(StaffSession))<br /> #14 (root)/scp/tickets.php(539): require_once('/home/helpdeskc...')<br /> #15 {main}```

### Versions

osTicket Info:
osTicket Version | v1.14.1 (f1e9e88) —  Up to date
Web Server Software | Apache
MySQL Version | 10.1.44
PHP Version | 7.2.28
...
Schema | helpdeskces_ostick (localhost)
Schema Signature | 4bd47d94b10bd8a6bab35c119dadf41f
Space Used | 11597.35 MiB
Space for Attachments | 9730.62 MiB
Timezone | EST (Interpreted as America/New_York)

Server Info:
cPanel Version	84.0 (build 21)
Apache Version	2.4.41
PHP Version	7.2.28
MySQL Version	10.1.44-MariaDB
Architecture	x86_64
Operating System	linux
Shared IP Address	162.211.80.200
Path to Sendmail	/usr/sbin/sendmail
Path to Perl	/usr/bin/perl
Perl Version	5.16.3
Kernel Version	3.10.0-1062.4.2.vz7.116.7

**Comment by JediKev** [comment]
@ke1v3y 

Is that the full error? Usually, it has the SQL error as well that points us to what part of the query is causing issues. (eg. `Table 'ost_ticket__cdata' doesn't exist` or `Unknown column 'relevance' in 'order clause'`)

Cheers.

**Comment by ke1v3y** [comment]
@JediKev 

This is a different occurrence of the same error, pulled from the System Logs:
```
[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`id` IN (1, 2) AND A3.`lastmessage`
---- Backtrace ----
#0 (root)/include/mysqli.php(200): osTicket->logDBError('DB Error #1054', '[SELECT COUNT(D...')
#1 (root)/include/class.orm.php(3459): db_query('SELECT COUNT(DI...', true, true)
#2 (root)/include/class.orm.php(3506): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(2093): MySqlExecutor->getArray()
#4 (root)/include/class.orm.php(2043): HashArrayIterator->{closure}()
#5 (root)/include/class.orm.php(2022): CallbackSimpleIterator->next()
#6 (root)/include/class.orm.php(2031): CallbackSimpleIterator->rewind()
#7 (root)/include/class.orm.php(1703): CallbackSimpleIterator->valid()
#8 (root)/include/class.orm.php(1713): CachedResultSet->fillTo(9223372036854775807)
#9 (root)/include/class.orm.php(1336): CachedResultSet->asArray()
#10 (root)/include/class.orm.php(1359): QuerySet->all()
#11 (root)/include/class.search.php(973): QuerySet->one()
#12 (root)/include/ajax.search.php(397): SavedQueue::counts(Object(StaffSession), true, Array)
#13 (root)/include/class.dispatcher.php(145): SearchAjaxAPI->collectQueueCounts()
#14 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('counts', Array)
#15 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('counts', Array)
#16 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/queue/counts', NULL)
#17 (root)/scp/ajax.php(308): Dispatcher->resolve('/queue/counts')
#18 {main}
```

**Comment by JediKev** [comment]
@ke1v3y 

That can't be the full error...it's missing the actual SQL Error. Can you look at your MySQL error logs to see if a full error is logged there?

Cheers.

**Comment by ke1v3y** [comment]
@JediKev 

This is what I get from the log column when querying ost5h_syslog column:
`[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`id` IN (1, 2) AND A3.`lastmessage` <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(200): osTicket-&gt;logDBError('DB Error #1054', '[SELECT COUNT(D...')<br /> #1 (root)/include/class.orm.php(3459): db_query('SELECT COUNT(DI...', true, true)<br /> #2 (root)/include/class.orm.php(3506): MySqlExecutor-&gt;execute()<br /> #3 (root)/include/class.orm.php(2093): MySqlExecutor-&gt;getArray()<br /> #4 (root)/include/class.orm.php(2043): HashArrayIterator-&gt;{closure}()<br /> #5 (root)/include/class.orm.php(2022): CallbackSimpleIterator-&gt;next()<br /> #6 (root)/include/class.orm.php(2031): CallbackSimpleIterator-&gt;rewind()<br /> #7 (root)/include/class.orm.php(1703): CallbackSimpleIterator-&gt;valid()<br /> #8 (root)/include/class.orm.php(1713): CachedResultSet-&gt;fillTo(9223372036854775807)<br /> #9 (root)/include/class.orm.php(1336): CachedResultSet-&gt;asArray()<br /> #10 (root)/include/class.orm.php(1359): QuerySet-&gt;all()<br /> #11 (root)/include/class.search.php(973): QuerySet-&gt;one()<br /> #12 (root)/include/class.search.php(905): SavedQueue::counts(Object(StaffSession), true)<br /> #13 (root)/include/staff/templates/queue-tickets.tmpl.php(111): SavedQueue-&gt;getCount(Object(StaffSession))<br /> #14 (root)/scp/tickets.php(539): require_once('/home/helpdeskc...')<br /> #15 {main}`

**Comment by JediKev** [comment]
@ke1v3y 

Right, that's the same error you posted above..

I need the full error. Check your MySQL error logs, _not osTicket's System Logs_.

Cheers.

**Comment by ke1v3y** [comment]
@JediKev 

Gotcha. I'll track that down (need to get root credentials) and send it over.
