### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by bakertaylor28** [osTicket/osTicket#5419]
Upon fresh install received the following error, which was typical for every attempted write to the database:  

[INSERT INTO `ost_thread_entry` SET `created` = NOW(), `type` = 'M', `thread_id` = 2, `format` = 'html', `flags` = 192, `ip_address` = '98.178.179.240', `body` = '<p>Test user is to be blocked permenantly because of a unspecified reason This is a test entry</p>']

Field 'updated' doesn't have a default value<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(200): osTicket->logDBError('DB Error #1364', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3459): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(1778): VerySimpleModel->save(true)<br />
#4 (root)/include/class.thread.php(1794): ThreadEntry::create(Array)<br />
#5 (root)/include/class.thread.php(2914): ThreadEntry::add(Array)<br />
#6 (root)/include/class.thread.php(3129): MessageThreadEntry::add(Array, Array)<br />
#7 (root)/include/class.ticket.php(3047): ObjectThread->addMessage(Array, Array)<br />
#8 (root)/include/class.ticket.php(4319): Ticket->postMessage(Array, 'Web', false)<br />
#9 (root)/open.php(42): Ticket::create(Array, Array, 'Web')<br />
#10 {main}

**Comment by JediKev** [comment]
@bakertaylor28 

Version your running? Environment details? Screenshot of **Admin Panel > Dashboard > Information** would be nice as well.

Cheers.
