### ISSUE TITLE
some ticket show cuting pages while error Unknown or bad format class.businesshours.php:170

### ISSUE THREAD

**Issue by visiniaga** [osTicket/osTicket#5532]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
not yet test

* [ ] Do you have any errors in the PHP error log, or javascript console?
[Thu Jun 04 13:04:35.447179 2020] [php7:error] [pid 1469] [client 117.102.226.70:38998] PHP Fatal error:  Uncaught Exception: DateInterval::__construct(): Unknown or bad format (PT2.887E+4S) in /var/www/support/include/class.businesshours.php:170\nStack trace:\n#0 /var/www/support/include/class.businesshours.php(170): DateInterval->__construct('PT2.887E+4S')\n#1

/var/www/support/include/class.schedule.php(479): BusinessHours->addWorkingHours(Object(DateTime), 45)\n#2 /var/www/support/include/class.sla.php(56): BusinessHoursSchedule->addWorkingHours(Object(DateTime), 45, Array)\n#3 /var/www/support/include/class.ticket.php(544): SLA->addGracePeriod(Object(DateTime), Object(BusinessHoursSchedule))\n#4 /var/www/support/include/class.ticket.php(562): Ticket->getSLADueDate()\n#5 /var/www/support/include/staff/ticket-view.inc.php(601): Ticket->getEstDueDate()\n#6 /var/www/support/scp/tickets.php(541): require_once('/var/www/suppor...')\n#7 {main}\n  thrown in /var/www/support/include/class.businesshours.php on line 170, referer: https://support.visiniaga.com/scp/tickets.php?a=search&search-type=&query=VMK7191130

* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
yes, not yet resolve 
http://forum.osticket.com/d/97382-negotiation-error-and-bad-format

* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
yes

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
from current exisiting ticket number VMK7191130, 
in the table:
(6873,NULL,'VMK7191130',608,0,20,15,11,18,68,43,15,0,0,0,'','Email',NULL,0,1,NULL,NULL,NULL,'2020-06-02 1
6:10:28','2020-06-02 16:10:28','2020-05-15 16:40:42','2020-06-02 16:10:29')

('T',6873,'VMK7191130 200515 - CUSTOMER - LAPTOP DAN PRINTER','200515 - CUSTOMER - LAPTOP DAN PRINTER')

2. [Second Step]
it show ticket with cut pages
https://www.dropbox.com/s/dky3p2xuazkh7ol/WhatsApp%20Image%202020-06-04%20at%2009.21.02.jpeg?dl=0

3. [and so on...]
Only workaround is disabled line 170
                    #$interval = new DateInterval('PT'.$time.'S');
                    $interval = 0;
then change Due Date and SLA in the web pages. then revert back code,
now ticket number pages is loading normal

**Expected behavior:** [What you expected to happen]
it show complete pages

**Actual behavior:** [What actually happened]
cut pages ticket 

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
osTicket Version	v1.14.2 (cba6035) —  Up to date
Web Server Software	Apache
MySQL Version	10.4.13
PHP Version	7.2.31

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Centos 7.x
Chrome Browser Version 83.0.4103.77 (Official Build) (64-bit)

**Comment by JediKev** [comment]
@visiniaga 

So, your interval_spec looks like `PT2.887E+4S` and as you can see it contains a crazy looking float of `2.887E+4` (which really means `28870` - your interval_spec should actually look like `PT28870S`). What does your SLA's Grace Period look like? Is it a really large number or is it a float?

Cheers.

**Comment by visiniaga** [comment]
checking table sla id 11 it should have this:
chronological update:
- before upgrade to 1.14.x, it have 120 hours
- after upgrade to 1.14.x, added for business hour and change to 45 hours, it happens in 18 May
- ticket mentioned created in 15 May, but right now, any other tickets dont have this problem. 

| 11 |           2 |     9 |           45 | VISI PROJECT_IN SLA (05 wrkday)  |                              | 2018-09-17 14:13:59 | 2020-05-18 23:08:28 |

**Comment by visiniaga** [comment]
error raise when creating new ticket,
selecting SLA different than System Default result no difference, 

[Fri Jun 05 16:53:37.510941 2020] [php7:error] [pid 27486] [client 117.102.226.70:34012] PHP Fatal error:  Uncaught Exception: DateInterval::__construct(): Unknown or bad format (PT2.198E+4S) in /var/www/support/include/class.businesshours.php:170\nStack trace:\n#0 /var/www/support/include/class.businesshours.php(170): DateInterval->__construct('PT2.198E+4S')\n#1 /var/www/support/include/class.schedule.php(479): BusinessHours->addWorkingHours(Object(DateTime), 3)\n#2 /var/www/support/include/class.sla.php(56): BusinessHoursSchedule->addWorkingHours(Object(DateTime), 3, Array)\n#3 /var/www/support/include/class.ticket.php(544): SLA->addGracePeriod(Object(DateTime), Object(BusinessHoursSchedule))\n#4 /var/www/support/include/class.ticket.php(555): Ticket->getSLADueDate(true)\n#5 /var/www/support/include/class.ticket.php(4458): Ticket->updateEstDueDate()\n#6 /var/www/support/include/class.ticket.php(4561): Ticket::create(Array, Array, 'staff', false)\n#7 /var/www/support/scp/tickets.php(400): Ticket::open(Array, Array)\n#8 {main}\n  thrown in /var/www/support/include/class.businesshours.php on line 170, referer: https://support.visiniaga.com/scp/tickets.php?a=open&uid=705

checking it may problem with float number, is it safe it change with intval
file class.businesshours.php line 169 :
                    $time = intval(round(($_seconds-$seconds)));

**Comment by JediKev** [comment]
@visiniaga 

It's okay to use Floats, just not the crazy formatted ones like `2.887E+4` (in your case). We will take a deeper look into this and get back to you.

Cheers.

**Comment by JediKev** [comment]
@visiniaga 

Playing with this a little bit, say we use `intval(round(xxx))` (like you suggested) if we pass in `2.887E+4` (like your instance) it actually returns the correct value of `28870` (which is what we expect). I will bring this to the team's attention and get back to you.

Cheers.

**Comment by JediKev** [comment]
@visiniaga 

Can you put `var_dump($_seconds, $seconds);die;` above line `169` in `include/class.businesshours.php` and paste the results here? I'm trying to figure out where the scientific notation is coming into play here.

Cheers.

**Comment by JediKev** [comment]
@visiniaga 

I believe you are getting the Scientific Format on small floats due to your [`precision` INI setting](https://www.php.net/manual/en/ini.core.php#ini.precision).

Regardless, here is the patch to force int values for floats (for businesshours):
- https://github.com/osTicket/osTicket/pull/5537

Thanks again for the report!

Cheers.
