### ISSUE TITLE
Task Update "Assign To" Throws DB Error

### ISSUE THREAD

**Issue by francogp** [osTicket/osTicket#5584]
### Description

tasks manipulation spam admin mail with this error:

### Steps to Reproduce

1. try to change "assign to" from task

**Expected behavior:** don't throw errors

**Actual behavior:** an email content

```
[SELECT 'open', count(task.id ) AS tasks FROM ost_task task  WHERE task.flags & 1 != 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 )  OR  ( task.team_id IN() AND task.flags & 1 != 0 ) OR task.dept_id IN(1,3,4,5,6,7,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36)  ) UNION SELECT 'overdue', count( task.id ) AS tasks FROM ost_task task  WHERE task.flags & 1 != 0  AND task.flags & 2 != 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 )  OR  ( task.team_id IN() AND task.flags & 1 != 0 ) OR task.dept_id IN(1,3,4,5,6,7,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36)  ) UNION SELECT 'assigned', count( task.id ) AS tasks FROM ost_task task  WHERE task.flags & 1 != 0 AND task.staff_id = 2 AND ( (task.staff_id=2 AND task.flags & 1 != 0 )  OR  ( task.team_id IN() AND task.flags & 1 != 0 ) OR task.dept_id IN(1,3,4,5,6,7,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36)  ) UNION SELECT 'closed', count( task.id ) AS tasks FROM ost_task task  WHERE task.flags & 1 = 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 )  OR  ( task.team_id IN() AND task.flags & 1 != 0 ) OR task.dept_id IN(1,3,4,5,6,7,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36)  ) ]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND task.flags & 1 != 0 ) OR task.dept_id IN(1,3,4,5,6,7,9,10,11,12,13,14,15,1' at line 1<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(200): osTicket->logDBError()<br />
#1 (root)/include/class.task.php(1683): db_query()<br />
#2 (root)/include/class.staff.php(652): Task::getStaffStats()<br />
#3 (root)/scp/tasks.php(132): Staff->getTasksStats()<br />
#4 {main}
```

### Versions

![image](https://user-images.githubusercontent.com/2739706/87786109-c5fd5500-c80f-11ea-9783-aaa86389822d.png)

Ubuntu 20.04

**Comment by JediKev** [comment]
@francogp 

I would like for you to edit `/path/to/osticket/include/class.task.php`, go to the `function getStaffStats()` method, and change the following:
```
if(($teams=$staff->getTeams()))
```
TO
```
var_dump($staff->getTeams());die;
if(($teams=$staff->getTeams()))
```

Once you make these changes reload the Task page, copy what is returned in the browser, and paste it here for review. I'm curious, as even though I don't have Teams mine does not throw the error (meaning I cannot replicate this issue). I am using PHP 7.4.x as well so I don't think this is PHP version specific.

Cheers.

**Comment by francogp** [comment]
@JediKev I managed to "workaround it", The problem is when you have an EMPTY team. I populate all of them, and now no errors appear, but if I empty one team, this problem appear.

**Comment by JediKev** [comment]
@francogp 

Right, like I said I cannot replicate this issue even with empty teams so we would like to get to the bottom of this and address the underlying issue. If you could follow the below steps it will help me get an idea of what you see and help me replicate the issue.
I would like for you to edit `/path/to/osticket/include/class.task.php`, go to the `function getStaffStats()` method, and change the following:
```
if(($teams=$staff->getTeams()))
```
TO
```
var_dump($staff->getTeams());die;
if(($teams=$staff->getTeams()))
```

Once you make these changes reload the Task page, copy what is returned in the browser, and paste it here for review.

Cheers.

**Comment by JediKev** [comment]
@francogp 

Any update on the changes?

Cheers.

**Comment by francogp** [comment]
@JediKev 

I'm not at the office right now (just closed) for testing, It has to wait until monday.
