### ISSUE TITLE
DB Error #1146

### ISSUE THREAD

**Issue by BoBeR182** [osTicket/osTicket#5591]
### Prerequisites

```
DB Error #1146

[SELECT A1.`number` AS `number`,  A1.`ticket_id` AS `ticket_id`,  A1.`source` AS `source`,  A1.`created` AS `created`,  A3.`subject` AS `cdata__subject`,  A1.`isoverdue` AS `isoverdue`,  A4.`name` AS `user__name`,  A3.`priority` AS `cdata__priority`,  A5.`firstname` AS `staff__firstname`,  A5.`lastname` AS `staff__lastname`,  A6.`name` AS `team__name`,  A1.`team_id` AS `team_id`,  A1.`isanswered` = '0' AS `2GkBZxz`,  (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _thread_count,  (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS _att_count,  COALESCE(A5.`firstname`,  A5.`lastname`,  A6.`name`,  'zzz') AS `assignee` FROM `ost_ticket` A1 JOIN (SELECT Q7.`ticket_id`,  Z1.relevance AS `relevance` FROM `ost_ticket` Q7 JOIN `ost_ticket_status` Q8 ON (Q7.`status_id` = Q8.`id`) LEFT JOIN `ost_thread` R0 ON (R0.`object_type` = 'T' AND Q7.`ticket_id` = R0.`object_id`) LEFT JOIN `ost_thread_referral` R1 ON (R0.`id` = R1.`thread_id`) LEFT JOIN `ost_staff` R2 ON (R1.`object_type` = 'S' AND R1.`object_id` = R2.`staff_id`) LEFT JOIN `ost_team` R3 ON (R1.`object_type` = 'E' AND R1.`object_id` = R3.`team_id`) LEFT JOIN `ost_department` R4 ON (R1.`object_type` = 'D' AND R1.`object_id` = R4.`id`) JOIN (SELECT COALESCE(Z3.`object_id`,  Z5.`ticket_id`,  Z8.`ticket_id`) as `ticket_id`,  Z1.relevance FROM (SELECT Z1.`object_id`,  Z1.`object_type`,  MATCH (Z1.title,  Z1.content) AGAINST ('test' IN NATURAL LANGUAGE MODE) AS `relevance` FROM `ost__search` Z1 WHERE MATCH (Z1.title,  Z1.content) AGAINST ('test' IN NATURAL LANGUAGE MODE) ORDER BY relevance DESC) Z1 LEFT JOIN `ost_thread_entry` Z2 ON (Z1.`object_type` = 'H' AND Z1.`object_id` = Z2.`id`) LEFT JOIN `ost_thread` Z3 ON (Z2.`thread_id` = Z3.`id` AND Z3.`object_type` = 'T') LEFT JOIN `ost_ticket` Z5 ON (Z1.`object_type` = 'T' AND Z1.`object_id` = Z5.`ticket_id`) LEFT JOIN `ost_user` Z6 ON (Z6.`id` = Z1.`object_id` and Z1.`object_type` = 'U') LEFT JOIN `ost_organization` Z7 ON (Z7.`id` = Z1.`object_id` AND Z7.`id` = Z6.`org_id` AND Z1.`object_type` = 'O') LEFT JOIN `ost_ticket` Z8 ON (Z8.`user_id` = Z6.`id`)) Z1 WHERE Q7.`ticket_id` = Z1.`ticket_id` AND ((Q8.`state` = 'open' AND (Q7.`staff_id` = 1 OR R2.`staff_id` = 1 OR Q7.`team_id` IN (2) OR R3.`team_id` IN (2))) OR Q7.`dept_id` IN (1) OR R4.`id` IN (1)) ORDER BY Z1.relevance LIMIT 500) A2 LEFT JOIN `ost_ticket__cdata` A3 ON (A1.`ticket_id` = A3.`ticket_id`) JOIN `ost_user` A4 ON (A1.`user_id` = A4.`id`) LEFT JOIN `ost_staff` A5 ON (A1.`staff_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A1.`team_id` = A6.`team_id`) WHERE A1.`ticket_id` = A2.`ticket_id` GROUP BY A1.`ticket_id` ORDER BY relevance DESC LIMIT 50] Table 'osticket.ost__search' doesn't exist
 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(200): osTicket->logDBError('DB Error #1146',  '[SELECT A1.`num...')
 #1 (root)/include/class.orm.php(3464): db_query('SELECT A1.`numb...',  true,  true)
 #2 (root)/include/class.orm.php(3511): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2087): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(2037): HashArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(2016): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(2025): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1697): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1707): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1723): CachedResultSet->asArray()
 #10 (root)/include/staff/templates/queue-tickets.tmpl.php(252): CachedResultSet->getIterator()
 #11 (root)/scp/tickets.php(532): require_once('/var/www/html/s...')
 #12 {main}
```

* [n/a] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n/a] Do you have any errors in the PHP error log, or javascript console?
* [yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]
Searches don't work

### Steps to Reproduce

1. Search "test"

**Expected behavior:** [What you expected to happen]
Tickets containing test

**Actual behavior:** [What actually happened]
no results

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
v1.12.6 e351ba5
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@BoBeR182 

That’s strange. The `ost__search` table should have been created once osTicket was installed. No worries though, the solution is simple. You can login to your database, go to the `ost_config` table, search for `key = 'reindex'`, and update the value from `0` to `1`. After you make the change simply login to osTicket, click around a bit, and the table should be recreated and populated with data automatically.

Cheers.

**Comment by BoBeR182** [comment]
That fixed it, thank you.
