### ISSUE TITLE
Ticket blank because of duplicate in database

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#5639]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "stable" branch? YES Cannot test the dev
* [ ] Do you have any errors in the PHP error log, or javascript console? 

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ObjectNotUnique: One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects. in osticket/include/class.orm.php:1363\nStack trace:\n#0 osticket/include/class.orm.php(606): QuerySet->one()\n#1 osticket/include/staff/templates/thread-entries.tmpl.php(37): VerySimpleModel::lookup(Array)\n#2 osticket/include/class.thread.php(415): include('/home/piadm/pub...')\n#3 osticket/include/staff/ticket-view.inc.php(773): Thread->render(Array, Array)\n#4 osticket/scp/tickets.php(560): require_once('/home/piadm/pub...')\n#5 {main}\n  thrown in osticket/include/class.orm.php on line 1363', referer: https://supporto.peopleinside.it/scp/tickets.php

* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
Yes never resolved. 
[Ticket not showed if the elaborated email is an email forwarded](https://forum.osticket.com/d/96445-ticket-not-showed-if-the-elaborated-email-is-an-email-forwarded)

* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? YES

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

BUG: Some action made OsTicket go in TILT have a dupicate data in the database so ticket new tickets and replies are empty in the operator interface.

Because of this unresolved issue I need leave OsTicket. This is a very big issue and made me loosing a lot of tickets even in a new completely install.

### Steps to Reproduce

I never found how to reproduce.
Maybe if you delete a user or ticket. I'm unable to find how to reproduce but it happen often to me

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
v1.14.3 (f4f5bc6)

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
CentOS Linux release 8.2.2004 (Core), Firefox stable 81.0.1

**Comment by PeopleInside** [comment]
I really want to help you to resolve this or OsTicket, feel free to contact me privately.

**Comment by fatedsnowfox** [comment]
Hi!

Don't know if this'll help, but we had exactly this error today and the culprit was a cron job running twice.

**Comment by PeopleInside** [comment]
I have migrated to UVdesk... I think I will never return to OsTicket also if I love it.
Because of this issue I lost many tickets and worked more than 24 hours for migrate.

Good luck

**Comment by JediKev** [comment]
@PeopleInside 

The error is saying there are 2 `ost_thread_entry` records that match the given ID when there should only be one.

What @fatedsnowfox said is true, I've also seen instances where both Cron Job and Auto-Cron were enabled and caused duplicate records and fatal errors. Disabling Auto-Cron resolved the issue in those instances.

**Note:**
If you ever need our Professional Services you can contact us through the form on our website, via email, or via phone. You can go to our website and click Contact Us to see the contact options.

Cheers.

**Comment by PeopleInside** [comment]
Maybe was the auto-cron. Don't know.
I will leave this open as I think this issue should be resolved.
Thanks @JediKev 👍🏻
