### ISSUE TITLE
develop-next = 2FA plugin issue

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#5657]
Latest git clone of develop-next. Installed the plugin auth-password-policy. 
This is what happens when I install it. I presume the database is missing a column called "version".

[INSERT INTO os_plugin SET installed=NOW() , install_path='plugins/auth-password-policy', name='Password Management Policies', isphar='', version=0.1]

Unknown column 'version' in 'field list'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054', '[INSERT INTO os...')<br />
#1 (root)/include/class.plugin.php(353): db_query('INSERT INTO os_...')<br />
#2 (root)/scp/plugins.php(51): PluginManager->install('plugins/auth-pa...')<br />
#3 {main}

**Comment by JediKev** [comment]
@TechCare-Aus 

This has been mentioned on the forum and github a few times already. Please perform a recursive search on github and the forum before creating an issue.

You can find the answer here:
- https://forum.osticket.com/d/97496-audit-install/2

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev apologies mate. I figured it was cutting edge so here we were ironing out bugs.

while I followed your advice and with slight alteration managed to enable the plug in. The next error when trying to configure for agent gives me and email:

Subject: BaseError: Project-Id-Version: osticket-officialX-Osticket-Major-Version: 1.10POT-Create-Date: 2019-02-06 20:46 +0000Report-Msgid-Bugs-To: support@osticket.comLanguage: en_GBMIME-Version: 1.0Content-Type: text/plain; charset=UTF-8Content-Transfer-Encod...

Body: Unable to retrieve two factor authentication email template

Now I went to /includes/staff/template/ and it has 2fas.tmpl.php

**Comment by JediKev** [comment]
@TechCare-Aus 

>Body: Unable to retrieve two factor authentication email template

Now that's a new error lol I'll reopen this and assign it appropriately.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev no drama. haha. let me know what you need.

**Comment by JediKev** [comment]
@TechCare-Aus 

I was just informed that the template will be part of the upgrade migrations. Even though you see the template under `Agents > Templates`, it's just an entry, if you click on it there is no template.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev 

so you are saying this feature is not ready yet? Because I don't see any template:

![image](https://user-images.githubusercontent.com/2740134/96272807-2f545600-1001-11eb-9eea-9c708d5ed169.png)

**Comment by TechCare-Aus** [comment]
I have this file - include/i18n/en_US/templates/page/email2fa-staff.yaml

which appears to be the email template.

**Comment by JediKev** [comment]
@TechCare-Aus 

You're looking under `Admin Panel > Emails > Templates` but the template is actually under `Admin Panel > Settings > Agents > Templates`.

You'll see there is an "entry" for a template but there is no template content. Yes, there is a file for the template but it has not been loaded into the db via migrations hence why the system can't find it.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev ah fair enough. how do we load it? or am i too impatient?

**Comment by JediKev** [comment]
@TechCare-Aus 

You'll need to run the db migrations which is not a part of that pull.

Cheers.

**Comment by JediKev** [comment]
@TechCare-Aus 

For now you can simply run the following query:
```sql
INSERT INTO `ost_content`
    (`id`, `isactive`, `type`, `name`, `body`, `notes`, `created`, `updated`)
VALUES
    (null, 1, 'email2fa-staff', 'osTicket Two Factor Authentication', '<h3><strong>Hi %{staff.name.first},</strong></h3> <div> You have just logged into for the helpdesk at %{url}.<br /> <br /> Use the verification code below to finish logging into the helpdesk.<br /> <br /> %{otp}<br /> <br /> <em style=\"font-size: small\">Your friendly Customer Support System</em> <br /> <img src=\"cid:b56944cb4722cc5cda9d1e23a3ea7fbc\" alt=\"Powered by osTicket\" width=\"126\" height=\"19\" style=\"width: 126px\" /> </div>', 'This template defines the email sent to Staff who use Email for Two Factor Authentication', NOW(), NOW());
```

This should load the template in the DB and let it continue.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev 
That has allowed me to progress. Nice.

Next issue is password policy (Feel free to make this a new bug report, figured it was all part of it, but might be wrong)

I cranked up the complexity requirements but when it asks for me to change the password as a result it seems to require the old password to meet the new complexity requirements as well.

![image](https://user-images.githubusercontent.com/2740134/96324161-e6c58880-1052-11eb-9117-ec340e801b02.png)

**Comment by TechCare-Aus** [comment]
Minor spacing issue too:
![image](https://user-images.githubusercontent.com/2740134/96325730-c8fd2100-105c-11eb-87c2-85aca1c693ab.png)

**Comment by TechCare-Aus** [comment]
> @TechCare-Aus
> 
> For now you can simply run the following query:
> 
> ```sql
> INSERT INTO `ost_content`
>     (`id`, `isactive`, `type`, `name`, `body`, `notes`, `created`, `updated`)
> VALUES
>     (null, 1, 'email2fa-staff', 'osTicket Two Factor Authentication', '<h3><strong>Hi %{staff.name.first},</strong></h3> <div> You have just logged into for the helpdesk at %{url}.<br /> <br /> Use the verification code below to finish logging into the helpdesk.<br /> <br /> %{otp}<br /> <br /> <em style=\"font-size: small\">Your friendly Customer Support System</em> <br /> <img src=\"cid:b56944cb4722cc5cda9d1e23a3ea7fbc\" alt=\"Powered by osTicket\" width=\"126\" height=\"19\" style=\"width: 126px\" /> </div>', 'This template defines the email sent to Staff who use Email for Two Factor Authentication', NOW(), NOW());
> ```
> 
> This should load the template in the DB and let it continue.
> 
> Cheers.

Works. Thanks mate.

**Comment by protich** [comment]
@TechCare-Aus - I have a PR #5674 to exclude current password policy enforcement.  Please give it a test - and - thank you for pointing it out.
