### ISSUE TITLE
Error updating ticket status

### ISSUE THREAD

**Issue by g0rbe** [osTicket/osTicket#5852]
### Prerequisites

* [  ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO ] Do you have any errors in the PHP error log, or javascript console?
* [ YES] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Cant update the the status of the tickets: "Error updating ticket status".
No error in console, apache log, php-fpm, mysql log.

Tried with nginx (i know it is not supported)  and apache.

The logs respond with 200 to the AJAX request. 

Find some issue about this related to the timezone setting. NTP is enabled.
The timezone is the same on the server, date.timezone and the database timezone.

The only error in the osTicket's log is **DB Error 1305**:
```
UPDATE `ost_ticket` SET `isoverdue` = 1,  `updated` = NOW() WHERE `ost_ticket`.`ticket_id` = 1598 LIMIT 1] PROCEDURE dbname.update_ft does not exist
 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(201): osTicket->logDBError()
 #1 (root)/include/class.orm.php(3466): db_query()
 #2 (root)/include/class.orm.php(658): MySqlExecutor->execute()
 #3 (root)/include/class.ticket.php(3668): VerySimpleModel->save()
 #4 (root)/include/class.ticket.php(2434): Ticket->save()
 #5 (root)/include/class.ticket.php(4721): Ticket->markOverdue()
 #6 (root)/include/class.cron.php(30): Ticket::checkOverdue()
 #7 (root)/scp/autocron.php(54): Cron::TicketMonitor()
 #8 {main}
```

### Steps to Reproduce

1. Try to set the ticket status
2. Fail

**Expected behavior:** The ticket status is correctly set

**Actual behavior:**
![image](https://user-images.githubusercontent.com/36860942/113052071-fa9b1c00-91a6-11eb-9e4c-55e493cbe4bc.png)

### Versions

![image](https://user-images.githubusercontent.com/36860942/113052139-11417300-91a7-11eb-9ec5-4bc7b9256ec5.png)

OS: Ubuntu 20.04

**Comment by JediKev** [comment]
@g0rbe

For the DB Error 1305, it appears as though you (or someone else) setup a custom procedure in MySQL (called `update_ft` apparently) that is being triggered by the above query and it no longer exists (or was renamed). This has nothing to do with the software and will need to be handled by your database administrator or whomever setup the procedure/trigger.

As for `Error updating ticket status`, I can see that we throw the error when `$ticket->setStatus()` returns `false` and there is no `$errors['err']` set. It's basically a generic error message saying we couldn't set the status for some reason. If there are no related errors in any of your logs you will need to go to `include/class.ticket.php`, search for `function setStatus(`, and start `var_dump()`ing until you see where it's failing/returning `false`.

Cheers.

**Comment by g0rbe** [comment]
Hi!

I set `error_log()` before every `return false`. And a one  `error_log()` at the beginning of the function.

The only logged error is the first which is called at the beginning of the function:
`PHP message: setStatus() error: log working!`

None of the others are called.

Here is the modified function:

```
// Ticket Status helper.
    function setStatus($status, $comments='', &$errors=array(), $set_closing_agent=true, $force_close=false) {
        global $cfg, $thisstaff;

        error_log("setStatus() error: log working!", 0); <----- initial log, the function called


        if ($thisstaff && !($role=$this->getRole($thisstaff)))
            // Delete next line, manually added
            error_log("setStatus() error: 1", 0); <-------- 1. false
            return false;

        if ((!$status instanceof TicketStatus)
                && !($status = TicketStatus::lookup($status)))
            // Delete next line, manually added
            error_log("setStatus() error: 2", 0); <-------- 2. false
            return false;

        // Double check permissions (when changing status)
        if ($role && $this->getStatusId()) {
            switch ($status->getState()) {
            case 'closed':
                if (!($role->hasPerm(Ticket::PERM_CLOSE)))
                    // Delete next line, manually added
                    error_log("setStatus() error: 3", 0); <--------- 3. false
                    return false;
                break;
            case 'deleted':
                // XXX: intercept deleted status and do hard delete TODO: soft deletes
                if ($role->hasPerm(Ticket::PERM_DELETE))
                    error_log("setStatus() error: return $role->hasPerm(Ticket::PERM_DELETE)", 0); <------- 
                    return $this->delete($comments);
                // Agent doesn't have permission to delete  tickets
                // Delete next line, manually added
                error_log("setStatus() error: 4", 0); <------ 4. false
                return false;
                break;
            }
        }

        $hadStatus = $this->getStatusId();
        if ($this->getStatusId() == $status->getId())
            error_log("setStatus() true: 1", 0); <------- 1. true
            return true;

        // Perform checks on the *new* status, _before_ the status changes
        $ecb = $refer = null;
        switch ($status->getState()) {
            case 'closed':
                // Check if ticket is closeable
                $closeable = $force_close ? true : $this->isCloseable();
                if ($closeable !== true)
                    $errors['err'] = $closeable ?: sprintf(__('%s cannot be closed'), __('This ticket'));

                if ($errors)
                    // Delete next line, manually added
                    error_log("setStatus() error: 5", 0); <-------- 5. false
                    return false;

                $refer = $this->staff ?: $thisstaff;
                $this->closed = $this->lastupdate = SqlFunction::NOW();
                if ($thisstaff && $set_closing_agent)
                    $this->staff = $thisstaff;
                // Clear overdue flags & due dates
                $this->clearOverdue(false);

                $ecb = function($t) use ($status) {
                    $t->logEvent('closed', array('status' => array($status->getId(), $status->getName())), null, 'closed');
                    $type = array('type' => 'closed');
                    Signal::send('object.edited', $t, $type);
                    $t->deleteDrafts();
                };
                break;
            case 'open':
                if ($this->isClosed() && $this->isReopenable()) {
                    // Auto-assign to closing staff or the last respondent if the
                    // agent is available and has access. Otherwise, put the ticket back
                    // to unassigned pool.
                    $dept = $this->getDept();
                    $staff = $this->getStaff() ?: $this->getLastRespondent();
                    $autoassign = (!$dept->disableReopenAutoAssign());
                    if ($autoassign
                            && $staff
                            // Is agent on vacation ?
                            && $staff->isAvailable()
                            // Does the agent have access to dept?
                            && $staff->canAccessDept($dept))
                        $this->setStaffId($staff->getId());
                    else
                        $this->setStaffId(0); // Clear assignment
                }

                if ($this->isClosed()) {
                    $this->closed = null;
                    $this->lastupdate = $this->reopened = SqlFunction::NOW();
                    $ecb = function ($t) {
                        $t->logEvent('reopened', false, null, 'closed');
                        // Set new sla duedate if any
                        $t->updateEstDueDate();
                    };
                }

                // If the ticket is not open then clear answered flag
                if (!$this->isOpen())
                    $this->isanswered = 0;
                break;
            default:
                // Delete next line, manually added
                error_log("setStatus() error: 6", 0); <--------- 6. false
                return false;
        }
        $this->status = $status;
        if (!$this->save(true))
            // Delete next line, manually added
            error_log("setStatus() error: 7", 0); <-------- 7. false
            return false;

        // Refer thread to previously assigned or closing agent
        if ($refer && $cfg->autoReferTicketsOnClose())
            $this->getThread()->refer($refer);

        // Log status change b4 reload — if currently has a status. (On new
        // ticket, the ticket is opened and thereafter the status is set to
        // the requested status).
        if ($hadStatus) {
            $alert = false;
            if ($comments = ThreadEntryBody::clean($comments)) {
                // Send out alerts if comments are included
                $alert = true;
                $this->logNote(__('Status Changed'), $comments, $thisstaff, $alert);
            }
        }
        // Log events via callback
        if ($ecb)
            $ecb($this);
        elseif ($hadStatus)
            // Don't log the initial status change
            $this->logEvent('edited', array('status' => $status->getId()));

        error_log("setStatus() true: 2", 0); <------- 2. true
        return true;
    }
```

**Comment by JediKev** [comment]
@g0rbe 

Then it's probably because your Agent Account doesn't have permission to close the ticket. See what Department the Ticket is under and then check your Role to that Department.

Cheers.

**Comment by g0rbe** [comment]
I have "All Access" which is:
![image](https://user-images.githubusercontent.com/36860942/113206289-91cba680-926f-11eb-82b0-8d6ee575ef8c.png)

Best regards.

**Comment by JediKev** [comment]
@g0rbe 

Maybe you need to put the `error_log()`s outside the `if()` statements and retest.

Cheers.

**Comment by g0rbe** [comment]
Aaaaand it's solved.

I added parenthesis `{` and `}` to the `if`s. I missed it in the code above.
Maybe the `update_ft` is caused the error, i removed it earlier.

Thanks for your help :slightly_smiling_face:
