### ISSUE TITLE
DB Error #1054 - Unknown column 'B2.priority' in 'field list'

### ISSUE THREAD

**Issue by miniPCR-Jesse** [osTicket/osTicket#5904]
### Prerequisites

* [ X ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ X ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ X ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

I just setup a fresh install of osTicket on Ubuntu 20.04 using the [deployment instructions](https://github.com/osTicket/osTicket#deployment) on the main github page.  Setup went smoothly with no issues.  I then setup basic settings (email, company info, etc) in the admin panel.  Upon visiting the tickets tab in the agent panel I receive the an automated email with the following error:

```
[SELECT A1.`number` AS `number`, A1.`ticket_id` AS `ticket_id`, A1.`source` AS `source`, A1.`lastupdate` AS `lastupdate`, B2.`subject` AS `cdata__subject`, A1.`isoverdue` AS `isoverdue`, B4.`name` AS `user__name`, B2.`priority` AS `cdata__priority`, B5.`firstname` AS `staff__firstname`, B5.`lastname` AS `staff__lastname`, B6.`name` AS `team__name`, A1.`team_id` AS `team_id`, A1.`isanswered` = '0' AS `2GkBZxz`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _thread_count, (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS _att_count, B7.`expire` > NOW() AND NOT B7.`staff_id` = 1 AS `_locked`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS _collabs, COALESCE(B5.`firstname`, B5.`lastname`, B6.`name`, 'zzz') AS `assignee` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_department` B0 ON (A4.`object_type` = 'D' AND A4.`object_id` = B0.`id`) LEFT JOIN `ost_department` B1 ON (A7.`object_type` = 'D' AND A7.`object_id` = B1.`id`) LEFT JOIN `ost_ticket__cdata` B2 ON (A1.`ticket_id` = B2.`ticket_id`) LEFT JOIN `ost_ticket_priority` B3 ON (B2.`priority` = B3.`priority_id`) LEFT JOIN `ost_user` B4 ON (A1.`user_id` = B4.`id`) LEFT JOIN `ost_staff` B5 ON (A1.`staff_id` = B5.`staff_id`) LEFT JOIN `ost_team` B6 ON (A1.`team_id` = B6.`team_id`) LEFT JOIN `ost_lock` B7 ON (A1.`lock_id` = B7.`lock_id`) WHERE A2.`state` = 'open' AND ((A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A6.`object_type` = 'C' AND A8.`staff_id` = 1)) OR A1.`dept_id` IN (1, 3) OR B0.`id` IN (1, 3) OR A6.`object_type` = 'C' AND B1.`id` IN (1, 3)) AND (A1.`ticket_pid` IS NULL OR A1.`flags` & 8 != 0) GROUP BY A1.`ticket_id` ORDER BY B3.`priority_urgency` ASC, A1.`lastupdate` DESC LIMIT 25]

Unknown column 'B2.priority' in 'field list'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054', '[SELECT A1.`num...')<br />
#1 (root)/include/class.orm.php(3466): db_query('SELECT A1.`numb...', true, true)<br />
#2 (root)/include/class.orm.php(3513): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2093): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2043): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2022): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2031): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1703): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1713): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1729): CachedResultSet->asArray()<br />
#10 (root)/include/staff/templates/queue-tickets.tmpl.php(262): CachedResultSet->getIterator()<br />
#11 (root)/scp/tickets.php(561): require_once('(root)/i...')<br />
#12 {main}
```

There was a [similar post](https://forum.osticket.com/d/99451-errors-on-fresh-install-db-error-1054-and-fatal-error-in-tickets/2) on the osTicket forums and the instructions were to use the download page on osTicket's website instead.  Checking to see if there's there's a solution while using the git clone install option.

### Versions
OS: Ubuntu 20.04
osTicket Version | v1.15.2-57-g525b1669 (525b166)
Web Server Software | Apache/2.4.38 (Debian)
MySQL Version | 8.0.25
PHP Version | 7.4.19

**Comment by JediKev** [comment]
@miniPCR-Jesse 

This is a known issue that we have on our bug sheet to further investigate.

Cheers.

**Comment by miniPCR-Jesse** [comment]
@JediKev 

Thanks for the response.  Is there a prior version that new users should use while the bug is being investigated?

**Comment by ObiWahn** [comment]
I am suffering from the same issue. If users should not use the development version, then  you should set a different default branch or change the deployment instructions, so that they contain a `git checkout stable` or whatever!

**Comment by michalexvr** [comment]
I got here to put the same bug. i had no idea that implemented the develop version (thought that default branch was stable branch). Well, i fixed this bug adding the column manually:

`ALTER TABLE ost_ticket__cdata ADD COLUMN priority mediumtext DEFAULT NULL;`

If i find other issue i will comment.

**Comment by JediKev** [comment]
@ObiWahn Unfortunately our release phases don’t work like that currently. We plan to improve this in the future (especially with v2.0).

@michalexvr Thank you for the comment. Your "fix" will be overwritten once the CDATA table gets dropped and recreated (when updating and/or adding a new field to the Ticket Details Form). As mentioned in my earlier comment we will be further investigating this issue.

**Comment by credomane** [comment]
I just ran into this problem on 1.18.1 
I went to Admin Panel -> Manage -> Forms -> Ticket Details.

Adding/removing fields here seems to cause the WRONG column in the database to get modified.

[edit]  
Specifically what happened to me is the `priority` column in the table `ticket__cdata` was renamed to the new field I added.

This is specifically the field I added that broken the `priority` column
![image](https://github.com/osTicket/osTicket/assets/1283031/4095d7dc-e86a-430a-83df-e6deb9bd2ca8)
