### ISSUE TITLE
README.md should point to a working version instead of only mentioning development.

### ISSUE THREAD

**Issue by ObiWahn** [osTicket/osTicket#5910]
Hi,

I want to try out osTicket for the first time. I have used the develop branch on github. But the installation fails to show `open tickets` which seems to me to be the most important feature. I am able to see some tickets but I have to inspect a user to get there.

Can you recommend a TAG or HASH of this repository that is somewhat stable?

Please note that there might be a problem with `https://forum.osticket.com/` I am not able to get a confirmation mail.

**Comment by JediKev** [comment]
@ObiWahn 

> But the installation fails to show open tickets which seems to me to be the most important feature.

Sounds like you don’t have Department Access to the tickets so you can’t see them. You will only be able to see tickets that are in the departments you have access to or that you/one of your teams are assigned to. I feel like you can benefit from our documentation below:
- https://docs.osticket.com/

> Can you recommend a TAG or HASH of this repository that is somewhat stable?

`develop` is our development branch where we merge the latest bug fixes, new features, etc. to get them ready for a new release. You can use the version tags (like v1.15.2 or v1.14.6) to use the code of a packaged release.

> Please note that there might be a problem with https://forum.osticket.com/ I am not able to get a confirmation mail.

I am not able to replicate this issue. I get the email just fine (just tested it). Maybe check your spam folder or maybe you mistyped something on sign up?

Cheers.

**Comment by JediKev** [comment]
@ObiWahn 

Also, next time when creating an Issue please fill out the _entire_ Issue Template. You are lacking critical information that might be useful in debugging, replicating, etc.

Cheers.

**Comment by ObiWahn** [comment]
Hi,

I am using commit `525b1669d5cb4edae503c49d00ec7c45774fe32f` the only agent is the admin user that was created during installation. I have added the admin to the first level support team, and he is in the support and maintenance (Zugang / access) group, but the user is still not able to see Tickets at: https://obi****.org/osticket/scp/tickets.php

```
Serverinformationen
--
osTicket-Version | v1.15.2-57-g525b1669 (525b166)     —  Aktuell
Server-Software | Apache/2.4.38 (Debian)
MySQL-Version | 10.3.27
PHP-Version | 7.3.27-1~deb10u1

gdlib | Wird für die Bildmanipulation und PDF-Druck verwendet
imap | Wird für den E-Mail-Abruf verwendet
xml | XML API
xml-dom | Wird für die HTML E-Mail-Verarbeitung verwendet
json | Verbessert die Leistung beim Erzeugen und Verarbeiten von JSON
mbstring | Dringend empfohlen für nicht-westeuropäische Sprachinhalte
phar | Dringend empfohlen für Plug-ins und Sprachpakete
intl | Dringend empfohlen für nicht-westeuropäische Sprachinhalte
fileinfo | Wird verwendet, um Dateitypen für Uploads zu erkennen
zip | Used for ticket and task exporting
APCu | Verbessert die Gesamtleistung
Zend Opcache | Verbessert die Gesamtleistung

cgi.fix_pathinfo | "1" wird empfohlen, wenn AJAX nicht funktioniert
date.timezone | Eine Standard-Zeitzone festzulegen, wird dringend empfohlen

Schema | osticket (localhost)
Schema-Signatur | add628927ee030469f5d3272ebda1e16
Belegter Speicher gesamt | 3.28 MiB
Datenbankspeicher für Anhänge | 0.03 MiB
Zeitzone | CEST                      (Interpretiert als Europe/Berlin)


<br>
<h2>Installierte Sprachpakete</h2>
<div style="margin: 0 20px">
    <h3><strong>Deutsch</strong>
                    — de_DE                &nbsp;
        <span class="label label-verified" title="Verifiziert von updates.osticket.com"> <i class="icon icon-lock"></i>            Verifiziert</span>
        </h3>
        <div><code>de</code> — include/i18n/de.phar            <br> Version: 158808, für version v1.14            <br> Erstellt: Fri, 01 May 20 17:54:37 +0000        </div>
    <h3><strong>English (United States) (Englisch (Vereinigte Staaten))</strong>
                </h3>
        <div><code>en_US</code> — include/i18n/en_US        </div>
</div>
```
The problem occurs with recent chrome and firefox.

The error log shows frequently the following problem:

```
 DB Error #1054

[SELECT A1.`number` AS `number`,  A1.`ticket_id` AS `ticket_id`,  A1.`source` AS `source`,  A1.`lastupdate` AS `lastupdate`,  B4.`subject` AS `cdata__subject`,  A1.`isoverdue` AS `isoverdue`,  B6.`name` AS `user__name`,  B4.`priority` AS `cdata__priority`,  A1.`dept_id` AS `dept_id`,  B7.`name` AS `dept__name`,  A1.`isanswered` = '0' AS `2GkBZxz`,  (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _thread_count,  (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS _att_count,  B8.`expire` > NOW() AND NOT B8.`staff_id` = 1 AS `_locked`,  (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS _collabs FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_team` B0 ON (A4.`object_type` = 'E' AND A4.`object_id` = B0.`team_id`) LEFT JOIN `ost_team` B1 ON (A7.`object_type` = 'E' AND A7.`object_id` = B1.`team_id`) LEFT JOIN `ost_department` B2 ON (A4.`object_type` = 'D' AND A4.`object_id` = B2.`id`) LEFT JOIN `ost_department` B3 ON (A7.`object_type` = 'D' AND A7.`object_id` = B3.`id`) LEFT JOIN `ost_ticket__cdata` B4 ON (A1.`ticket_id` = B4.`ticket_id`) LEFT JOIN `ost_ticket_priority` B5 ON (B4.`priority` = B5.`priority_id`) LEFT JOIN `ost_user` B6 ON (A1.`user_id` = B6.`id`) LEFT JOIN `ost_department` B7 ON (A1.`dept_id` = B7.`id`) LEFT JOIN `ost_lock` B8 ON (A1.`lock_id` = B8.`lock_id`) WHERE (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND ((A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A6.`object_type` = 'C' AND A8.`staff_id` = 1 OR A1.`team_id` IN (1) OR B0.`team_id` IN (1) OR A6.`object_type` = 'C' AND B1.`team_id` IN (1))) OR A1.`dept_id` IN (3) OR B2.`id` IN (3) OR A6.`object_type` = 'C' AND B3.`id` IN (3)) AND (A1.`ticket_pid` IS NULL OR A1.`flags` & 8 != 0) GROUP BY A1.`ticket_id` ORDER BY B5.`priority_urgency` ASC,  A1.`est_duedate` DESC LIMIT 25] Unknown column 'B4.priority' in 'field list'

 ---- Ablaufverfolgung ----
 #0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054',  '[SELECT A1.`num...')
 #1 (root)/include/class.orm.php(3466): db_query('SELECT A1.`numb...',  true,  true)
 #2 (root)/include/class.orm.php(3513): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2093): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(2043): HashArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(2022): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(2031): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1703): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1713): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1729): CachedResultSet->asArray()
 #10 (root)/include/staff/templates/queue-tickets.tmpl.php(262): CachedResultSet->getIterator()
 #11 (root)/scp/tickets.php(561): require_once('/var/www/htdocs...')
 #12 {main}
Log-Datum: Sonntag, 13. Juni 2021 um 22:34 IP-Adresse: 10.13.42.2
```

And the browser console shows the following content.
```
Error in parsing value for ‘background-position’.  Declaration dropped. s3downbar.css:349:28
Elements matching selector: #s3downbar_hide_button:hover:active #s3downbar_hide_button_img
NodeList []
​
length: 0
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
​​
constructor: function ()
​​
entries: function entries()
​​
forEach: function forEach()
​​
item: function item()
​​
keys: function keys()
​​
length: 
​​
values: function values()
​​
Symbol(Symbol.iterator): function values()
​​
Symbol(Symbol.toStringTag): "NodeList"
​​
<get length()>: function length()
​​
<prototype>: Object { … }
```

From the apache error log:


```
[Sun Jun 13 22:21:42.347767 2021] [php7:error] [pid 31789] [client 10.13.42.2:44
                          550] PHP Fatal error:  Uncaught InconsistentModelException: Unable to prepare qu
                          ery:  SELECT A1.`number` AS `number`, A1.`ticket_id` AS `ticket_id`, A1.`source`
                           AS `source`, A1.`lastupdate` AS `lastupdate`, B2.`subject` AS `cdata__subject`,
                           A1.`isoverdue` AS `isoverdue`, B4.`name` AS `user__name`, B2.`priority` AS `cda
                          ta__priority`, B5.`firstname` AS `staff__firstname`, B5.`lastname` AS `staff__la
                          stname`, B6.`name` AS `team__name`, A1.`team_id` AS `team_id`, A1.`isanswered` =
                           '0' AS `2GkBZxz`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `
                          ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) L
                          EFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id
                          ` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _thread_count, (SELECT COUNT(
                          R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_typ
                          e` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON
                           (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AN
                          D R0.`i in /var/www/htdocs/osticket/include/class.orm.php on line 3467, referer:

```

**Comment by JediKev** [comment]
@ObiWahn 

That is a known issue listed here:
- #5904 

The above issue is still in progress.

It’s not recommended to use `develop` or `1.14.x` in production. You should be using the packaged releases on our downloads page or the version branches as I have mentioned in my previous comment. 

Cheers.

**Comment by ObiWahn** [comment]
Why is `develop` the only mentioned version in the deployment section of your `README.md`? I think this was just misleading. I am not sure how other people find you. I found you by looking for a ticketsystem, that is still actively developed. Therefore I found you on gitlab rather than osticket.com.

You should not be surprised that people follow the instructions which they find in the `README.md`. Not being precise in your `README` causes grief and frustration on both sides. I know it is open source and people should shut up and be grateful. But people can really cheer more and give you the credit you deserve, if they do not fall into the `You should not use that version pit` after following instructions. I hope you find this more constructive after the edit.
