### ISSUE TITLE
strtotime() expects parameter 1 to be string object given in osticket/include/class.lock.php

### ISSUE THREAD

**Issue by LH-Eelko** [osTicket/osTicket#5918]
### Prerequisites

* [ x ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ x ] Do you have any errors in the PHP error log, or javascript console?
* [ x ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ x ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

For some time now, I'm seeing errors like these in our PHP error log:

```
2021/07/09 10:53:37 [error] 172037#0: *219090 FastCGI sent in stderr: "PHP message: PHP Warning:  strtotime() expects parameter 1 to be string, object given in osticket/include/class.lock.php on line 66" while reading response header from upstream, client: <ip_address>, server: www.server.net, request: "POST /osticket/scp/ajax.php/lock/ticket/<id> HTTP/2.0", upstream: "fastcgi://unix:/var/run/server.sock:", host: "server.net", referrer: "https://server.net/osticket/scp/tickets.php?id={id}"
2021/07/09 11:15:11 [error] 172037#0: *220381 FastCGI sent in stderr: "PHP message: PHP Warning:  strtotime() expects parameter 1 to be string, object given in osticket/include/class.lock.php on line 66" while reading response header from upstream, client: <ip_address>, server: www.server.net, request: "POST /osticket/scp/ajax.php/lock/ticket/<id> HTTP/2.0", upstream: "fastcgi://unix:/var/run/server.sock:", host: "server.net", referrer: "https://server.net/osticket/scp/tickets.php?id={id}"
```

Not sure when the error first occurred but I'm pretty sure it's there since v1.15 (might even have been present in v1.14).

### Steps to Reproduce

Not exactly sure what triggers this and it's kind of hard to reproduce. I do know it happens occasionally, not all the time. Have tried to debug / reproduce it without any success. Pretty sure my lack of knowledge of the osTicket core is the/a problem here.

**Expected behavior:** [What you expected to happen]

No entries in our PHP error.log.

**Actual behavior:** [What actually happened]

Errors in our PHP error log and a possible side effect where users unintentionally hijack a ticket thread (ticket stays locked, lock is not being released). Although last thing might be a different issue but that might become clear once this problem is gone? :-)

### Versions

osTicket Version
v1.15.2 (cb6766e)

Web Server Software
nginx/1.21.0

MySQL Version
10.3.23

PHP Version
7.4.21 (PHP-FPM)

**Comment by LH-Eelko** [comment]
Updating this with more recent information, there have been a few updates in the mean time. We installed a fresh new server with RHEL 8.4 and transferred osTicket to it. We still see the (perhaps more verbose) error in our logfiles:

```
2022/10/11 12:15:35 [error] 3410614#0: *4587141 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: strtotime(): Argument #1 ($datetime) must be of type string, SqlExpression given in <path>/osticket/include/class.lock.php:66
Stack trace:
#0 <path>/osticket/include/class.lock.php(66): strtotime(Object(SqlExpression))
#1 <path>/osticket/include/class.lock.php(70): Lock->getExpireTime()
#2 <path>/osticket/include/ajax.tickets.php(226): Lock->getTime()
#3 <path>/osticket/include/class.dispatcher.php(145): TicketsAjaxAPI->acquireLock('31869')
#4 <path>/osticket/include/class.dispatcher.php(38): UrlMatcher->dispatch('ticket/31869', Array)
#5 <path>/osticket/include/class.dispatcher.php(120): Dispatcher->resolve('ticket/31869', Array)
#6 <docroot>" while reading response header from upstream, client: <ip>, server: <hostname>, request: "POST /osticket/scp/ajax.php/lock/ticket/<id> HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "<url>", referrer: "https://<url>/osticket/scp/tickets.php?id=<id>"
```
### Versions
osTicket Version
v1.16.3

Web Server Software
nginx/1.22.0

MySQL Version (MariaDB)
10.3.23

PHP Version
8.0.24 (PHP-FPM)

**Comment by LH-Eelko** [comment]
We're still seeing the exact same errors in v1.17.2 (so won't be reposting that). :)

Some software components have changed in the meantime;

### Versions
osTicket Version
v1.17.2

Web Server Software
nginx/1.23.3

MySQL Version (MariaDB)
10.6.10

PHP Version
8.1.11 (PHP-FPM)
