### ISSUE TITLE
DB Error #1054

### ISSUE THREAD

**Issue by tunes0710** [osTicket/osTicket#6001]
### Prerequisites

* [✓] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [✓] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [✓] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
In addition to getting the DB Error #5904 from [Here](https://github.com/osTicket/osTicket/issues/5904)
I also get 2 further DB 1054 errors

```
[INSERT INTO `ost_user__cdata` SET `notes`='', `user_id`= 3 ON DUPLICATE KEY UPDATE `notes`='']

Unknown column 'notes' in 'field list'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054', '[INSERT INTO `o...')<br />
#1 (root)/include/class.dynamic_forms.php(381): db_query('INSERT INTO `os...')<br />
#2 (root)/include/class.dynamic_forms.php(396): DynamicForm::updateDynamicDataView(Object(DynamicFormEntryAnswer), NULL)<br />
#3 (root)/include/class.signal.php(98): DynamicForm::updateDynamicFormEntryAnswer(Object(DynamicFormEntryAnswer), NULL)<br />
#4 (root)/include/class.orm.php(680): Signal::send('model.created', Object(DynamicFormEntryAnswer))<br />
#5 (root)/include/class.dynamic_forms.php(1536): VerySimpleModel->save(false)<br />
#6 (root)/include/class.dynamic_forms.php(1378): DynamicFormEntryAnswer->save(false)<br />
#7 (root)/include/class.dynamic_forms.php(1317): DynamicFormEntry->saveAnswers(NULL, false)<br />
#8 (root)/include/class.user.php(348): DynamicFormEntry->save()<br />
#9 (root)/include/class.user.php(421): User->addForm(Object(UserForm), 1, Array)<br />
#10 (root)/include/class.user.php(249): User->addDynamicData(Array)<br />
#11 (root)/include/class.ticket.php(4221): User::fromVars(Array, true)<br />
#12 (root)/include/class.mailfetch.php(905): Ticket::create(Array, Array, 'Email')<br />
#13 (root)/include/class.mailfetch.php(954): MailFetcher->createTicket(1)<br />
#14 (root)/include/class.mailfetch.php(1034): MailFetcher->fetchEmails()<br />
#15 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#16 (root)/include/class.cron.php(110): Cron::MailFetcher()<br />
#17 (root)/include/api.cron.php(19): Cron::run()<br />
#18 (root)/include/api.cron.php(40): CronApiController->run()<br />
#19 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#20 {main}
```

and 

```
[INSERT INTO `ost_user__cdata` SET `phone`='', `user_id`= 3 ON DUPLICATE KEY UPDATE `phone`='']

Unknown column 'phone' in 'field list'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054', '[INSERT INTO `o...')<br />
#1 (root)/include/class.dynamic_forms.php(381): db_query('INSERT INTO `os...')<br />
#2 (root)/include/class.dynamic_forms.php(396): DynamicForm::updateDynamicDataView(Object(DynamicFormEntryAnswer), NULL)<br />
#3 (root)/include/class.signal.php(98): DynamicForm::updateDynamicFormEntryAnswer(Object(DynamicFormEntryAnswer), NULL)<br />
#4 (root)/include/class.orm.php(680): Signal::send('model.created', Object(DynamicFormEntryAnswer))<br />
#5 (root)/include/class.dynamic_forms.php(1536): VerySimpleModel->save(false)<br />
#6 (root)/include/class.dynamic_forms.php(1378): DynamicFormEntryAnswer->save(false)<br />
#7 (root)/include/class.dynamic_forms.php(1317): DynamicFormEntry->saveAnswers(NULL, false)<br />
#8 (root)/include/class.user.php(348): DynamicFormEntry->save()<br />
#9 (root)/include/class.user.php(421): User->addForm(Object(UserForm), 1, Array)<br />
#10 (root)/include/class.user.php(249): User->addDynamicData(Array)<br />
#11 (root)/include/class.ticket.php(4221): User::fromVars(Array, true)<br />
#12 (root)/include/class.mailfetch.php(905): Ticket::create(Array, Array, 'Email')<br />
#13 (root)/include/class.mailfetch.php(954): MailFetcher->createTicket(1)<br />
#14 (root)/include/class.mailfetch.php(1034): MailFetcher->fetchEmails()<br />
#15 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#16 (root)/include/class.cron.php(110): Cron::MailFetcher()<br />
#17 (root)/include/api.cron.php(19): Cron::run()<br />
#18 (root)/include/api.cron.php(40): CronApiController->run()<br />
#19 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#20 {main}
```

This happens when I send in an email to the account in OsTicket for it to create a new ticket.

### Versions
Running v1.15.4 (6bd7884) Using LiteSpeed
MySQL - 10.3.31
PHP - 7.3.30

**Comment by JediKev** [comment]
@tunes0710 

Search is your friend. You can find the fix here:
- https://forum.osticket.com/d/100021-db-error-1054/2

Cheers.
