### ISSUE TITLE
PHP fatal error while installing

### ISSUE THREAD

**Issue by ChengxiX** [osTicket/osTicket#6050]
`
Hydrating :: lib/sonata-project/google-authenticator/src => auth-2fa/lib/Sonata/GoogleAuthenticator,
Hydrating :: lib/jasig/phpcas/source => auth-cas/lib/jasig/phpcas,
Hydrating :: lib/pear-pear.php.net/net_ldap2 => auth-ldap/include,
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/var/www/src/public/include/plugins/lib/pear-pear.php.net/net_ldap2): failed to open dir: No such file or directory in /var/www/src/public/include/plugins/make.php:481,
Stack trace:,
#1 /var/www/src/public/include/plugins/make.php(340): PluginBuilder->_hydrate(Array),
#0 /var/www/src/public/include/plugins/make.php(481): RecursiveDirectoryIterator->__construct('/var/www/src/pu...', 4096),
#2 /var/www/src/public/include/plugins/make.php(240): PluginBuilder->run(Array, Array),
#3 /var/www/src/public/include/plugins/make.php(704): Module->_run('make.php'),,
},
Generating autoload files,
Writing lock file,
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.,
  thrown in /var/www/src/public/include/plugins/make.php on line 481`

Then the installing progress stopped but the docker container didn't stop
This happens when even using the simpliest install method

**Comment by JediKev** [comment]
@ChengxiX 

You don’t appear to be running the recommended installation steps. Please follow our Installation Guide here:
- https://docs.osticket.com/en/latest/Getting%20Started/Installation.html

**Note:**
We are making changes to the plugins and their dependencies to function with PHP 8 and Composer 2. Stay tuned.

Cheers.

**Comment by ChengxiX** [comment]
Thanks for responding.
I am actually using a docker image osticket/osticket, [https://github.com/pi0/osticket-docker]()

**Comment by ntozier** [comment]
You are using a third party docker image.  You will be on your own for getting it to work.

**Comment by bobweston** [comment]
Hi ntozier, is there an official docker image available? (if you go to dockerhub, that docker image carries the osticket namespace.

https://hub.docker.com/r/osticket/osticket

If you follow that page's link to the Source Repository, it points to 

https://github.com/pi0/osticket-docker

I'm not using that image. But I had thought it was the official image because on dockerhub, it occupies the osticket namespace.

**Comment by JediKev** [comment]
@bobweston 

There is no official docker image available at this time (as none of us use docker). We will look into dockerhub using the official namespace issue; thanks for pointing it out.

Cheers.

**Comment by bobweston** [comment]
yeah. I'd love to see you all put out your own docker image. It certainly would make deployment easier for many folks.

We're running a Kubernetes cluster for most of our apps, so I would personally love to see you guys develop a docker image. As devs, it would allow you to control things like the version of php used, etc. Spinning up the app, for most users, would simply mean assigning some values for variables and running a single docker command (assuming the user has an external mysql instance and doesn't require a separate mysql docker container).

What I love about it is, I can spin up an identical version of my production osTicket stack on my local Mac. (including things like os version, php version, etc). I can test upgrades, etc on my local Mac before pulling the trigger and upgrading in production. If things don't work out, I simply remove the local osticket container and then try again with a new container.

This workflow makes my old one (using vagrant to try to recreate my production environment locally) seem clunky.

**Comment by comprofix** [comment]
I am currently working on building osTicket into a docker image for myself as I run most of my apps as Docker containers as well so as not overheard with a separate web server. I am happy work on this with the team if we can work towards an official docker image.
