### ISSUE TITLE
New ticket search causes DB error 1054

### ISSUE THREAD

**Issue by Peter1994** [osTicket/osTicket#6053]
Hi all,

Just started testing osTicket for our IT department. Everything has been working great so far except the following:

When I attempt to create a new ticket in the web interface and assign a creator to it, no results are shown:

![afbeelding](https://user-images.githubusercontent.com/1346743/151182581-b1dfb808-2f20-46c5-a4db-d1d2c6370484.png)

Instead a DB 1054 error occurs with the following output:

```
[SELECT A1.`id`,  A1.`name`,  A6.`address` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) LEFT JOIN `ost_organization` A3 ON (A1.`org_id` = A3.`id`) LEFT JOIN `ost_user_account` A4 ON (A1.`id` = A4.`user_id`) LEFT JOIN `ost_user__cdata` A5 ON (A1.`id` = A5.`user_id`) LEFT JOIN `ost_user_email` A6 ON (A1.`default_email_id` = A6.`id`) WHERE (A2.`address` LIKE '%peter%' OR A1.`name` LIKE '%peter%' OR A3.`name` LIKE '%peter%' OR A4.`username` LIKE '%peter%' OR A5.`phone` LIKE '%peter%') UNION ALL (SELECT A1.`id`,  A1.`name`,  A3.`address` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) LEFT JOIN `ost_user_email` A3 ON (A1.`default_email_id` = A3.`id`) WHERE A2.`address` IN ('Peter.<redacted>',  'peter.<redacted>',  'Peter.<redacted>',  'Peter.<redacted>',  'peter.<redacted>')) LIMIT 25] Unknown column 'A5.phone' in 'where clause'
 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054',  '[SELECT A1.`id`...')
 #1 (root)/include/class.orm.php(3466): db_query('SELECT A1.`id`, ...',  true,  true)
 #2 (root)/include/class.orm.php(3522): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2070): MySqlExecutor->getRow()
 #4 (root)/include/class.orm.php(2043): FlatArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(2022): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(2031): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1703): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1713): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1729): CachedResultSet->asArray()
 #10 (root)/include/ajax.users.php(98): CachedResultSet->getIterator()
 #11 (root)/include/class.dispatcher.php(145): UsersAjaxAPI->search()
 #12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('',  Array)
 #13 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('',  Array)
 #14 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users',  NULL)
 #15 (root)/scp/ajax.php(316): Dispatcher->resolve('/users')
 #16 {main}
```

Instance information:
![afbeelding](https://user-images.githubusercontent.com/1346743/151183242-91a023b3-901c-487a-8f7c-7c5a67b7ae11.png)

It's a fresh instance connected to our Windows AD environment. Can anyone offer some help here?

**Comment by JediKev** [comment]
@Peter1994 

Search is your friend:
- https://github.com/osTicket/osTicket/issues/6043

Cheers.

**Comment by Peter1994** [comment]
Hi JediKev,

Sorry for the duplicate issue. Will check the solution. Thanks!
