### ISSUE TITLE
error on ticket create (fresh install)

### ISSUE THREAD

**Issue by Crush33** [osTicket/osTicket#6091]
version 1.61.1
just tried to create a ticket on default web page after creating a filter rule. Got blank page and this error throwed :

```
[Thu Mar 03 22:40:48.729906 2022] [php:error] [pid 2347] [client 192.168.1.23:56496] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/html/osticket/upload/include/class.validator.php:187
Stack trace:
#0 /var/www/html/osticket/upload/include/class.validator.php(201): Validator::is_email()
#1 /var/www/html/osticket/upload/include/class.forms.php(1520): Validator::is_valid_email()
#2 /var/www/html/osticket/upload/include/class.forms.php(664): TextboxField->validateEntry()
#3 /var/www/html/osticket/upload/include/class.ticket.php(3987): FormField->getClean()
#4 /var/www/html/osticket/upload/include/class.ticket.php(4178): Ticket::filterTicketData()
#5 /var/www/html/osticket/upload/open.php(45): Ticket::create()
#6 {main}
thrown in /var/www/html/osticket/upload/include/class.validator.php on line 187, referer: http://192.168.1.22/open.php
```

thx for any help !

**Comment by ntozier** [comment]
Environment details?

**Comment by JediKev** [comment]
@Crush33 

Apply the below patch and do a fresh install:
- https://github.com/osTicket/osTicket/pull/6089

Cheers.
