### ISSUE TITLE
Uncaught Error: Call to a member function set() on null in include/class.schedule.php:370

### ISSUE THREAD

**Issue by tarekfellah** [osTicket/osTicket#6167]
### Prerequisites

[*] Do you have any errors in the PHP error log, or javascript console? Yes
[*] Did you check the [osTicket forums](https://forum.osticket.com/)? Yes
 [*] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Yes
 

### Description

I tried to upgrade Osticket from 1.12 to 15.7, i followed all steps in this [docs link](http://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html)  but the upgrade failed.
The PHP Error
PHP Fatal error: Uncaught Error: Call to a member function set() on null in /public_html/include/class.schedule.php:370
Stack trace:
#0 /include/upgrader/streams/core/00c949a6-8b923d61.task.php(9): Schedule::create(Array)
#1 /include/class.upgrader.php(348): ScheduleCreator->run(30)
#2 /include/class.upgrader.php(121): StreamUpgrader->doTask()
#3 /include/ajax.upgrader.php(35): Upgrader->call('doTask', Array)
#4 /include/class.dispatcher.php(145): UpgraderAjaxAPI->upgrade()
#5 /include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader', NULL)
#6 /scp/ajax.php(316): Dispatcher->resolve('/upgrader')
#7 {main}
thrown in /include/class.schedule.php on line 370

The database size is big about 50G

### Steps to Reproduce

1. Upload backup files
2. Add database
3. change ost-config.php
4. click upgrade button
5. The process tooke some time (3-4 minutes)
6. The upgrade failed

**Expected behavior:** Upgrade successfully made

**Actual behavior:** Upgrade failed

### Versions
![image](https://user-images.githubusercontent.com/4117950/168649831-7536eca7-dc36-443a-bdff-6b9af81948b8.png)

OS: Centos 7.9
WHM/Cpanel v102.0.15
Firefox 99.0 (64-bit)

**Comment by protich** [comment]
Looks like the issue happens when importing default schedules.  Did you get any SQL errors related to schedule table?

**Comment by tarekfellah** [comment]
Where can i find this errors?

**Comment by JediKev** [comment]
@tarekfellah 

In your MySQL error logs. You can check your MySQL config or consult the MySQL documentation to find the path to your MySQL error logs.

You can also check the osTicket System Logs to see if any SQL Errors were logged there as well.

Cheers.

**Comment by tarekfellah** [comment]
I found this error
` [ERROR] /usr/sbin/mysqld: Table './dev8_osticket_30_04_22/ost_file_chunk' is marked as crashed and last (automatic?) repair failed`

**Comment by tarekfellah** [comment]
I increased the max_execution_time and for 2 times the upgrade works successfully!

**Comment by tarekfellah** [comment]
@JediKev @protich 
I repeated the upgrade on production, now i got DB Error #1062
`[INSERT INTO `ost_schedule` SET `id` = 1, `flags` = 1, `name` = 'Monday - Friday 8am - 5pm with U.S. Holidays', `created` = NOW(), `updated` = NOW()] Duplicate entry '1' for key 'PRIMARY'<br /> <br /> ---- Trace ----<br /> #0 (racine)/include/mysqli.php(201): osTicket-&gt;logDBError('DB Error #1062', '[INSERT INTO `o...')<br /> #1 (racine)/include/class.orm.php(3466): db_query('INSERT INTO `os...', true, true)<br /> #2 (racine)/include/class.orm.php(658): MySqlExecutor-&gt;execute()<br /> #3 (racine)/include/class.schedule.php(319): VerySimpleModel-&gt;save(false)<br /> #4 (racine)/include/class.schedule.php(364): Schedule-&gt;save()<br /> #5 (racine)/include/class.schedule.php(369): Schedule::create(Array)<br /> #6 (racine)/include/upgrader/streams/core/00c949a6-8b923d61.task.php(9): Schedule::__create(Array)<br /> #7 (racine)/include/class.upgrader.php(348): ScheduleCreator-&gt;run(30)<br /> #8 (racine)/include/class.upgrader.php(121): StreamUpgrader-&gt;doTask()<br /> #9 (racine)/include/ajax.upgrader.php(35): Upgrader-&gt;__call('doTask', Array)<br /> #10 (racine)/include/class.dispatcher.php(145): UpgraderAjaxAPI-&gt;upgrade()<br /> #11 (racine)/include/class.dispatcher.php(38): UrlMatcher-&gt;dispatch('/upgrader', NULL)<br /> #12 (racine)/scp/ajax.php(316): Dispatcher-&gt;resolve('/upgrader')<br /> #13 {main}` 

What i noticed is that cron job was executing, it can be the cause of the problem?

**Comment by tarekfellah** [comment]
Any solution?

**Comment by tarekfellah** [comment]
I fixed the problem by migrating to new server
