### ISSUE TITLE
Error when switching language vi.phar

### ISSUE THREAD

**Issue by VN-CERT** [osTicket/osTicket#6264]
Hi
I install version **v1.17-rc4** (356e156)
MySQL: **8.0.30**
PHP: **8.0.23**
Everything worked perfectly until I installed the language pack 'vi.phar 158808, for version v1.14', after I switched to Vietnamese I couldn't see the opened tickets on the Dashboard. When I change the language back to English (en_us), everything works fine.

I also tried on **v1.16.3 the same error appeared**.
Version v1.15.8 Vietnamese language works fine

This is my log received

```
root@ubuntu:~# tail -100 /var/log/apache2/osticket.error.log
[Thu Sep 22 04:35:00.131402 2022] [php:error] [pid 26908] [client 10.70.38.233:19678] PHP Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /var/www/html/osticket/upload/include/staff/ticket-view.inc.php:409\nStack trace:\n#0 /var/www/html/osticket/upload/include/staff/ticket-view.inc.php(409): sprintf()\n#1 /var/www/html/osticket/upload/scp/tickets.php(565): require_once('...')\n#2 {main}\n thrown in /var/www/html/osticket/upload/include/staff/ticket-view.inc.php on line 409, referer: http://10.70.38.230/scp/index.php
```
![image](https://user-images.githubusercontent.com/72367463/191886122-3a6e572c-058e-4d71-aff8-8018aba6afe4.png)
![image](https://user-images.githubusercontent.com/72367463/191886142-58942e86-3d7e-422c-83b1-be0548be4c0d.png)
![image](https://user-images.githubusercontent.com/72367463/191886157-bbc38972-116e-48db-90e2-5b6fda385266.png)

Can you guide me?

**Comment by JediKev** [comment]
@VN-CERT 

I can see a potential issue as the current approved translation is malformed a little and since the Vietnamese language doesn’t have a plural form it has two translations in one which might be throwing the `_N()` method off resulting in the error. I can take a look at it and make the appropriate change in translation. The issue should be addressed the next time we build new language packs. I can also try to provide a new temporary build here once I fix the issue.

Cheers.

**Comment by VN-CERT** [comment]
Thank you very much!!

> @VN-CERT
> 
> I can see a potential issue as the current approved translation is malformed a little and since the Vietnamese language doesn’t have a plural form it has two translations in one which might be throwing the `_N()` method off resulting in the error. I can take a look at it and make the appropriate change in translation. The issue should be addressed the next time we build new language packs. I can also try to provide a new temporary build here once I fix the issue.
> 
> Cheers.

**Comment by tuanchunglc** [comment]
> Thank you very much!!
> 
> > @VN-CERT
> > I can see a potential issue as the current approved translation is malformed a little and since the Vietnamese language doesn’t have a plural form it has two translations in one which might be throwing the `_N()` method off resulting in the error. I can take a look at it and make the appropriate change in translation. The issue should be addressed the next time we build new language packs. I can also try to provide a new temporary build here once I fix the issue.
> > Cheers.

You can try change:
sprintf(_N('%d Closed Ticket', '%d Closed Tickets', $closed), $closed) to sprintf(_N('%d Closed Ticket', '%d Closed Tickets', $closed), $closed, '')

**Comment by VN-CERT** [comment]
> Thank you very much!!
> 
> > @VN-CERT
> > I can see a potential issue as the current approved translation is malformed a little and since the Vietnamese language doesn’t have a plural form it has two translations in one which might be throwing the `_N()` method off resulting in the error. I can take a look at it and make the appropriate change in translation. The issue should be addressed the next time we build new language packs. I can also try to provide a new temporary build here once I fix the issue.
> > Cheers.

I have seen a new language update for Vietnamese, but the error still seems to be unresolved

![image](https://github.com/osTicket/osTicket/assets/72367463/6bf40487-2a73-4491-923d-da97833f8816)

![image](https://github.com/osTicket/osTicket/assets/72367463/4ad545c1-fdae-4caf-a44b-28bd63013afe)

And log:

`[Tue Jun 13 07:43:29.930693 2023] [php:error] [pid 73762] [client 10.70.38.28:8285] PHP Fatal error:  Uncaught ArgumentCountError: 3 arguments are required, 2 given in /var/www/osTicket/upload/include/staff/ticket-view.inc.php:409\nStack trace:\n#0 /var/www/osTicket/upload/include/staff/ticket-view.inc.php(409): sprintf()\n#1 /var/www/osTicket/upload/scp/tickets.php(569): require_once('...')\n#2 {main}\n  thrown in /var/www/osTicket/upload/include/staff/ticket-view.inc.php on line 409, referer: http://10.70.38.230/scp/tickets.php?id=1
`

**Comment by Cuongyd196** [comment]
> > Thank you very much!!
> > > @VN-CERT
> > > I can see a potential issue as the current approved translation is malformed a little and since the Vietnamese language doesn’t have a plural form it has two translations in one which might be throwing the `_N()` method off resulting in the error. I can take a look at it and make the appropriate change in translation. The issue should be addressed the next time we build new language packs. I can also try to provide a new temporary build here once I fix the issue.
> > > Cheers.
> 
> You can try change: sprintf(_N('%d Closed Ticket', '%d Closed Tickets', $closed), $closed) to sprintf(_N('%d Closed Ticket', '%d Closed Tickets', $closed), $closed, '')

Where can i change?
