### ISSUE TITLE
oAuth2 nginx authentication redirection problem

### ISSUE THREAD

**Issue by dvillareal22** [osTicket/osTicket#6293]
We are using osticket 1.17 stable version. Oauth2 is not working properly. When you try to authenticate it says 404 after redirection.

We are using nginx and php 8.0.

Is there anything that we need to configure?

**Comment by protich** [comment]
you need to make sure` api/auth/(*)` is handled by `/api/http.php` 

Here is an example of location setting.

```nginx
    location ~ ^/api/(tickets|tasks|auth)(.*)$ {
        try_files $uri $uri/ /api/http.php?$query_string;
    }
```

**Comment by dvillareal22** [comment]
I already try that but this is what happen
![Screenshot 2022-10-04 130112](https://user-images.githubusercontent.com/2813862/193738172-32b7b5cf-0caf-45a7-8d21-c844789a024c.png)

**Comment by dvillareal22** [comment]
server {
    root /var/www/html/helpdesk/upload;
    index  index.php index.html index.htm;
    server_name  helpdesk.xxxxxxx.com www.helpdesk.xxxxxxxxx.com;

    client_max_body_size 2000M;
        client_body_buffer_size 100M;
        client_header_buffer_size 10M;
        large_client_header_buffers 2 10M;

        client_body_timeout 12;
        client_header_timeout 12;
        keepalive_timeout 15;
        send_timeout 10;

        gzip             on;
        gzip_comp_level  2;
        gzip_min_length  1000;
        gzip_proxied     expired no-cache no-store private auth;
        gzip_types       text/plain application/x-javascript text/xml text/css application/xml;

        set $path_info "";

        # Deny access to all files in the include directory
        location ~ /include {
                deny all;
                return 403;
        }

        # Requests to /api/* need their PATH_INFO set, this does that
        if ($request_uri ~ "^/api(/[^\?]+)") {
                set $path_info $1;
        }

    # /api/*.* should be handled by /api/http.php if the requested file does not exist

    location ~ ^/api/(tickets|tasks|auth)(.*)$ {
        try_files $uri $uri/ /api/http.php?$query_string;
    }
    # /scp/ajax.php needs PATH_INFO too, possibly more files need it hence the .*\.php
    if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
        set $path_info $1;
    }

    # Make sure requests to /scp/ajax.php/some/path get handled by ajax.php
    location ~ ^/scp/ajax.php/(.*)$ {
        try_files $uri $uri/ /scp/ajax.php$is_args$args;
       }

    location ~ ^/ajax.php/(.*)$ {
        try_files $uri $uri/ /ajax.php$is_args$args;
    }

    location / {
        index     index.php;
        #try_files $uri $uri/ /index.php$is_args$args;
    }



    location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info  ^(.+\.php)(/.+)$;
    fastcgi_index            index.php;
    fastcgi_pass             unix:/var/run/php/php8.0-fpm.sock;
    include                  fastcgi_params;
    fastcgi_param   PATH_INFO       $fastcgi_path_info;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

**Comment by narongarj** [comment]
Same problem here, I change my rewrite rules but still had the same problem: "URL not supported"
Try change my web.config with more specific rewrite rules, but nothing has changed.

**Comment by narongarj** [comment]
Some errors on log:
  thrown in phar:///var/www/osticket/include/plugins/auth-oauth2.phar/oauth2.php on line 511" while reading response header from upstream, client:xxx.xxx.xxx.xxx, server: osticket.xxx.cloud, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "suporte.xxx.xxx.cloud"
2022/10/05 11:27:39 [error] 58771#58771: *67 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "League\OAuth2\Client\Provider\GenericProvider" not found in phar:///var/www/osticket/include/plugins/auth-oauth2.phar/oauth2.php:511
Stack trace:
#0 phar:///var/www/osticket/include/plugins/auth-oauth2.phar/config.php(3): require_once()
#1 phar:///var/www/osticket/include/plugins/auth-oauth2.phar/auth.php(3): require_once('...')
#2 /var/www/osticket/include/class.plugin.php(180): include_once('...')
#3 /var/www/osticket/include/class.plugin.php(231): PluginManager::allInstalled()
#4 /var/www/osticket/include/class.plugin.php(146): PluginManager::allActive()
#5 /var/www/osticket/include/class.osticket.php(668): PluginManager->bootstrap()
#6 /var/www/osticket/main.inc.php(33): osTicket::start()
#7 /var/www/osticket/scp/staff.inc.php(20): require_once('...')
#8 /var/www/osticket/scp/tickets.php(17): require('...')
#9 {main}
  thrown in phar:///var/www/osticket/include/plugins/auth-oauth2.phar/oauth2.php on line 511" while reading response header from upstream, client: xxx.xxx.xxx..xxx, server: osticket.xxx.cloud, request: "GET /scp/tickets.php?a=search&search-type=&query= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "suporte.xxx.xxx", referrer: "https://suporte.xxx.xxx.br/scp/login.php"

**Comment by ChrisTG742** [comment]
Is that the latest phar of the auth-oauth2 plugin?
The line
`PHP Fatal error: Uncaught Error: Class "League\OAuth2\Client\Provider\GenericProvider" not found in phar:///var/www/osticket/include/plugins/auth-oauth2.phar/oauth2.php:511`
looks suspicious to me.

**Comment by ChrisTG742** [comment]
Another idea: For me, the "prompt=consent" property in the generated URL prevented the process to work. Try removing that in the URL in the address bar of the browser when the plugin generates the external request (MS login dialog appears) and reload the page by pressing enter.

I had the same issue when I tried to enable OAuth2 with getmail6. Maybe Microsoft has changed something internally.

**Comment by narongarj** [comment]
I correct the problem with PHAR, after thar I tried to remove "prompt=consent" but still not working.
Same error "URL not supported"
How to solve that redirect?

**Comment by ChristianGabs** [comment]
The best answer from osTicket is ( we do not care about nginx )

To fix the issue :

1. NGINX

```
    location ~ ^/api/(?:tickets|tasks|auth).*$ {
        try_files $uri $uri/ /api/http.php?$query_string;
    }
```

3. In include /include/class.osticket.php Line : 366

From  :

    function get_path_info() {
        if(isset($_SERVER['PATH_INFO']))
            return $_SERVER['PATH_INFO'];

        if(isset($_SERVER['ORIG_PATH_INFO']))
            return $_SERVER['ORIG_PATH_INFO'];

        //TODO: conruct possible path info.

        return null;
    }

TO :

    static function get_path_info() {
        if(isset($_SERVER['PATH_INFO']) && !empty($_SERVER['PATH_INFO']))
            return $_SERVER['PATH_INFO'];

        if(isset($_SERVER['ORIG_PATH_INFO']) && !empty($_SERVER['ORIG_PATH_INFO']))
            return $_SERVER['ORIG_PATH_INFO'];

        $request_uri = preg_replace('@\?.*$@', '', $_SERVER['REQUEST_URI']);

        if (strpos($request_uri, $_SERVER['SCRIPT_NAME']) !== false) {
            $guessed_pathinfo = preg_replace('#^'.preg_quote($_SERVER['SCRIPT_NAME']).'#', '', $request_uri);
        } else {
            $guessed_pathinfo = preg_replace('#^'.preg_quote(preg_replace('@/([^/]+)$@', '', $_SERVER['SCRIPT_NAME'])).'#', '', $request_uri);
        }
        if (!empty($guessed_pathinfo))
            return $guessed_pathinfo;

        return null;
    }


I'm not sure if they plan to do something about it but hopefully, this will fix your issue.

Regards

**Comment by JediKev** [comment]
@ChristianGabs 

Please don’t just assume things; that is totally not the case. In-fact we will be posting a fully working NGINX config on our documentation very soon.

Cheers.

**Comment by ChristianGabs** [comment]
@JediKev ,

I'm not assuming, based on all issues raised regarding Nginx special on routing, and we speaking about months ... months ago no one was trying to fix that.

Apologies, just my impression based on people raising and giving as well the solution but no one bothered to fix it :D

PS: Special when Nginx is used by most people, that should be fixed from the old version and I'm amazed the routing has not been fixed yet, In my case every time when an update has been done, I have to change that file to support my Nginx.
EX : https://github.com/osTicket/osTicket/issues/4090
Cheers

**Comment by ChrisTG742** [comment]
IMHO using isset() in combination with !empty() is generally a good idea with server-side variables, not only on Nginx.

**Comment by VoiletDragon** [comment]
I recently migrated from Apache to Nginx at work with a breeze and works with Microsofts Azure oAuth method login, You need to change the Server block to the following, no need for any fancy configuration.

```
        location ~ /include {
            deny all;
            return 403;
        }

        if ($request_uri ~ "^/api(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/api/(?:tickets|tasks|Auth).*$ {
            try_files $uri $uri/ /api/http.php?$query_string;
        }

        if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/scp/ajax.php/.*$ {
            try_files $uri $uri/ /scp/ajax.php?$query_string;
        }

        location / {
            try_files $uri $uri/ index.php;
        }

        location ~ \.php$ {
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
            fastcgi_pass unix:/run/php/php8.1-fpm.sock;
            fastcgi_param  PATH_INFO    $path_info;
        }
```

**Comment by d--j** [comment]
These nginx location blocks should reflect the `.htaccess` files osTicket has:

```
        location /include {
            deny all;
            return 403;
        }

        location / {
            try_files $uri $uri/ index.php;
            location ~ ^/api/(?!http.php/)(.*) {
                try_files $uri $uri/ /api/http.php/$1;
            }
            location ~ ^/pages/(?!index.php/)(.*) {
                try_files $uri $uri/ /pages/index.php/$1;
            }
            location ~ ^(.*[^/]\.php)(/|$) {
                include fastcgi_params;
                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                fastcgi_pass unix:/var/run/php.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
            }
        }
```

This should work for all `/api` and `/pages` requests – current and future ones.

**Comment by AndrewG10i** [comment]
> @ChristianGabs
> 
> Please don’t just assume things; that is totally not the case. In-fact we will be posting a fully working NGINX config on our documentation very soon.
> 
> Cheers.

@JediKev any updates where such documentation can be located? Also would be very helpful to have case when osTicket located in subfolder (https://site.com/osticket/) covered. Thank you!

P.S. So far I was able to make oauth2 working properly (I mean redirect back to /api/auth/oauth2) only after changing the function `get_path_info()` as per [this comment](https://github.com/osTicket/osTicket/issues/6293#issuecomment-1278609953) above.

**Comment by JediKev** [comment]
@AndrewG10i 

No update on the documentation yet, legacy has been lower on priority scale whilst we work on v2.0. NGINX has a osTicket recipe on their site however they updated their site and idk where the recipes are anymore but I found the [old link on way back machine](https://web.archive.org/web/20240511013836/https://www.nginx.com/resources/wiki/start/topics/recipes/osticket/). To note, you shouldn’t have to mess with the `get_path_info()` function at all. As far as the subdirectory part goes, you can find many posts and guides online on how to accomplish this. You can use location block with root, location block with an alias, etc.

Cheers.

**Comment by mainmind83** [comment]
About [function](https://github.com/osTicket/osTicket/issues/6293#issuecomment-1278609953) of @ChristianGabs 

> static function get_path_info() {

PHP is not exactly my preferred language, could it be clearer this way?

```
/**
 * Determines and returns the PATH_INFO for the current request.
 *
 * This function attempts to retrieve PATH_INFO from various server variables
 * or derive it from the REQUEST_URI if not explicitly available.
 * 
 * Steps:
 * 1. Check if PATH_INFO is directly available in the $_SERVER superglobal.
 * 2. Check if ORIG_PATH_INFO (alternative variable) is available.
 * 3. Extract the PATH_INFO from REQUEST_URI by removing query strings
 *    and matching it against SCRIPT_NAME or its directory.
 * 4. Return null if no PATH_INFO can be determined.
 *
 * @return string|null The derived PATH_INFO or null if unavailable.
 */
static function get_path_info() {
    // Check if PATH_INFO is directly set in the server variables
    if (!empty($_SERVER['PATH_INFO'])) {
        return $_SERVER['PATH_INFO'];
    }

    // Check if ORIG_PATH_INFO is set (used in some server configurations)
    if (!empty($_SERVER['ORIG_PATH_INFO'])) {
        return $_SERVER['ORIG_PATH_INFO'];
    }

    // Attempt to derive PATH_INFO from REQUEST_URI
    $request_uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

    // Check if SCRIPT_NAME is a prefix of REQUEST_URI
    if (strpos($request_uri, $_SERVER['SCRIPT_NAME']) === 0) {
        return substr($request_uri, strlen($_SERVER['SCRIPT_NAME']));
    }

    // Check if the script's directory is a prefix of REQUEST_URI
    $script_dir = dirname($_SERVER['SCRIPT_NAME']);
    if (strpos($request_uri, $script_dir) === 0) {
        return substr($request_uri, strlen($script_dir));
    }

    // Return null if no PATH_INFO can be determined
    return null;
}

```

NOTE: I found this page due to OAuth2 errors with Microsoft 365, do not forget to [download the latest version of the plugin](https://osticket.com/download/) if this is also your case
