### ISSUE TITLE
 DB Error #1054

### ISSUE THREAD

**Issue by ivanmankov** [osTicket/osTicket#6330]
How to fix?

[INSERT INTO `osthd_task__cdata` SET `field`=16, `task_id`= 1 ON DUPLICATE KEY UPDATE `field`=16] Unknown column 'field' in 'field list'<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(203): osTicket->logDBError()<br /> #1 (root)/include/class.dynamic_forms.php(389): db_query()<br /> #2 (root)/include/class.dynamic_forms.php(402): DynamicForm::updateDynamicDataView()<br /> #3 (root)/include/class.signal.php(98): DynamicForm::updateDynamicFormEntryAnswer()<br /> #4 (root)/include/class.orm.php(684): Signal::send()<br /> #5 (root)/include/class.dynamic_forms.php(1535): VerySimpleModel->save()<br /> #6 (root)/include/class.forms.php(1451): DynamicFormEntryAnswer->save()<br /> #7 (root)/include/class.task.php(1384): FormField->save()<br /> #8 (root)/include/ajax.tasks.php(238): Task->updateField()<br /> #9 (root)/include/class.dispatcher.php(151): TasksAjaxAPI->editField()<br /> #10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch()<br /> #11 (root)/include/class.dispatcher.php(120): Dispatcher->resolve()<br /> #12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch()<br /> #13 (root)/scp/ajax.php(326): Dispatcher->resolve()<br /> #14 {main}

![image](https://user-images.githubusercontent.com/35625651/197490628-e5b93a31-5b64-4141-ae06-a69e5b44bbbc.png)

**Comment by JediKev** [comment]
@ivanmankov 

You can try deleting task__cdata table and manually run cron until the table is recreated and fully repopulated. Then you can retest.

Also, next time please post things like this on the Forum.

Cheers.

**Comment by RikkiMasters** [comment]
We had a similar issue and making sure all of the variables are filled out on the form settings fixed it.
