### ISSUE TITLE
Task Print PHP Fatal Error

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#6388]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

`PHP Fatal error:  Uncaught Error: Non-static method DynamicFormEntry::forTask() cannot be called statically in C:\inetpub\osTicket\Live\include\staff\templates\task-print.tmpl.php:177
Stack trace:
#0 C:\inetpub\osTicket\Live\include\class.pdf.php(129): include()
#1 C:\inetpub\osTicket\Live\include\class.pdf.php(119): Task2PDF->_print()
#2 C:\inetpub\osTicket\Live\include\class.task.php(1077): Task2PDF->__construct()
#3 C:\inetpub\osTicket\Live\scp\tasks.php(225): Task->pdfExport()
#4 {main}
  thrown in C:\inetpub\osTicket\Live\include\staff\templates\task-print.tmpl.php on line 177`

### Steps to Reproduce

1. Print Task

**Expected behavior:** Print task with all details including the thread.
**Actual behavior:** Print preview opens with only task data. No thread information is presented.

### Versions

Server Information
--
osTicket Version | v1.17.2 (8fbc7ee) —  Up to date
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 5.7.40
PHP Version | 8.0.25

Client Information
--
Windows 10
Chrome Version 107.0.5304.107 (Official Build) (64-bit)

**Comment by JediKev** [comment]
@jdelhome3578 

I believe this will be addressed with the following:
- https://github.com/osTicket/osTicket/pull/6383

Cheers.
