### ISSUE TITLE
Recreating "ost__search" with "php manage.php cron search" is throwing a fatal error

### ISSUE THREAD

**Issue by AlexanderB-C** [osTicket/osTicket#6404]
I tried to recreate the "ost__search" table after I dropped it as stated in #2208 latest updates:
`php manage.php cron search`

The table is recreated successfully but it looks like per call of the above command only ~1000 entries of old tickets are added to the table.
So I called it repeatingly and at the 5th or 6th call I ran into the following issue:

```
***-sys@***:~/ticket.***.de$ /opt/plesk/php/8.0/bin/php manage.php cron search
PHP Fatal error:  Uncaught Error: Call to a member function getDateFormat() on null in /var/www/vhosts/***.de/ticket.***.de/include/class.format.php:837
Stack trace:
#0 /var/www/vhosts/***.de/ticket.***.de/include/class.forms.php(2333): Format::date()
#1 /var/www/vhosts/***.de/ticket.***.de/include/class.forms.php(2346): DatetimeField->format()
#2 /var/www/vhosts/***.de/ticket.***.de/include/class.forms.php(975): DatetimeField->toString()
#3 /var/www/vhosts/***.de/ticket.***.de/include/class.dynamic_forms.php(1499): FormField->searchable()
#4 /var/www/vhosts/***.de/ticket.***.de/include/class.search.php(517): DynamicFormEntryAnswer->getSearchable()
#5 /var/www/vhosts/***.de/ticket.***.de/include/cli/modules/cron.php(25): MysqlSearchBackend->IndexOldStuff()
#6 /var/www/vhosts/***.de/ticket.***.de/include/class.cli.php(240): CronManager->run()
#7 /var/www/vhosts/***.de/ticket.***.de/manage.php(70): Module->_run()
#8 /var/www/vhosts/***.de/ticket.***.de/include/class.cli.php(240): Manager->run()
#9 /var/www/vhosts/***.de/ticket.***.de/manage.php(79): Module->_run()
#10 {main}
  thrown in /var/www/vhosts/***.de/ticket.***.de/include/class.format.php on line 837
```

I think this is a bug.
I guess it refers to field values in table "ost_form_entry_values".
I checked this and it looks like datetime fields are added to this table and filled with NULL as default value once you add a custom form to a ticket.
The field with id 48 in the following screenshot is of type "datetime".
![grafik](https://user-images.githubusercontent.com/91258267/205967418-90bcf774-32a8-45fe-8178-58746087aa5c.png)

Is this a bug in this manage.php command that can be fixed?
Or is it an issue with my database as datetime fields are not supposed to be NULL?

Thanks & best regards
Alex

**Comment by JediKev** [comment]
@AlexanderB-C 

What version of osTicket are you running?

It's basically saying the global var `$cfg` is not available in this case (NULL) so it can't call `getDateFormat()` on NULL.

Cheers.

**Comment by AlexanderB-C** [comment]
Thanks for the reply @JediKev 

Ups, I forgot the most important thing...
I am running osTicket 1.17.2.

**Comment by AlexanderB-C** [comment]
But how can I make `$cfg` available now?

**Comment by AlexanderB-C** [comment]
Hi @JediKev

Can you please let me know what I can do now to get my "ost__search" table completely restored?
Can I somehow make `$cfg` available?

Thanks.

**Comment by JediKev** [comment]
@AlexanderB-C 

You really shouldn't drop this table unless absolutely required. However if you do you can simply recreate it using the installer's SQL CREATE statement for the table. Once you recreate the table you can go to `ost_config`, set `reindex` to `1`, and run cron manually a bunch of times until `reindex` gets set back to `0` automatically. Once complete you should have the search table fully restored and repopulated with data.

Cheers.
