### ISSUE TITLE
Reopen Count produces SQL errors and does not return results

### ISSUE THREAD

**Issue by MatterL** [osTicket/osTicket#6464]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Attempting to create a custom search or custom queue filter using the field "Reopen Count" results in SQL errors and that search breaks.

SQL errors are generated in large number and reference "A1.reopen_count" which does not appear to exist in the database despite using the default osTicket setup configuration.

### Steps to Reproduce

1. Click "Add Personal Queue"
2. Click "Add Other Field" and select "Reopen Count"
3. Assign "Reopen Count" to any Equal, Greater Than, or Less Than
4. Assign the blank field a number equal to or greater than 0
5. Give the search a title and click Save
6. The Reopen Count will now show NO parameters, the search will return 0 results, and SQL errors will begin generating

**Expected behavior:** Search tickets based on Reopen Count and create custom queues that search based on how many times a ticket has been reopened.

**Actual behavior:** The search does not function and SQL errors are generated.

### Error Message
```
[SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_department` B0 ON (A4.`object_type` = 'D' AND A4.`object_id` = B0.`id`) LEFT JOIN `ost_department` B1 ON (A7.`object_type` = 'D' AND A7.`object_id` = B1.`id`) WHERE A2.`state` = 'open' AND A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`reopen_count` > 0 AND ((A2.`state` = 'open' AND (A1.`staff_id` = 4 OR A5.`staff_id` = 4 OR A6.`object_type` = 'C' AND A8.`staff_id` = 4)) OR A1.`dept_id` IN (1, 4, 6) OR B0.`id` IN (1, 4, 6) OR A6.`object_type` = 'C' AND B1.`id` IN (1, 4, 6))) __]

Unknown column 'A1.reopen_count' in 'where clause'<br /> <br />
---- Backtrace ----<br />
#0 C:\inetpub\wwwroot\osticket\include\mysqli.php(207): osTicket->logDBError()<br />
#1 C:\inetpub\wwwroot\osticket\include\class.orm.php(3482): db_query()<br />
#2 C:\inetpub\wwwroot\osticket\include\class.orm.php(3538): MySqlExecutor->execute()<br />
#3 C:\inetpub\wwwroot\osticket\include\class.orm.php(2964): MySqlExecutor->getRow()<br />
#4 C:\inetpub\wwwroot\osticket\include\class.orm.php(1381): MySqlCompiler->compileCount()<br />
#5 C:\inetpub\wwwroot\osticket\include\class.search.php(906): QuerySet->count()<br />
#6 C:\inetpub\wwwroot\osticket\include\class.search.php(918): SavedQueue->getTotal()<br />
#7 C:\inetpub\wwwroot\osticket\include\staff\templates\queue-tickets.tmpl.php(124): SavedQueue->getCount()<br />
#8 C:\inetpub\wwwroot\osticket\scp\tickets.php(569): require_once('...')<br />
#9 {main}
```

### Versions

![image](https://user-images.githubusercontent.com/9290106/217328832-7e083e78-756d-426f-9fe0-b0623bb58970.png)

**Comment by JediKev** [comment]
@MatterL 

Please downgrade to PHP 8.1 and retest; PHP 8.2 is not yet supported.

Cheers.

**Comment by MatterL** [comment]
We'll downgrade to PHP 8.1 after hours and report back if the issue still occurs. Thank you for the swift reply.
