### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone ()

### ISSUE THREAD

**Issue by hgolshenas** [osTicket/osTicket#6589]
Hi
i installed the newer version of OsTicket v1.18 on iis 10 and php 8.1.21 and mysql 5.7
but i have this error :
PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone ()
and some forms like setting in admin panel does not load correct and many functions do not execute true.
my timezone in windows and php and mysql are same and it is "Iran Standard Time"

anybody can help me?

Regards

**Comment by JediKev** [comment]
@hgolshenas 

You need to provide the full stack trace so we can better look into this.

Cheers.

**Comment by hgolshenas** [comment]
@JediKev 

```
[30-Jul-2023 13:36:03 UTC] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in D:\WebSites\Support\include\class.misc.php:74
Stack trace:
#0 D:\WebSites\Support\include\class.misc.php(74): DateTimeZone->__construct('')
#1 D:\WebSites\Support\include\class.format.php(697): Misc::db2gmtime('2023-07-30 15:1...')
#2 D:\WebSites\Support\include\class.format.php(860): Format::__formatDate('2023-07-30 15:1...', '', true, 0, 3, '%x %X', 'UTC', false)
#3 D:\WebSites\Support\include\ajax.content.php(32): Format::daydatetime('2023-07-30 15:1...')
#4 D:\WebSites\Support\include\class.dispatcher.php(153): ContentAjaxAPI->syslog('3')
#5 D:\WebSites\Support\include\class.dispatcher.php(40): UrlMatcher->dispatch('log/3', Array)
#6 D:\WebSites\Support\include\class.dispatcher.php(122): Dispatcher->resolve('log/3', Array)
#7 D:\WebSites\Support\include\class.dispatcher.php(40): UrlMatcher->dispatch('/content/log/3', NULL)
#8 D:\WebSites\Support\scp\ajax.php(327): Dispatcher->resolve('/content/log/3')
#9 {main}
  thrown in D:\WebSites\Support\include\class.misc.php on line 74
```

**Comment by JediKev** [comment]
@hgolshenas 

Apparently the timezone your database is returning is not valid for PHP. Go to [this line](https://github.com/osTicket/osTicket/blob/develop/include/class.misc.php#L72), add `var_dump($cfg->getDbTimezone());die;`, redo the steps to replicate the error, and post the var_dump results here.

Cheers.

**Comment by hgolshenas** [comment]
@JediKev 

[Pasted a full repeat of logs; not the var_dump results as instructed]

**Comment by hgolshenas** [comment]
@JediKev i havent knowledge of php also!

**Comment by JediKev** [comment]
@hgolshenas 

Okay we will try an easier route. Login to the database, run the below query, and paste the results here.
```sql
SELECT @@GLOBAL.time_zone, @@GLOBAL.system_time_zone;
```

Cheers.

**Comment by hgolshenas** [comment]
@JediKev 
system ---- Iran Standard Time

Cheers

**Comment by JediKev** [comment]
@hgolshenas 

That is not what I asked for. Please follow the steps listed above.

Cheers.

**Comment by hgolshenas** [comment]
@JediKev 

![image](https://github.com/osTicket/osTicket/assets/140948010/77a60f74-8a56-4ed0-836b-602db2a32932)

Cheers

**Comment by JediKev** [comment]
@hgolshenas 

So "Iran Standard Time" does not appear to be a [supported timezone for PHP](https://www.php.net/manual/en/timezones.php). Try running the below query in MySQL and retest. If that works you will need to update your timezone setting in your my.cnf file to persist the change.
```sql
SET GLOBAL time_zone = 'Asia/Tehran';
```

**Note:**
Asia/Tehran should be +03:30 which is IRST. If not please replace it with the correct timezone name.

Cheers.

**Comment by hgolshenas** [comment]
@JediKev 
i try to change the timezone by several ways but every time i get the same error :
![image](https://github.com/osTicket/osTicket/assets/140948010/d1efb158-9c8f-4f5a-a8e7-aa3bed9d9c67)
what should i do?

Cheers

**Comment by JediKev** [comment]
@hgolshenas 

Sounds like you need to populate your MySQL timezone tables (scroll to **Populating the Time Zone Tables** section):
- https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html

Also, `(UTC+03:30)` is not a valid timezone; `+03:30` is though.

Cheers.

**Comment by hgolshenas** [comment]
@JediKev 
i change the time zone to +03:30 but i still have the error
