### ISSUE TITLE
undefined method EmailAccountConfig::toArray()

### ISSUE THREAD

**Issue by LeifSec** [osTicket/osTicket#6636]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
I am on v1.18.1 (fresh installation but existing config and database)

* [ ] Do you have any errors in the PHP error log, or javascript console?
Apache log
```
Call to undefined method EmailAccountConfig::toArray() in /var/www/osticket.int.axxteq.de/upload/include/class.email.php:814
Stack trace:\n#0 /var/www/osticket.int.axxteq.de/upload/include/class.email.php(785): EmailAccount->getBasicAuthCredentials()\n
#1 /var/www/osticket.int.axxteq.de/upload/include/class.email.php(760): mailAccount->getCredentials()\n
#2 /var/www/osticket.int.axxteq.de/upload/include/class.email.php(1179): EmailAccount->getFreshCredentials()\n
#3 /var/www/osticket.int.axxteq.de/upload/include/class.email.php(1239): MailBoxAccount->setInfo()\n
#4 /var/www/osticket.int.axxteq.de/upload/include/class.email.php(325): MailBoxAccount->update()\n
#5 /var/www/osticket.int.axxteq.de/upload/scp/emails.php(35): Email->update()\n
#6 {main}\n  thrown in /var/www/osticket.int.axxteq.de/upload/include/class.email.php on line 814, referer: http://osticket.int.axxteq.de/scp/emails.php?id=1
```
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
yes

### Description
see log above

### Steps to Reproduce

1. Emails
2. Remote Mailbox
3. configuration

**Expected behavior:** 
configuration data

**Actual behavior:**
nothing - see log above

### Versions
osTicket-Version 	v1.18.1 (0375576)
Server-Software 	Apache/2.4.57 (Debian)
MySQL-Version 	10.11.4
PHP-Version 	8.2.7
Firefox 120.0

**Comment by LeifSec** [comment]
[Solved by](https://forum.osticket.com/d/104086-undefined-method-for-emails/5)
