### ISSUE TITLE
issue in migration to 1.18 from 1.15.8

### ISSUE THREAD

**Issue by nayanprompt** [osTicket/osTicket#6637]
getting 500 error on page in php error log getting below error

PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_init() in /opt/hosting/osticket/upload/include/mysqli.php:28
Stack trace:
#0 /opt/hosting/osticket/upload/bootstrap.php(217): db_connect()
#1 /opt/hosting/osticket/upload/main.inc.php(28): Bootstrap::connect()
#2 /opt/hosting/osticket/upload/scp/staff.inc.php(20): require_once('...')
#3 /opt/hosting/osticket/upload/scp/admin.inc.php(16): require_once('...')
#4 /opt/hosting/osticket/upload/scp/settings.php(17): require('...')

**Comment by JediKev** [comment]
@nayanprompt 

Please use [the Forum](https://forum.osticket.com) for any assistance such as this. Once we can confirm it’s an actual bug then you can make an Issue on GitHub.

With this being said, it appears you do not have the php-mysql(i) extension installed and enabled. Please install and enable this extension, reload the webserver (and PHP-FPM if you’re running it), and retest.

Cheers.

**Comment by nayanprompt** [comment]
mysqli is installed and it works finr with php7.4 error while upgrading to 1.18 from 1.15.8 with php8.1 fpm
