### ISSUE TITLE
LDAP: Remote User Registration and Lookup Issue

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#6642]
### Description

We have been having an issue with agents not being able to lookup remote users and new users logging in and auto registering.

We have the following error in PHP when a user tries to log in:

``[28-Nov-2023 19:02:36 UTC] PHP Fatal error:  Uncaught Error: Call to a member function dn() on bool in phar://C:/inetpub/osTicket/Live/include/plugins/auth-ldap.phar/authentication.php:246
Stack trace:
#0 phar://C:/inetpub/osTicket/Live/include/plugins/auth-ldap.phar/authentication.php(479): LDAPAuthentication->authenticate()
#1 C:\inetpub\osTicket\Live\include\class.auth.php(341): ClientLDAPAuthentication->authenticate()
#2 C:\inetpub\osTicket\Live\login.php(52): AuthenticationBackend::process()
#3 {main}
  thrown in phar://C:/inetpub/osTicket/Live/include/plugins/auth-ldap.phar/authentication.php on line 246``

The user lookup AJAX call is coming back blank when it should return the remote user. `http://osticket/scp/ajax.php/users?q=`

When I have manually add the users to `ost_user_account` table the user can then login.
`'157', '308', '1', 'America/New_York', NULL, 'username', NULL, 'ldap.client.p1i3', '{\"browser_lang\":\"en_US\"}', '2023-11-28 14:17:00'`

I think the issue is that the DN is not getting resolved so the system can't register the user.

I have the same results from the published LDAP plugin 0.6.2 and the latest LDAP Code from [osTicket/osTicket-plugins/tree/develop/auth-ldap](https://github.com/osTicket/osTicket-plugins/tree/develop/auth-ldap).

### Versions

Server Information
--
osTicket Version | v1.18.1 (0375576) —  Up to date
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 8.0.35
PHP Version | 8.1.25
Windows Server 2019
PLatest LDAP Code from [osTicket/osTicket-plugins/tree/develop/auth-ldap](https://github.com/osTicket/osTicket-plugins/tree/develop/auth-ldap)

Client Information
--
Windows 10
Chrome Latest

**Comment by JediKev** [comment]
@jdelhome3578 

Hmm, I am unable to replicate this in my instance but I only have OpenLDAP. Is your Schema set to Autodetect?

The error is essentially stating it cannot call `dn()` on `current()` as it's `false` which means ~it was unable to establish a connection (or it has since dropped)~. Can you check your AD logs to see what's going on in greater detail?

**Edit:** Scratch the above it appears as though `$r->current()` is supposed to be a search result [based on this search](https://github.com/osTicket/osTicket-plugins/blob/develop/auth-ldap/authentication.php#L231). It's super strange as we have a check that returns `null` if there is no `$r->current()` right before we use it where you error is occurring. I don't see how this is happening unless `$r->current()` is somehow equating to `(bool) true`.

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev 

Schema is set to Microsoft AD

**Comment by JediKev** [comment]
@jdelhome3578 

Have you tried using Autodetect?

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev 

New error

``[28-Nov-2023 21:05:20 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method PEAR_Error::getValue() in C:\inetpub\osTicket\Live\include\plugins\auth-ldap\authentication.php:265
Stack trace:
#0 C:\inetpub\osTicket\Live\include\plugins\auth-ldap\authentication.php(308): LDAPAuthentication->getSchema()
#1 C:\inetpub\osTicket\Live\include\plugins\auth-ldap\authentication.php(452): LDAPAuthentication->search()
#2 C:\inetpub\osTicket\Live\include\class.auth.php(428): StaffLDAPAuthentication->search()
#3 phar://C:/inetpub/osTicket/Live/include/plugins/auth-passthru.phar/authenticate.php(74): AuthenticationBackend::searchUsers()
#4 C:\inetpub\osTicket\Live\include\class.auth.php(382): UserHttpAuthentication->signOn()
#5 C:\inetpub\osTicket\Live\login.php(119): AuthenticationBackend::processSignOn()
#6 {main}
  thrown in C:\inetpub\osTicket\Live\include\plugins\auth-ldap\authentication.php on line 265``

**Comment by jdelhome3578** [comment]
@JediKev 

https://github.com/pear/Net_LDAP2/issues/11

I tested this in a test environment and initial results are good.

**Comment by JediKev** [comment]
@jdelhome3578 

Ah, I see. They didn't have these changes when we needed them. I had to manually go in and fix these back in April and they just got to this in October. I will check out their updates and see what I missed. Afterwards I will update the Net_LDAP2 package altogether and provide you with a dev-build to test with. If that fully addresses the issue then we will merge the package updates and make new builds of the LDAP plugins.

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev 

The updated Net_LDAP2 package is working well in production.

I have it in `\include\plugins\auth-ldap\include\Net`

**Comment by jdelhome3578** [comment]
@JediKev I found an issue not sure if it is related.

`https://helpdesk.org/scp/ajax.php/users/select/auth%3Aldap.p1i3%3ACN%3DFirst%20Last%2COU%3DUsers%2COU%3DDomain%20User%20Group%2CDC%3Ddomain%2CDC%3Dlocal` works fine to add a remote user from user page.

`https://helpdesk.org/scp/ajax.php/thread/10301/add-collaborator/addcc/147` local users work fine.

`https://helpdesk.org/scp/ajax.php/thread/10301/add-collaborator/addcc/auth%3Aldap.p1i3%3ACN%3DFirst%20Last%2COU%3DUsers%2COU%3DDomain%20User%20Group%2CDC%3Ddomain%2CDC%3Dlocal` comes back with a 400 error URL not supported

**Comment by JediKev** [comment]
@jdelhome3578 

This should fix it:
- https://github.com/osTicket/osTicket/pull/6695

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev 
Thanks, it is working again.
